import { buildInsightArticle } from "../insights.helpers";
import { getSharedSources } from "../insights.registry";
import type { InsightsContent } from "../insights.types";

const ctaAudit = { label: "Demander un audit SEO gratuit", href: "/free-seo-audit" };
const ctaCall = { label: "Reserver un appel strategie", href: "/book-a-call" };

export const insights: InsightsContent = {
  ui: {
    insights: "Analyses",
    home: "Accueil",
    allCategories: "Toutes les categories",
    featured: "Dossier a la une",
    latest: "Dernieres analyses",
    readArticle: "Lire l'article",
    readMore: "Lire la suite",
    searchPlaceholder: "Rechercher par sujet, service ou mot-cle",
    filterByCategory: "Categorie",
    filterByTopic: "Sujet",
    filterByService: "Service",
    noResults: "Aucune analyse publiee ne correspond a ces filtres.",
    minutes: "min de lecture",
    published: "Publie",
    updated: "Mis a jour",
    tableOfContents: "Table des matieres",
    executiveSummary: "Resume executif",
    keyTakeaways: "Points cles",
    sources: "Sources et references",
    relatedServices: "Services associes",
    relatedSample: "Exemple associe",
    relatedArticles: "Articles associes",
    startFreeAudit: "Demarrer l'audit gratuit",
    author: "Auteur",
    finalCta: "Prochaine etape",
    categoryContext: "Contexte de la categorie",
    topicCluster: "Carte du cluster",
    recommendedPaths: "Parcours de lecture recommandes",
    sourceLabel: "Source",
    accessed: "Consulte le",
    evidence: "Preuve",
    searchGrowthMap: "Carte de croissance search",
  },
  hub: {
    eyebrow: "Analyses Taskcover",
    h1: "Une publication search pour Google, la recherche IA et la croissance du revenu.",
    description:
      "Bibliotheque editoriale multilingue pour la strategie SEO, les fondations techniques, l'autorite de contenu, la visibilite IA, l'intelligence PPC et le SEO international.",
    featuredTitle: "Commencer par le dossier search 2026",
    topicMapTitle: "Une carte de croissance search, pas une simple archive de blog",
    topicMapDescription:
      "Les contenus sont organises par decision business: fondations, autorite, visibilite dans les reponses IA, intelligence paid-organic, expansion de marche et accompagnement d'equipe.",
    pathsTitle: "Parcours de lecture recommandes",
    paths: [
      {
        title: "Pour dirigeants et responsables marketing",
        body: "Commencez par le paysage search 2026, puis reliez SEO et PPC dans un meme modele de croissance.",
        href: "/insights/seo-guides/seo-2026-google-ai-search-revenue-growth",
      },
      {
        title: "Pour equipes techniques et produit",
        body: "Utilisez la checklist d'audit technique avant les migrations, lancements et deploiements internationaux.",
        href: "/insights/technical-seo/technical-seo-audit-checklist-growing-websites",
      },
      {
        title: "Pour contenu et autorite",
        body: "Construisez des actifs qui repondent a l'intention, peuvent etre cites et mènent vers une action claire.",
        href: "/insights/content-authority/content-rankings-citations-leads",
      },
    ],
    cta: {
      title: "Transformer la lecture en plan de croissance search.",
      body: "Utilisez l'audit gratuit ou un appel strategie pour appliquer ces cadres a votre site, vos marches et vos objectifs.",
      primary: ctaAudit,
      secondary: ctaCall,
    },
  },
  author: {
    name: "Taskcover Editorial Team",
    description:
      "Taskcover Editorial Team publie des guides pratiques sur le SEO, la recherche IA, l'autorite de contenu, l'intelligence paid search et la strategie de croissance search.",
  },
  categories: {
    "seo-guides": {
      slug: "seo-guides",
      label: "Guides SEO",
      eyebrow: "Guides strategiques",
      h1: "Guides SEO pour la croissance search",
      description: "Cadres pour prioriser le SEO, Google organique, les reponses IA, l'autorite et les resultats business.",
      context: "Cette categorie aide les decideurs a comprendre ce que le SEO doit produire, comment il se relie au revenu et quoi prioriser.",
      visualVariant: "guide",
      relatedServices: [{ label: "Agence SEO", href: "/services/seo-agency" }, { label: "Audit SEO", href: "/services/seo-audit" }],
      relatedIndustries: [{ label: "SEO SaaS", href: "/industries/saas-seo" }],
      relatedMarkets: [{ label: "Agence SEO USA", href: "/markets/usa-seo-agency" }],
      curatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth"],
      cta: { title: "Besoin d'une feuille de route search?", body: "Commencez par un diagnostic avant de choisir les tactiques.", primary: ctaAudit },
    },
    "ai-search": {
      slug: "ai-search",
      label: "Recherche IA & GEO",
      eyebrow: "Visibilite dans les reponses",
      h1: "Recherche IA et GEO",
      description: "Mesurer les mentions de marque, citations, entites et sources dans les experiences de reponse IA.",
      context: "La mesure IA est utile comme intelligence directionnelle, pas comme attribution parfaite.",
      visualVariant: "ai",
      relatedServices: [{ label: "Optimisation recherche IA", href: "/services/ai-search-optimization" }, { label: "Marketing de contenu", href: "/services/content-marketing" }],
      relatedIndustries: [{ label: "SEO Education", href: "/industries/education-seo" }],
      relatedMarkets: [{ label: "Agence SEO Canada", href: "/markets/canada-seo-agency" }],
      curatedArticleSlugs: ["measure-ai-search-visibility"],
      cta: { title: "Cartographier les ecarts IA.", body: "Analysez entites, sources et couverture avant de multiplier les tactiques.", primary: ctaCall },
    },
    "technical-seo": {
      slug: "technical-seo",
      label: "SEO technique",
      eyebrow: "Crawl, rendu, index",
      h1: "Systemes de SEO technique",
      description: "Audits de crawl, indexation, architecture, canonicalisation, performance, schema, international et migrations.",
      context: "Le SEO technique doit reduire le risque search et debloquer la performance, pas produire une liste infinie d'alertes.",
      visualVariant: "technical",
      relatedServices: [{ label: "SEO technique", href: "/services/technical-seo" }, { label: "Audit SEO", href: "/services/seo-audit" }],
      relatedIndustries: [{ label: "SEO e-commerce", href: "/industries/ecommerce-seo" }],
      relatedMarkets: [{ label: "Agence SEO Australie", href: "/markets/australia-seo-agency" }],
      curatedArticleSlugs: ["technical-seo-audit-checklist-growing-websites"],
      cta: { title: "Auditer la fondation technique.", body: "Utilisez une structure d'audit avant d'engager du temps d'ingenierie.", primary: { label: "Voir les audits exemples", href: "/work/sample-audits" } },
    },
    "content-authority": {
      slug: "content-authority",
      label: "Contenu & Autorite digitale",
      eyebrow: "Systemes d'autorite",
      h1: "Contenu et autorite digitale",
      description: "Construire du contenu utile, des preuves, des liens internes, des actifs RP digitales et des chemins de conversion.",
      context: "L'autorite vient d'une couverture utile, de preuves credibles, d'entites claires et de chemins d'action.",
      visualVariant: "authority",
      relatedServices: [{ label: "Marketing de contenu", href: "/services/content-marketing" }, { label: "RP digitales et liens", href: "/services/digital-pr-link-building" }],
      relatedIndustries: [{ label: "SEO Voyage", href: "/industries/travel-seo" }],
      relatedMarkets: [{ label: "Agence SEO USA", href: "/markets/usa-seo-agency" }],
      curatedArticleSlugs: ["content-rankings-citations-leads"],
      cta: { title: "Construire l'autorite avec des preuves.", body: "Priorisez les actifs capables de gagner classements, citations, liens et prospects qualifies.", primary: ctaCall },
    },
    "local-international-seo": {
      slug: "local-international-seo",
      label: "SEO local & international",
      eyebrow: "Marches et localisation",
      h1: "SEO local et international",
      description: "Architecture de marche, localisation, autorite locale, hreflang et sequence de deploiement multi-region.",
      context: "Le SEO international fonctionne quand strategie de marche, architecture, localisation et autorite se renforcent.",
      visualVariant: "international",
      relatedServices: [{ label: "SEO international", href: "/services/international-seo" }, { label: "SEO local", href: "/services/local-seo" }],
      relatedIndustries: [{ label: "SEO Voyage", href: "/industries/travel-seo" }, { label: "SEO Education", href: "/industries/education-seo" }],
      relatedMarkets: [{ label: "Agence SEO USA", href: "/markets/usa-seo-agency" }, { label: "Agence SEO Canada", href: "/markets/canada-seo-agency" }, { label: "Agence SEO Australie", href: "/markets/australia-seo-agency" }],
      curatedArticleSlugs: ["international-seo-usa-canada-australia"],
      cta: { title: "Planifier avant de traduire.", body: "Cartographiez marches, langues et ecarts d'autorite en premier.", primary: ctaCall },
    },
    "ppc-search-intelligence": {
      slug: "ppc-search-intelligence",
      label: "PPC & Intelligence search",
      eyebrow: "Paid et organique",
      h1: "PPC et intelligence search",
      description: "Utiliser ensemble les donnees paid et organiques sans pretendre que chaque canal convient toujours.",
      context: "Le paid search teste et capte vite; le SEO compose quand requete, contenu et fondation le justifient.",
      visualVariant: "ppc",
      relatedServices: [{ label: "Gestion PPC", href: "/services/ppc-management" }, { label: "Agence SEO", href: "/services/seo-agency" }],
      relatedIndustries: [{ label: "SEO Franchise et local", href: "/industries/franchise-local-seo" }],
      relatedMarkets: [{ label: "Agence SEO USA", href: "/markets/usa-seo-agency" }],
      curatedArticleSlugs: ["seo-vs-ppc-search-growth-system"],
      cta: { title: "Relier paid et organique.", body: "Utilisez requetes, pages d'atterrissage et economie de conversion ensemble.", primary: ctaCall },
    },
    "seo-mentor": {
      slug: "seo-mentor",
      label: "SEO Mentor",
      eyebrow: "Conseil et montee en competence",
      h1: "Hub SEO Mentor",
      description: "Contenus d'accompagnement pour ameliorer le jugement SEO, les revues et la priorisation.",
      context: "Cette categorie prepare de futurs contenus mentorat et regroupe les guides utiles des autres clusters.",
      visualVariant: "mentor",
      relatedServices: [{ label: "Service SEO Mentor", href: "/services/seo-mentor-service" }],
      relatedIndustries: [{ label: "SEO SaaS", href: "/industries/saas-seo" }],
      relatedMarkets: [{ label: "Agence SEO Canada", href: "/markets/canada-seo-agency" }],
      curatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "technical-seo-audit-checklist-growing-websites", "measure-ai-search-visibility", "content-rankings-citations-leads", "seo-vs-ppc-search-growth-system"],
      cta: { title: "Renforcer le jugement SEO interne.", body: "Utilisez le mentorat pour challenger strategie, roadmaps et execution.", primary: { label: "Explorer SEO Mentor", href: "/services/seo-mentor-service" } },
    },
  },
  articles: [
    buildInsightArticle({
      id: "insight-fr-seo-2026",
      slug: "seo-2026-google-ai-search-revenue-growth",
      translationGroupId: "seo-2026",
      locale: "fr",
      title: "SEO en 2026 : Google, recherche IA et croissance du revenu",
      excerpt: "Un modele operationnel pour proteger la visibilite Google, preparer les reponses IA, renforcer l'autorite et relier le SEO au revenu.",
      category: "seo-guides",
      tags: ["Strategie SEO", "Recherche IA", "Revenu", "Entites"],
      readingTime: 12,
      coverImageAlt: "Tableau de bord search reliant Google, recherche IA, autorite et revenu.",
      coverImageCaption: "Un programme search doit relier acces technique, utilite du contenu, autorite et resultats commerciaux.",
      focusKeyword: "SEO en 2026",
      secondaryKeywords: ["SEO recherche IA", "croissance search", "strategie Google organique"],
      intent: "Comprendre les priorites SEO modernes.",
      audience: "Fondateurs, directions marketing, responsables SEO et equipes revenu",
      funnelStage: "consideration",
      coreQuestion: "Que prioriser en SEO quand Google, les reponses IA et le revenu comptent ensemble?",
      primaryEntity: "Optimisation pour les moteurs de recherche",
      supportingEntities: ["Google Search", "reponses IA", "autorite de contenu", "SEO technique", "mesure de conversion"],
      topicCluster: "Strategie de croissance search",
      parentPillar: "Guides SEO",
      uniqueInformationGain: "Un cadre de 90 jours separant fondations, visibilite, autorite et instrumentation revenu.",
      refreshTrigger: "Actualiser lorsque les recommandations Google, les controles IA ou l'architecture Taskcover evoluent.",
      sources: getSharedSources(["google-seo-starter", "google-helpful-content", "google-ai-features", "google-structured-data"]),
      claims: [
        { id: "seo-no-guarantee", text: "Google ne garantit pas qu'un changement SEO produise un classement immediat.", requiresEvidence: true, sourceIds: ["google-seo-starter"] },
        { id: "people-first-content", text: "Les recommandations Google privilegient le contenu utile, fiable et pense pour les personnes.", requiresEvidence: true, sourceIds: ["google-helpful-content"] },
      ],
      originalInsights: ["Traiter la visibilite IA comme une couche supplementaire, pas comme un remplacement du SEO.", "Instrumenter le revenu avant d'augmenter le volume de contenu."],
      serviceLinks: [{ label: "Agence SEO", href: "/services/seo-agency" }, { label: "Optimisation recherche IA", href: "/services/ai-search-optimization" }, { label: "Audit SEO", href: "/services/seo-audit" }],
      industryLinks: [{ label: "SEO SaaS", href: "/industries/saas-seo" }],
      marketLinks: [{ label: "Agence SEO USA", href: "/markets/usa-seo-agency" }, { label: "Agence SEO Canada", href: "/markets/canada-seo-agency" }],
      caseStudyLinks: [{ label: "Cadres de croissance search", href: "/work/search-growth-frameworks" }],
      sampleAuditLinks: [{ label: "Roadmap search 90 jours", href: "/work/sample-audits/90-day-search-growth-roadmap" }],
      relatedArticleSlugs: ["measure-ai-search-visibility", "seo-vs-ppc-search-growth-system", "content-rankings-citations-leads"],
      metaTitle: "SEO en 2026 : Google, IA et croissance du revenu",
      metaDescription: "Cadre SEO 2026 pour visibilite Google, recherche IA, autorite, mesure et croissance du revenu.",
      breadcrumbLabel: "SEO en 2026",
      blocks: [
        { type: "direct-answer", title: "Reponse directe", answer: "En 2026, le SEO doit etre gere comme un systeme de croissance search : acces technique, contenu utile, clarte des entites, autorite, preparation aux reponses IA et mesure de conversion." },
        { type: "key-takeaways", title: "Points cles", items: ["La visibilite organique depend encore de pages accessibles et utiles.", "La recherche IA ajoute une couche ou entites, citations et sources comptent.", "La mesure doit suivre la demande qualifiee, pas seulement les positions.", "Le plan le plus robuste corrige les fondations avant de produire plus."] },
        { type: "heading", level: 2, text: "Le paysage search est devenu multicouche", id: "paysage-search" },
        { type: "paragraph", text: "Une entreprise ne se bat plus uniquement pour un lien bleu. Elle cherche une presence utile dans les resultats organiques, les elements locaux, les apercus IA, les comparaisons et les recherches de marque." },
        { type: "paragraph", text: "Le travail durable reste connu : rendre le site accessible, clarifier l'offre, publier des contenus qui resolvent un besoin et faciliter l'etape commerciale suivante. La difference est l'exigence de preuves et de coherence." },
        { type: "evidence", claimId: "seo-no-guarantee", summary: "La documentation Google presente le SEO comme une aide a la decouverte et a la comprehension, sans promesse de classement.", sourceIds: ["google-seo-starter"] },
        { type: "comparison-table", caption: "Modele de priorisation SEO 2026.", columns: ["Couche", "A inspecter", "Question business"], rows: [["Fondation technique", "Crawl, rendu, index, canonicals, performance", "Les bonnes pages sont-elles accessibles?"], ["Utilite du contenu", "Intention, profondeur, preuves, liens internes", "La page aide-t-elle mieux que les alternatives?"], ["Entite et autorite", "Coherence marque, citations, actifs RP", "La source est-elle credible?"], ["Revenu", "CTA, formulaires, analytics, qualite lead", "La demande peut-elle devenir pipeline?"]] },
        { type: "heading", level: 2, text: "Preparation IA sans surpromettre", id: "preparation-ia" },
        { type: "paragraph", text: "Les surfaces IA ne sont pas un canal analytics propre. Elles peuvent citer, mentionner ou resumer sans clic. La mesure directionnelle est utile, mais l'attribution parfaite serait trompeuse." },
        { type: "checklist", title: "Checklist de preparation IA", items: [{ label: "Entites claires", detail: "Utiliser des informations coherentes sur marque, services, marches et auteur." }, { label: "Sections citables", detail: "Rendre definitions, cadres et preuves faciles a reprendre." }, { label: "Sources propres", detail: "Citer des sources primaires pour les affirmations factuelles." }, { label: "Chemins de conversion", detail: "Relier les guides aux services, audits, cas et contact sans forcer la vente." }] },
        { type: "steps", title: "Sequence 90 jours", steps: [{ title: "Jours 1-20 : diagnostiquer", body: "Auditer crawl, indexation, templates, analytics et pages qui captent deja la demande." }, { title: "Jours 21-45 : renforcer", body: "Ameliorer les pages prioritaires avec reponses, liens internes, schema et CTA." }, { title: "Jours 46-70 : creer l'autorite", body: "Construire cadres, comparatifs et guides fondes sur des preuves." }, { title: "Jours 71-90 : relire le revenu", body: "Comparer requetes, leads, conversions assistees et retours commerciaux." }] },
        { type: "faq", items: [{ question: "La recherche IA remplace-t-elle le SEO?", answer: "Non. Elle modifie la decouverte et la mesure de la visibilite, mais depend encore de sources accessibles, utiles et fiables." }, { question: "Faut-il encore suivre les positions?", answer: "Oui, avec la couverture de requetes, les leads, les conversions assistees, la marque et les mentions IA." }] },
        { type: "cta", title: "Besoin d'un plan search sur 90 jours?", body: "Commencez par un audit qui separe risque technique, opportunite contenu, preparation IA et mesure revenu.", primary: ctaAudit, secondary: ctaCall },
      ],
      faqItems: [{ question: "La recherche IA remplace-t-elle le SEO?", answer: "Non. Elle modifie la decouverte et la mesure de la visibilite, mais depend encore de sources accessibles, utiles et fiables." }, { question: "Faut-il encore suivre les positions?", answer: "Oui, avec la couverture de requetes, les leads, les conversions assistees, la marque et les mentions IA." }],
    }),
    buildInsightArticle({
      id: "insight-fr-ai-visibility",
      slug: "measure-ai-search-visibility",
      translationGroupId: "ai-visibility",
      locale: "fr",
      title: "Comment mesurer la visibilite dans la recherche IA",
      excerpt: "Un modele de mesure honnete pour les reponses IA : couverture, mentions, citations, coherence des entites, qualite des sources et limites.",
      category: "ai-search",
      tags: ["Visibilite IA", "GEO", "Entites", "Citations"],
      readingTime: 10,
      coverImageAlt: "Carte de visibilite IA avec mentions, citations, sources et requetes.",
      coverImageCaption: "La mesure IA doit etre directionnelle, repetable et claire sur ses limites.",
      focusKeyword: "mesurer visibilite recherche IA",
      secondaryKeywords: ["suivi visibilite IA", "mesure GEO", "citations IA SEO"],
      intent: "Evaluer la presence dans les experiences de reponse IA.",
      audience: "Responsables SEO, contenus et directions marketing",
      funnelStage: "consideration",
      coreQuestion: "Comment mesurer la visibilite IA sans promettre une attribution parfaite?",
      primaryEntity: "Visibilite dans la recherche IA",
      supportingEntities: ["reponses IA", "mentions de marque", "citations", "coherence entite", "qualite source"],
      topicCluster: "Recherche IA & GEO",
      parentPillar: "Recherche IA & GEO",
      uniqueInformationGain: "Un tableau de bord leger qui separe couverture, citations, exactitude et limites.",
      refreshTrigger: "Actualiser quand les produits de recherche IA changent leurs citations ou controles.",
      sources: getSharedSources(["google-ai-features", "google-helpful-content", "google-seo-starter"]),
      claims: [{ id: "ai-search-visibility", text: "Google documente les fonctionnalites IA dans l'apparence Search et donne des recommandations aux proprietaires de sites.", requiresEvidence: true, sourceIds: ["google-ai-features"] }],
      originalInsights: ["Separer presence IA et performance business; la premiere est une intelligence de visibilite."],
      serviceLinks: [{ label: "Optimisation recherche IA", href: "/services/ai-search-optimization" }, { label: "Marketing de contenu", href: "/services/content-marketing" }],
      industryLinks: [{ label: "SEO Education", href: "/industries/education-seo" }],
      sampleAuditLinks: [{ label: "Revue de visibilite IA", href: "/work/sample-audits/ai-search-visibility-review" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "content-rankings-citations-leads", "technical-seo-audit-checklist-growing-websites"],
      metaTitle: "Comment mesurer la visibilite dans la recherche IA",
      metaDescription: "Cadre de mesure pour la visibilite IA : couverture des reponses, citations, mentions, entites, qualite source et limites.",
      breadcrumbLabel: "Mesurer la visibilite IA",
      blocks: [
        { type: "direct-answer", title: "Reponse directe", answer: "Mesurez la visibilite IA avec des ensembles de requetes repetables, la couverture des reponses, les mentions de marque, les citations, la qualite des sources, l'exactitude des entites et la comparaison concurrentielle." },
        { type: "key-takeaways", title: "Points cles", items: ["La visibilite IA n'est pas une position unique.", "Les requetes doivent etre groupees par intention, marche et theme.", "Mentions et citations doivent etre suivies separement.", "Une revue humaine reste necessaire."] },
        { type: "heading", level: 2, text: "Definir la visibilite avant de la mesurer", id: "definition" },
        { type: "paragraph", text: "La visibilite peut signifier etre cite, mentionne, resume ou absent alors que des concurrents apparaissent. Melanger ces signaux dans un score opaque cache les decisions a prendre." },
        { type: "definition", term: "Visibilite IA", definition: "Presence observable, exactitude et qualite de citation d'une marque ou d'une source dans les reponses IA pour un ensemble de requetes defini." },
        { type: "checklist", title: "Concevoir l'ensemble de requetes", items: [{ label: "Intention commerciale", detail: "Inclure services, fournisseurs, prix et comparaisons." }, { label: "Intention informationnelle", detail: "Inclure guides, definitions, checklists et cadres." }, { label: "Contexte marche", detail: "Separer USA, Canada, Australie, local et multilingual." }, { label: "Concurrents", detail: "Suivre un groupe stable de concurrents, medias et sources officielles." }] },
        { type: "comparison-table", caption: "Indicateurs de visibilite IA.", columns: ["Indicateur", "Ce qu'il indique", "Limite"], rows: [["Couverture", "Le sujet apparait dans une reponse", "Ne prouve pas l'influence de votre marque"], ["Mention", "La marque est nommee", "Peut avoir peu de valeur sans contexte"], ["Citation", "Une URL est citee", "Les formats varient"], ["Exactitude entite", "Services et marches sont corrects", "Revue manuelle requise"]] },
        { type: "callout", title: "Limite de mesure", body: "Ne presentez pas la visibilite IA comme attribution revenu exacte sans preuves de clic, lead et vente.", tone: "amber" },
        { type: "steps", title: "Workflow mensuel", steps: [{ title: "Echantillonner", body: "Relancer les memes requetes et enregistrer couverture, mentions, citations, concurrents." }, { title: "Classer", body: "Marquer exact, partiel, absent ou trompeur." }, { title: "Mapper", body: "Relier les ecarts aux pages, entites, services et sources." }, { title: "Agir", body: "Ameliorer les sources et verifier apres un delai raisonnable." }] },
        { type: "faq", items: [{ question: "La visibilite IA se mesure-t-elle parfaitement?", answer: "Non. Elle se mesure de facon directionnelle avec methode repetable et limites documentees." }, { question: "Une citation vaut-elle plus qu'une mention?", answer: "Souvent elle est plus actionnable car elle pointe vers une URL, mais une mention de qualite peut aussi compter." }] },
        { type: "cta", title: "Revoir votre methode IA.", body: "Taskcover peut cartographier votre couverture actuelle et les ecarts de contenu, entites et sources.", primary: { label: "Explorer recherche IA", href: "/services/ai-search-optimization" }, secondary: ctaCall },
      ],
      faqItems: [{ question: "La visibilite IA se mesure-t-elle parfaitement?", answer: "Non. Elle se mesure de facon directionnelle avec methode repetable et limites documentees." }, { question: "Une citation vaut-elle plus qu'une mention?", answer: "Souvent elle est plus actionnable car elle pointe vers une URL, mais une mention de qualite peut aussi compter." }],
    }),
    buildInsightArticle({
      id: "insight-fr-technical-audit",
      slug: "technical-seo-audit-checklist-growing-websites",
      translationGroupId: "technical-audit",
      locale: "fr",
      title: "Checklist d'audit SEO technique pour sites en croissance",
      excerpt: "Checklist priorisee pour crawl, indexation, architecture, canonicals, rendu, Core Web Vitals, schema, international et migrations.",
      category: "technical-seo",
      tags: ["SEO technique", "Audit SEO", "Core Web Vitals", "Indexation"],
      readingTime: 14,
      coverImageAlt: "Tableau d'audit technique avec crawl, index, architecture, performance et schema.",
      coverImageCaption: "Un bon audit transforme les problemes en roadmap priorisee.",
      focusKeyword: "checklist audit SEO technique",
      secondaryKeywords: ["audit SEO", "audit crawl", "audit indexation"],
      intent: "Auditer techniquement un site en croissance.",
      audience: "Responsables SEO, produit, developpeurs et proprietaires de sites",
      funnelStage: "consideration",
      coreQuestion: "Que verifier dans un audit SEO technique d'un site en croissance?",
      primaryEntity: "Audit SEO technique",
      supportingEntities: ["crawl", "indexation", "canonicalisation", "Core Web Vitals", "schema", "hreflang"],
      topicCluster: "SEO technique",
      parentPillar: "SEO technique",
      uniqueInformationGain: "Un modele qui separe bloqueurs, reduction de risque et leviers de croissance.",
      refreshTrigger: "Actualiser quand les recommandations performance, schema ou international evoluent.",
      sources: getSharedSources(["google-seo-starter", "google-canonical", "google-structured-data", "google-hreflang", "web-vitals"]),
      claims: [{ id: "google-crawl-index", text: "Google decouvre, explore et indexe les pages avec des systemes automatises et des liens.", requiresEvidence: true, sourceIds: ["google-seo-starter"] }, { id: "core-web-vitals", text: "Les Core Web Vitals couvrent chargement, interaction et stabilite visuelle.", requiresEvidence: true, sourceIds: ["web-vitals"] }],
      originalInsights: ["Prioriser par impact sur l'indexation et le chemin revenu, pas par nombre d'alertes."],
      serviceLinks: [{ label: "SEO technique", href: "/services/technical-seo" }, { label: "Audit SEO", href: "/services/seo-audit" }],
      industryLinks: [{ label: "SEO e-commerce", href: "/industries/ecommerce-seo" }, { label: "SEO SaaS", href: "/industries/saas-seo" }],
      sampleAuditLinks: [{ label: "Audit SEO technique exemple", href: "/work/sample-audits/technical-seo-audit" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "international-seo-usa-canada-australia", "content-rankings-citations-leads"],
      metaTitle: "Checklist d'audit SEO technique",
      metaDescription: "Checklist SEO technique pour crawl, indexation, architecture, canonicals, rendu, Core Web Vitals, schema et migrations.",
      breadcrumbLabel: "Checklist audit SEO technique",
      blocks: [
        { type: "direct-answer", title: "Reponse directe", answer: "Un audit SEO technique doit verifier que les bonnes pages peuvent etre explorees, rendues, indexees, canonicalisees, structurees, localisees et mesurees, puis prioriser les corrections par risque et valeur business." },
        { type: "key-takeaways", title: "Points cles", items: ["Traiter les bloqueurs d'indexation avant les details de template.", "Canonicals et redirections coutent plus cher a corriger quand le site grandit.", "La performance compte surtout quand elle touche experience et conversion.", "Chaque audit doit finir avec responsable, priorite et validation."] },
        { type: "checklist", title: "Crawl et indexation", items: [{ label: "Directives", detail: "Verifier robots.txt, noindex, canonicals et ressources bloquees." }, { label: "Sitemap", detail: "Comparer URLs sitemap et URLs canoniques indexables." }, { label: "Liens internes", detail: "S'assurer que les pages prioritaires sont atteignables." }, { label: "Codes statut", detail: "Cartographier 3xx, 4xx, 5xx par template et importance." }] },
        { type: "heading", level: 2, text: "Architecture, canonicalisation et redirections", id: "architecture" },
        { type: "paragraph", text: "Les sites en croissance accumulent des doublons via filtres, parametres, archives CMS et variantes locales. L'audit decide quelles URLs doivent exister, consolider ou rediriger." },
        { type: "comparison-table", caption: "Modele de priorite.", columns: ["Probleme", "Risque", "Action"], rows: [["Pages prioritaires bloquees", "Eleve", "Retirer le blocage et valider."], ["Canonicals contradictoires", "Eleve", "Choisir les URLs representatives."], ["Chaines de redirection", "Moyen", "Les raccourcir sur chemins importants."], ["Liens internes faibles", "Moyen", "Ajouter des liens contextuels."]] },
        { type: "heading", level: 2, text: "Rendu, performance et schema", id: "rendu-performance" },
        { type: "paragraph", text: "Le rendu doit confirmer que utilisateurs et robots voient le contenu, les liens et les CTA utiles. Le schema doit correspondre au contenu visible." },
        { type: "checklist", title: "Rendu et performance", items: [{ label: "Contenu critique", detail: "Valider copie, liens et details service dans le HTML rendu." }, { label: "Core Web Vitals", detail: "Prioriser les templates avec trafic ou leads." }, { label: "Schema", detail: "Eviter notes, avis ou recompenses non justifies." }, { label: "Images", detail: "Prevoir dimensions et alt text significatif." }] },
        { type: "steps", title: "Roadmap post-audit", steps: [{ title: "Stabiliser", body: "Corriger les bloqueurs de crawl, index, rendu ou tracking." }, { title: "Consolider", body: "Resoudre doublons, canonicals, redirections et architecture fine." }, { title: "Ameliorer", body: "Renforcer schema, maillage, performance et templates." }, { title: "Valider", body: "Recrawler, inspecter, monitorer et documenter." }] },
        { type: "cta", title: "Besoin d'une roadmap technique?", body: "Taskcover transforme donnees crawl, templates et priorites business en roadmap SEO exploitable.", primary: { label: "Explorer SEO technique", href: "/services/technical-seo" }, secondary: { label: "Voir l'audit exemple", href: "/work/sample-audits/technical-seo-audit" } },
      ],
    }),
    buildInsightArticle({
      id: "insight-fr-seo-ppc",
      slug: "seo-vs-ppc-search-growth-system",
      translationGroupId: "seo-ppc",
      locale: "fr",
      title: "SEO vs PPC : construire un seul systeme de croissance search",
      excerpt: "Utiliser SEO et PPC ensemble grace a l'intention, aux landing pages, aux requetes, au tracking, aux tests, aux budgets et au reporting.",
      category: "ppc-search-intelligence",
      tags: ["SEO vs PPC", "PPC", "Intelligence search", "Pages d'atterrissage"],
      readingTime: 11,
      coverImageAlt: "Dashboard paid et organique avec requetes, landing pages et conversions.",
      coverImageCaption: "SEO et PPC fonctionnent mieux quand ils partagent intelligence de requete et apprentissage conversion.",
      focusKeyword: "SEO vs PPC",
      secondaryKeywords: ["strategie SEO PPC", "paid organic search", "croissance search"],
      intent: "Comparer SEO et PPC puis les combiner intelligemment.",
      audience: "Directions marketing, paid media, SEO et fondateurs",
      funnelStage: "consideration",
      coreQuestion: "Quand utiliser SEO, PPC ou les deux?",
      primaryEntity: "Search marketing",
      supportingEntities: ["SEO", "PPC", "landing pages", "requetes", "tracking conversion"],
      topicCluster: "PPC & Intelligence search",
      parentPillar: "Croissance search",
      uniqueInformationGain: "Un modele de decision qui evite de dire que SEO et PPC conviennent toujours autant.",
      refreshTrigger: "Actualiser quand tracking paid, consentement ou services Taskcover changent.",
      sources: getSharedSources(["google-seo-starter", "google-helpful-content"]),
      claims: [{ id: "people-first-content", text: "Le contenu utile et l'experience restent centraux pour l'organique durable.", requiresEvidence: true, sourceIds: ["google-helpful-content"] }],
      originalInsights: ["Le PPC achete de la vitesse; le SEO compose la pertinence. Le systeme commun est l'intention search."],
      serviceLinks: [{ label: "Gestion PPC", href: "/services/ppc-management" }, { label: "Agence SEO", href: "/services/seo-agency" }, { label: "SEO local", href: "/services/local-seo" }],
      sampleAuditLinks: [{ label: "Revue PPC + organique", href: "/work/sample-audits/ppc-organic-intelligence" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "content-rankings-citations-leads", "measure-ai-search-visibility"],
      metaTitle: "SEO vs PPC : un systeme de croissance search",
      metaDescription: "Comparer SEO et PPC puis combiner paid et organique via intention, landing pages, tracking, requetes, tests et reporting.",
      breadcrumbLabel: "SEO vs PPC",
      blocks: [
        { type: "direct-answer", title: "Reponse directe", answer: "SEO et PPC ne sont pas des adversaires. Utilisez le PPC pour la vitesse, les tests et la capture de demande; utilisez le SEO pour la decouverte durable et l'autorite quand le marche et le site le permettent." },
        { type: "key-takeaways", title: "Points cles", items: ["Le PPC sert la vitesse et le controle.", "Le SEO sert la couverture durable et l'autorite.", "Les deux doivent partager requetes, landing pages et conversion.", "Certains marches exigent un canal avant l'autre."] },
        { type: "comparison-table", caption: "Modele SEO/PPC.", columns: ["Question", "Signal SEO", "Signal PPC"], rows: [["Vitesse requise?", "Moyen/long terme", "Capture immediate"], ["Intention stable?", "Demande recurrente", "Saisonnier ou test"], ["Page d'atterrissage?", "Profondeur et liens", "Clarte conversion"], ["Apprentissage?", "Search Console et leads", "Termes de recherche et CPA"]] },
        { type: "paragraph", text: "La meme personne peut cliquer une annonce, comparer des resultats organiques puis convertir apres une recherche de marque. La carte d'intention est donc plus utile que le debat canal contre canal." },
        { type: "decision-framework", title: "Cadre de choix", criteria: [{ signal: "Intention forte, autorite faible, besoin urgent", action: "Utiliser PPC pendant l'amelioration SEO." }, { signal: "Demande informative stable", action: "Investir en contenu SEO et maillage." }, { signal: "Offre ou message non prouve", action: "Tester avec PPC avant un cluster SEO." }, { signal: "CPC eleve et leads faibles", action: "Revoir page, exclusions et alternatives organiques." }] },
        { type: "checklist", title: "Reporting integre", items: [{ label: "Themes de requetes", detail: "Regrouper termes payants et requetes organiques." }, { label: "Pages d'atterrissage", detail: "Suivre conversion, profondeur, vitesse et message." }, { label: "Budget", detail: "Comparer cout par lead qualifie et opportunite organique." }, { label: "Journal de decision", detail: "Documenter ce qui passe du test paid a l'investissement SEO." }] },
        { type: "cta", title: "Relier SEO et PPC.", body: "Taskcover transforme donnees de requetes, pages et economie canal en systeme de croissance search.", primary: { label: "Explorer Gestion PPC", href: "/services/ppc-management" }, secondary: { label: "Explorer Agence SEO", href: "/services/seo-agency" } },
      ],
    }),
    buildInsightArticle({
      id: "insight-fr-international",
      slug: "international-seo-usa-canada-australia",
      translationGroupId: "international-seo",
      locale: "fr",
      title: "SEO international pour les USA, le Canada et l'Australie",
      excerpt: "Planifier le SEO international avec intention de marche, localisation, hreflang, canonicals, architecture, autorite locale et sequence.",
      category: "local-international-seo",
      tags: ["SEO international", "USA", "Canada", "Australie", "Hreflang"],
      readingTime: 13,
      coverImageAlt: "Carte d'architecture de marche pour USA, Canada et Australie.",
      coverImageCaption: "Le SEO international est une strategie de marche avant une traduction.",
      focusKeyword: "SEO international USA Canada Australie",
      secondaryKeywords: ["agence SEO USA", "agence SEO Canada", "agence SEO Australie", "hreflang SEO"],
      intent: "Planifier le SEO sur trois marches anglophones avec localisation.",
      audience: "Directions marketing en expansion internationale",
      funnelStage: "consideration",
      coreQuestion: "Comment planifier le SEO aux USA, au Canada et en Australie?",
      primaryEntity: "SEO international",
      supportingEntities: ["hreflang", "canonicalisation", "localisation", "architecture de marche", "intention regionale"],
      topicCluster: "SEO local & international",
      parentPillar: "SEO international",
      uniqueInformationGain: "Un cadre de sequence pour regions anglophones avec considerations francaises et espagnoles.",
      refreshTrigger: "Actualiser quand pages marche, hreflang ou priorites localisation changent.",
      sources: getSharedSources(["google-hreflang", "google-canonical", "google-seo-starter"]),
      claims: [{ id: "hreflang-alternates", text: "Google documente hreflang pour signaler les versions localisees d'une page.", requiresEvidence: true, sourceIds: ["google-hreflang"] }],
      originalInsights: ["La localisation suit la demande et le contexte de conversion, pas seulement la langue disponible."],
      serviceLinks: [{ label: "SEO international", href: "/services/international-seo" }, { label: "SEO local", href: "/services/local-seo" }],
      industryLinks: [{ label: "SEO Voyage", href: "/industries/travel-seo" }, { label: "SEO Education", href: "/industries/education-seo" }],
      marketLinks: [{ label: "Agence SEO USA", href: "/markets/usa-seo-agency" }, { label: "Agence SEO Canada", href: "/markets/canada-seo-agency" }, { label: "Agence SEO Australie", href: "/markets/australia-seo-agency" }],
      sampleAuditLinks: [{ label: "Carte marche SEO international", href: "/work/sample-audits/international-seo-market-map" }],
      relatedArticleSlugs: ["technical-seo-audit-checklist-growing-websites", "seo-2026-google-ai-search-revenue-growth", "content-rankings-citations-leads"],
      metaTitle: "SEO international USA, Canada et Australie",
      metaDescription: "Planifier le SEO international pour USA, Canada et Australie avec localisation, hreflang, canonicals, architecture et sequence.",
      breadcrumbLabel: "SEO international USA Canada Australie",
      blocks: [
        { type: "direct-answer", title: "Reponse directe", answer: "Le SEO international pour USA, Canada et Australie commence par l'intention de marche et l'architecture, puis aligne localisation, hreflang, canonicals, autorite locale, adaptation de contenu et sequence." },
        { type: "key-takeaways", title: "Points cles", items: ["Ne supposez pas qu'une meme page anglaise convient partout.", "Le Canada peut exiger anglais et francais selon l'audience.", "L'espagnol peut soutenir des audiences hispaniques aux USA si le service le justifie.", "Hreflang aide quand les equivalents localises existent vraiment."] },
        { type: "paragraph", text: "USA, Canada et Australie partagent une partie de la demande anglophone, mais pas les memes attentes, concurrents, termes, preuves locales ou contextes commerciaux." },
        { type: "comparison-table", caption: "Considerations par marche.", columns: ["Marche", "Consideration SEO", "Implication contenu"], rows: [["USA", "Requetes concurrentielles et variations locales", "Segmenter par service, secteur et intention locale."], ["Canada", "Besoins anglais/francais possibles", "Prevoir contenu bilingue quand operations et demande le justifient."], ["Australie", "Terminologie et concurrents locaux", "Adapter exemples, langage et signaux de confiance."]] },
        { type: "paragraph", text: "Choisissez une structure URL maintenable. Hreflang doit decrire des pages equivalentes; il ne doit pas masquer des doublons sans valeur de marche." },
        { type: "checklist", title: "Verification internationale", items: [{ label: "Carte marche", detail: "Definir services, secteurs et regions qui meritent des pages." }, { label: "Profondeur localisation", detail: "Adapter termes, preuves, offres et CTA." }, { label: "Hreflang", detail: "Inclure auto-references et equivalents reels." }, { label: "Autorite", detail: "Construire pertinence locale avec ressources, citations et liens internes." }] },
        { type: "steps", title: "Sequence recommandee", steps: [{ title: "Choisir un cluster", body: "Demarrer avec le marche au meilleur fit service/demande." }, { title: "Localiser les pages prioritaires", body: "Adapter services, marches et guides high-intent." }, { title: "Valider les signaux", body: "Verifier canonicals, hreflang, maillage, sitemaps et indexation." }, { title: "Etendre avec preuve", body: "Utiliser donnees search, qualite lead et retours sales." }] },
        { type: "cta", title: "Planifier l'architecture marche.", body: "Cartographiez USA, Canada et Australie avant de produire des pages localisees.", primary: { label: "Explorer SEO international", href: "/services/international-seo" }, secondary: ctaCall },
      ],
    }),
    buildInsightArticle({
      id: "insight-fr-content-authority",
      slug: "content-rankings-citations-leads",
      translationGroupId: "content-authority",
      locale: "fr",
      title: "Creer du contenu qui gagne classements, citations et leads",
      excerpt: "Cadre d'autorite contenu pour intention, information gain, expertise, entites, actifs citables, RP digitales, maillage, conversion et refresh.",
      category: "content-authority",
      tags: ["Marketing de contenu", "Autorite digitale", "Information gain", "Maillage interne"],
      readingTime: 12,
      coverImageAlt: "Carte d'autorite contenu reliant intention, preuves, entites, citations, liens et leads.",
      coverImageCaption: "Un contenu utile doit aider le lecteur et soutenir le systeme search autour de lui.",
      focusKeyword: "contenu classements citations leads",
      secondaryKeywords: ["autorite contenu SEO", "contenu citable", "strategie contenu SEO"],
      intent: "Creer du contenu performant en search et utile au business.",
      audience: "Equipes contenu, SEO, RP digitales et marketing",
      funnelStage: "consideration",
      coreQuestion: "Comment creer du contenu qui peut ranker, etre cite et generer des leads qualifies?",
      primaryEntity: "Autorite de contenu",
      supportingEntities: ["intention search", "information gain", "expertise", "RP digitales", "maillage interne", "conversion"],
      topicCluster: "Contenu & Autorite digitale",
      parentPillar: "Marketing de contenu",
      uniqueInformationGain: "Un systeme reliant utilite, valeur de citation, RP digitales et conversion sans densite de mots-cles.",
      refreshTrigger: "Actualiser quand sources, services ou performance contenu changent.",
      sources: getSharedSources(["google-helpful-content", "google-seo-starter", "google-structured-data"]),
      claims: [{ id: "people-first-content", text: "Google recommande un contenu utile, fiable et pense pour les personnes.", requiresEvidence: true, sourceIds: ["google-helpful-content"] }],
      originalInsights: ["Un actif contenu doit meriter une action suivante : sauvegarde, clic interne, citation, question commerciale ou refresh."],
      serviceLinks: [{ label: "Marketing de contenu", href: "/services/content-marketing" }, { label: "RP digitales et liens", href: "/services/digital-pr-link-building" }, { label: "Optimisation recherche IA", href: "/services/ai-search-optimization" }, { label: "SEO Mentor", href: "/services/seo-mentor-service" }],
      caseStudyLinks: [{ label: "Cas clients", href: "/work/case-studies" }],
      sampleAuditLinks: [{ label: "Carte d'ecarts contenu", href: "/work/sample-audits/content-gap-map" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "measure-ai-search-visibility", "technical-seo-audit-checklist-growing-websites"],
      metaTitle: "Creer du contenu qui gagne classements, citations et leads",
      metaDescription: "Cadre de contenu SEO pour intention, information gain, expertise, entites, citations, RP digitales, liens internes, leads et refresh.",
      breadcrumbLabel: "Contenu, citations et leads",
      blocks: [
        { type: "direct-answer", title: "Reponse directe", answer: "Un contenu gagne classements, citations et leads quand il repond a une intention claire, ajoute une interpretation originale, utilise des preuves credibles, couvre les bonnes entites, s'integre au site et propose une etape naturelle." },
        { type: "key-takeaways", title: "Points cles", items: ["L'intention est le depart, pas toute la strategie.", "L'information gain vient de l'interpretation utile et des preuves.", "Un contenu citable a des definitions, cadres et sources clairs.", "Les chemins lead doivent etre utiles et pertinents."] },
        { type: "paragraph", text: "L'intention dit ce que le lecteur veut accomplir. L'information gain explique pourquoi votre page merite d'exister. Reecrire les memes conseils que les concurrents ne suffit pas." },
        { type: "checklist", title: "Entrants d'information gain", items: [{ label: "Input expert", detail: "Capturer un jugement reel sans inventer citations ou credentials." }, { label: "Cadres de decision", detail: "Aider a choisir quoi faire." }, { label: "Preuves", detail: "Citer sources primaires pour les faits." }, { label: "Exemples operationnels", detail: "Relier le concept aux audits, briefs, roadmaps ou ventes." }] },
        { type: "comparison-table", caption: "Actifs contenu et usage.", columns: ["Actif", "Usage", "Chemin lead"], rows: [["Checklist", "Evaluation operationnelle", "Audit SEO ou mentorat"], ["Cadre", "Decision strategique", "Appel strategie"], ["Tableau comparatif", "Evaluation options", "Page service"], ["Liste de sources", "Confiance et citation", "RP digitales"]] },
        { type: "paragraph", text: "Les liens internes doivent expliquer les relations. Un guide sur les citations peut naturellement relier contenu, RP digitales, recherche IA, cas clients, audits et SEO Mentor." },
        { type: "related-service", title: "SEO Mentor comme chemin d'enablement", href: "/services/seo-mentor-service", summary: "SEO Mentor aide les equipes a renforcer briefs, revues, jugement contenu et priorisation." },
        { type: "steps", title: "Workflow de refresh", steps: [{ title: "Inspecter la demande", body: "Revoir requetes, leads, objections sales et changements concurrents." }, { title: "Verifier les preuves", body: "Actualiser sources, affirmations, exemples et schema." }, { title: "Ameliorer les chemins", body: "Ajouter des liens vers services, audits, cas et marches." }, { title: "Documenter", body: "Noter ce qui change au lieu de changer la date sans substance." }] },
        { type: "faq", items: [{ question: "Faut-il viser une densite de mots-cles?", answer: "Non. Un bon brief couvre intention, entites, preuves et decisions du lecteur." }, { question: "Le contenu peut-il aider les citations IA?", answer: "Il peut ameliorer la comprehension et la reference possible, mais personne ne peut garantir une citation." }] },
        { type: "cta", title: "Construire du contenu avec autorite et revenu.", body: "Taskcover aide a relier contenu utile, autorite digitale, recherche IA et chemins de conversion.", primary: { label: "Explorer Marketing de contenu", href: "/services/content-marketing" }, secondary: { label: "Explorer RP digitales", href: "/services/digital-pr-link-building" } },
      ],
      faqItems: [{ question: "Faut-il viser une densite de mots-cles?", answer: "Non. Un bon brief couvre intention, entites, preuves et decisions du lecteur." }, { question: "Le contenu peut-il aider les citations IA?", answer: "Il peut ameliorer la comprehension et la reference possible, mais personne ne peut garantir une citation." }],
    }),
  ],
};
