import type { LeadsContent } from "@/content/leads.types";

export const leads: LeadsContent = {
  locale: "fr",
  recipientEmail: "business@taskcover.com",
  common: {
    back: "Retour",
    continue: "Continuer",
    submit: "Envoyer la demande",
    submitting: "Envoi...",
    retry: "Reessayer",
    directEmail: "Ecrire a business@taskcover.com",
    requiredNote: "Les champs obligatoires sont indiques.",
    optional: "Facultatif",
    consentText:
      "J'accepte que Taskcover utilise ces informations pour examiner ma demande et me contacter au sujet de services de croissance search pertinents.",
    honeypotLabel: "Laissez ce champ vide",
    unavailableTitle: "L'envoi en ligne est temporairement indisponible.",
    unavailableBody:
      "Vous pouvez envoyer votre demande directement a business@taskcover.com. Les informations saisies restent sur cette page pour reessayer ou ecrire a l'equipe.",
    temporaryError:
      "La demande n'a pas pu etre livree pour le moment. Reessayez ou ecrivez directement a business@taskcover.com.",
    spamError:
      "La demande n'a pas pu etre acceptee. Verifiez le formulaire et reessayez, ou ecrivez directement a business@taskcover.com.",
    validationSummary: "Veuillez verifier les champs signales avant de continuer.",
    mailSubjects: {
      "seo-audit": "Demande d'audit SEO gratuit",
      "strategy-call": "Demande d'appel strategie",
      "general-contact": "Demande de contact Taskcover",
      "media-inquiry": "Demande media pour Taskcover",
      "private-reference": "Demande de reference privee",
      "data-request": "Demande de donnees Taskcover",
      partnership: "Demande de partenariat",
      "seo-mentor": "Demande SEO Mentor",
      "ppc-inquiry": "Demande PPC",
      other: "Demande Taskcover",
    },
    turnstileLabel: "Verification de securite",
  },
  fields: {
    name: { label: "Nom complet", placeholder: "Jane Nguyen" },
    workEmail: { label: "Email professionnel", placeholder: "jane@entreprise.com" },
    company: { label: "Entreprise", placeholder: "Entreprise ou organisation" },
    role: { label: "Role", placeholder: "Responsable marketing, fondateur, operateur" },
    websiteUrl: { label: "URL du site", placeholder: "https://exemple.com" },
    market: { label: "Marche principal" },
    industry: { label: "Secteur" },
    serviceInterests: { label: "Services d'interet" },
    currentTrafficRange: { label: "Trafic organique mensuel actuel" },
    paidSearchActivity: { label: "Le paid search est-il actif ?" },
    primaryChallenge: { label: "Principal defi search", placeholder: "Qu'est-ce qui bloque la visibilite, les leads ou l'execution ?" },
    goals: { label: "Objectif business principal", placeholder: "Que doit aider a accomplir la croissance search ?" },
    timeline: { label: "Calendrier souhaite" },
    investmentRange: { label: "Investissement mensuel estime en croissance search" },
    preferredTimeZone: { label: "Fuseau horaire prefere" },
    preferredCallWindows: { label: "Creneaux d'appel preferes" },
    message: { label: "Message", placeholder: "Partagez le contexte utile, les liens, les contraintes ou les questions." },
    engagementType: { label: "Type d'engagement" },
    publication: { label: "Publication ou plateforme", placeholder: "Publication, podcast, infolettre ou emission" },
    topic: { label: "Sujet", placeholder: "Search, visibilite IA, SEO technique, SEO local..." },
    deadline: { label: "Echeance", placeholder: "Date ou timing si pertinent" },
    requestedFormat: { label: "Format demande" },
  },
  validation: {
    required: "Ce champ est obligatoire.",
    email: "Indiquez un email professionnel valide.",
    url: "Indiquez une URL de site valide.",
    consent: "Le consentement est requis avant l'envoi.",
    selectRequired: "Choisissez au moins une option.",
    length: "Ce champ est trop long.",
    malformed: "Cette valeur n'est pas prise en charge.",
    callWindows: "Choisissez deux ou trois creneaux d'appel preferes.",
  },
  options: {
    markets: [
      { value: "usa", label: "Etats-Unis" },
      { value: "canada", label: "Canada" },
      { value: "australia", label: "Australie" },
      { value: "multiple", label: "Plusieurs marches" },
      { value: "other", label: "Autre" },
    ],
    industries: [
      { value: "travel-hospitality", label: "Voyage et hospitalite" },
      { value: "education", label: "Education" },
      { value: "healthcare-wellness", label: "Sante et bien-etre" },
      { value: "legal-immigration", label: "Droit et immigration" },
      { value: "saas-technology", label: "SaaS et technologie" },
      { value: "ecommerce", label: "eCommerce" },
      { value: "franchise-multilocation", label: "Franchise et multi-sites" },
      { value: "other", label: "Autre" },
    ],
    services: [
      { value: "seo-agency", label: "Strategie SEO" },
      { value: "technical-seo", label: "SEO technique" },
      { value: "ai-search-optimization", label: "Optimisation recherche IA" },
      { value: "content-marketing", label: "Marketing de contenu" },
      { value: "website-development", label: "Developpement de site web" },
      { value: "digital-pr-link-building", label: "RP digitales et autorite" },
      { value: "local-seo", label: "SEO local" },
      { value: "ecommerce-seo", label: "SEO eCommerce" },
      { value: "international-seo", label: "SEO international" },
      { value: "seo-audit", label: "Audit SEO" },
      { value: "ppc-management", label: "Gestion PPC" },
      { value: "seo-mentor-service", label: "Service SEO Mentor" },
    ],
    traffic: [
      { value: "unknown", label: "Pas encore certain" },
      { value: "under-1000", label: "Moins de 1 000 visites/mois" },
      { value: "1000-10000", label: "1 000-10 000 visites/mois" },
      { value: "10000-50000", label: "10 000-50 000 visites/mois" },
      { value: "50000-plus", label: "50 000+ visites/mois" },
    ],
    paidSearch: [
      { value: "yes", label: "Oui" },
      { value: "no", label: "Non" },
      { value: "planned", label: "Prevus" },
      { value: "not-sure", label: "Pas certain" },
    ],
    timelines: [
      { value: "urgent", label: "A traiter maintenant" },
      { value: "30-60-days", label: "30-60 jours" },
      { value: "quarter", label: "Ce trimestre" },
      { value: "6-months", label: "Dans les 6 prochains mois" },
      { value: "exploring", label: "Exploration" },
    ],
    investments: [
      { value: "not-sure", label: "Pas encore certain" },
      { value: "under-2500", label: "Moins de 2 500 USD/mois" },
      { value: "2500-5000", label: "2 500-5 000 USD/mois" },
      { value: "5000-10000", label: "5 000-10 000 USD/mois" },
      { value: "10000-plus", label: "10 000 USD+/mois" },
      { value: "project-based", label: "Engagement par projet" },
    ],
    timeZones: [
      { value: "america-eastern", label: "Heure de l'Est" },
      { value: "america-central", label: "Heure centrale" },
      { value: "america-mountain", label: "Heure des Rocheuses" },
      { value: "america-pacific", label: "Heure du Pacifique" },
      { value: "canada-eastern", label: "Heure de l'Est canadien" },
      { value: "australia-eastern", label: "Heure de l'Est australien" },
      { value: "europe", label: "Europe" },
      { value: "asia", label: "Asie" },
      { value: "other", label: "Autre" },
    ],
    callWindows: [
      { value: "weekday-morning", label: "Matin en semaine" },
      { value: "weekday-midday", label: "Milieu de jour en semaine" },
      { value: "weekday-afternoon", label: "Apres-midi en semaine" },
      { value: "weekday-evening", label: "Soir en semaine" },
      { value: "flexible", label: "Flexible" },
    ],
    contactIntents: [
      { value: "seo-services", label: "Services SEO" },
      { value: "ppc", label: "Gestion PPC" },
      { value: "seo-mentor", label: "Service SEO Mentor" },
      { value: "media", label: "Demande media" },
      { value: "private-reference", label: "Demande de reference privee" },
      { value: "partnership", label: "Partenariat" },
      { value: "general", label: "Question generale" },
      { value: "other", label: "Autre" },
    ],
    engagementTypes: [
      { value: "audit", label: "Audit ou evaluation" },
      { value: "ongoing", label: "Programme de croissance continu" },
      { value: "consulting", label: "Conseil ou mentorat" },
    ],
    requestedFormats: [
      { value: "quote", label: "Citation ecrite" },
      { value: "interview", label: "Interview" },
      { value: "briefing", label: "Briefing technique" },
    ],
  },
  freeAudit: {
    meta: { title: "Demande d'audit SEO gratuit", description: "Demandez un audit SEO Taskcover couvrant sante technique, demande search, autorite de contenu, preparation IA et priorites 90 jours." },
    eyebrow: "Evaluation diagnostique",
    h1: "Demander un audit SEO gratuit",
    intro: "Partagez le contexte necessaire pour diagnostiquer le systeme search de votre site, marche, contenu et priorites de croissance.",
    proof: "La demande d'audit ne promet ni classement ni delai de reponse. Elle aide Taskcover a evaluer l'adaptation et le bon angle de diagnostic.",
    steps: [
      { title: "Contact et site", description: "Qui vous etes et quel site doit etre examine." },
      { title: "Contexte business et search", description: "Marche, secteur, services d'interet et activite search actuelle." },
      { title: "Priorites et calendrier", description: "Ce qui compte le plus, quand agir, et le budget facultatif." },
    ],
    previewTitle: "Axes possibles de l'audit",
    previewIntro: "Le bon examen depend de votre marche et de votre site, mais le diagnostic peut couvrir :",
    previewItems: ["Sante technique", "Demande search", "Autorite de contenu", "Preparation recherche IA", "Opportunite locale ou internationale", "Recouvrement paid et organique", "Priorites 90 jours"],
    privacyTitle: "Utilisation des informations",
    privacyBody: "Les donnees du formulaire servent uniquement a evaluer et traiter votre demande. Aucune donnee personnelle sensible, financiere, medicale ou de compte n'est demandee.",
  },
  bookCall: {
    meta: { title: "Demander un appel strategie", description: "Demandez un appel strategie Taskcover pour SEO, recherche IA, PPC, contenu, local, eCommerce, international ou planification search." },
    eyebrow: "Planificateur de session strategie",
    h1: "Demander un appel strategie",
    intro: "Partagez votre contexte de croissance et vos creneaux preferes. Taskcover confirmera la disponibilite apres acceptation par un adaptateur de livraison configure.",
    agendaTitle: "Ce que la session peut couvrir",
    agenda: ["Contexte business", "Contraintes search", "Opportunites prioritaires", "Adaptation audit, conseil ou execution"],
    prepareTitle: "Contexte utile a preparer",
    prepare: ["Site et marche", "Activite SEO ou PPC actuelle", "Contraintes internes", "Echeances ou dates de decision importantes"],
    boundary: "Cette route collecte une demande d'appel strategie. Elle ne confirme pas de rendez-vous calendrier avant la configuration d'un futur adaptateur calendrier.",
  },
  contact: {
    meta: { title: "Contacter Taskcover Agency | Demandes search", description: "Contactez Taskcover pour services SEO, PPC, SEO Mentor, demandes media, references privees, partenariats ou questions generales." },
    eyebrow: "Bureau de routage des demandes",
    h1: "Envoyer la bonne demande a Taskcover",
    intro: "Choisissez l'intention la plus proche de votre demande pour qu'elle soit evaluee avec le bon contexte.",
    deskTitle: "Carte de routage",
    deskItems: ["Fit SEO et PPC", "Questions de mentorat", "Media et commentaire expert", "Qualification reference privee", "Partenariats et demandes generales"],
    intentHelp: "L'intention selectionnee modifie les champs de contexte ci-dessous.",
  },
  thankYou: {
    meta: { title: "Demande recue", description: "Confirmation de demande Taskcover." },
    fallbackTitle: "Demande recue",
    fallbackMessage: "Le type de demande a ete enregistre de facon sure.",
    nextLabel: "Suite du processus",
    studiesLabel: "Cas clients pertinents",
    samplesLabel: "Audits exemples pertinents",
    viewStudies: "Voir les cas clients",
    viewSamples: "Voir les audits exemples",
    analyticsHook: "Hook analytics pret : thank_you_view",
    states: {
      "seo-audit": { title: "Demande d'audit SEO recue", message: "Votre demande diagnostique a ete acceptee par le chemin de livraison configure.", next: ["Taskcover examine le site et le contexte fournis.", "L'equipe evalue le fit, les axes probables et les prochaines etapes utiles.", "Aucun delai de reponse n'est garanti sur cette page."], studies: ["British University Vietnam", "Matthew Jeffery Law Firm", "SkatePro"], samples: ["Audit SEO technique", "Revue visibilite IA", "Roadmap search 90 jours"], primaryCta: "Demander un appel strategie", secondaryCta: "Explorer les audits exemples" },
      "strategy-call": { title: "Demande d'appel strategie recue", message: "Votre demande d'appel a ete livree. Ce n'est pas un rendez-vous calendrier confirme.", next: ["Taskcover examine le fit et la disponibilite.", "L'equipe utilise vos creneaux pour evaluer les options.", "Un futur adaptateur calendrier pourra automatiser cela plus tard."], studies: ["Agoda", "FWD Insurance", "Casa Madera"], samples: ["Carte des gaps contenu", "Revue PPC + organique"], primaryCta: "Voir les cas clients", secondaryCta: "Explorer les services" },
      "media-inquiry": { title: "Demande media recue", message: "Votre demande media a ete livree pour evaluation editoriale.", next: ["Le sujet, le format et l'echeance sont examines.", "Taskcover evalue si un representant approuve est adapte.", "La disponibilite d'un porte-parole n'est pas promise."], studies: ["Agoda", "British University Vietnam"], samples: ["Revue visibilite IA", "Framework search"], primaryCta: "Explorer la preuve", secondaryCta: "Retour contact" },
      "private-reference": { title: "Demande de reference privee recue", message: "Votre demande de reference privee a ete livree pour qualification.", next: ["Taskcover verifie le fit et la confidentialite.", "Aucun nom, detail ou contact prive n'est expose automatiquement.", "La disponibilite est evaluee au cas par cas."], studies: ["Bibliotheque de cas verifies", "Standard resultats clients"], samples: ["Audit SEO technique", "Roadmap 90 jours"], primaryCta: "Voir le standard de preuve", secondaryCta: "Voir le travail" },
      "data-request": { title: "Demande de donnees recue", message: "Votre demande de confidentialite ou de donnees a ete acceptee par le chemin de livraison configure.", next: ["Taskcover examine la categorie et le contexte fournis.", "Une verification d'identite peut etre necessaire avant action.", "Aucun delai de reponse n'est garanti sur cette page."], studies: ["Politique de confidentialite", "Politique cookies"], samples: ["Preferences de cookies", "Demande de donnees"], primaryCta: "Lire la confidentialite", secondaryCta: "Gerer les preferences cookies" },
      "general-contact": { title: "Demande de contact recue", message: "Votre demande a ete acceptee par le chemin de livraison configure.", next: ["Taskcover examine et route le message par sujet.", "Si utile, l'equipe peut relier la demande a un service, un audit exemple ou un cas.", "Aucun delai de reponse n'est garanti."], studies: ["Bibliotheque de cas verifies", "Bibliotheque d'audits exemples"], samples: ["Carte des gaps contenu", "Audit SEO local"], primaryCta: "Demander un appel strategie", secondaryCta: "Explorer les services" },
      partnership: { title: "Demande de partenariat recue", message: "Votre demande de partenariat a ete livree pour evaluation.", next: ["Taskcover examine l'alignement, l'audience et les limites operationnelles.", "Aucune disponibilite de partenariat n'est impliquee.", "Un contexte supplementaire peut etre demande."], studies: ["Systeme preuve et autorite"], samples: ["Framework search"], primaryCta: "Explorer la preuve", secondaryCta: "Retour contact" },
      "seo-mentor": { title: "Demande SEO Mentor recue", message: "Votre demande de mentorat a ete livree.", next: ["Taskcover examine le contexte d'equipe et les ecarts de competence.", "Le scope mentorat est evalue avant confirmation.", "Aucun delai de reponse n'est garanti."], studies: ["Service SEO Mentor"], samples: ["Roadmap 90 jours"], primaryCta: "Explorer SEO Mentor", secondaryCta: "Voir les audits exemples" },
      "ppc-inquiry": { title: "Demande PPC recue", message: "Votre demande PPC a ete livree.", next: ["Taskcover examine le contexte paid search et le recouvrement organique.", "L'equipe evalue si la gestion PPC ou l'intelligence search est adaptee.", "Aucun delai de reponse n'est garanti."], studies: ["Casa Madera", "FWD Insurance"], samples: ["Revue PPC + organique"], primaryCta: "Explorer la gestion PPC", secondaryCta: "Voir le travail" },
      other: { title: "Demande recue", message: "Votre demande a ete acceptee par le chemin de livraison configure.", next: ["Taskcover examine et route le message.", "Un contexte supplementaire peut etre demande.", "Aucun delai de reponse n'est garanti."], studies: ["Bibliotheque Work"], samples: ["Bibliotheque d'audits exemples"], primaryCta: "Explorer Work", secondaryCta: "Retour accueil" },
      contact: { title: "Demande de contact recue", message: "Votre demande a ete acceptee par le chemin de livraison configure.", next: ["Taskcover examine le type de demande et le message.", "L'equipe evalue la prochaine voie la plus pertinente.", "Aucun delai de reponse n'est garanti."], studies: ["Bibliotheque de cas verifies"], samples: ["Bibliotheque d'audits exemples"], primaryCta: "Demander un appel strategie", secondaryCta: "Explorer Work" },
    },
  },
};
