import type { PricingContent } from "../pricing.types";

export const pricing = {
  metadata: {
    title: "Tarifs | Plans SEO et developpement de site web | Taskcover Agency",
    description:
      "Explorez les tarifs de Taskcover Agency pour le SEO local, national, global, le developpement de site web, SEO Mentor, les audits, la gestion PPC et les programmes de croissance search sur mesure.",
  },
  breadcrumbs: {
    home: "Accueil",
    pricing: "Tarifs",
  },
  hero: {
    eyebrow: "Tarifs de croissance search",
    h1: "Tarifs pour la croissance search locale, nationale et globale",
    subheadline:
      "Commencez par une base SEO locale ciblee ou passez a une croissance nationale et globale avec SEO, AI Search, PPC, autorite de contenu et execution technique.",
    primaryCta: { label: "Audit SEO gratuit", href: "/free-seo-audit" },
    secondaryCta: { label: "Reserver un appel", href: "/book-a-call" },
    signalChips: ["Local", "National", "Global", "Sites web", "Mentor"],
    commandPanel: {
      title: "Panneau de cadrage",
      rows: [
        { label: "Point d'entree", value: "Audit SEO gratuit" },
        { label: "Execution recommandee", value: "National SEO Growth System" },
        { label: "Projet site web", value: "Growth Website" },
        { label: "Conseil recommande", value: "SEO Mentor Growth Advisory" },
        { label: "Marches complexes", value: "Cadrage sur mesure requis" },
      ],
      note: "Chaque engagement part du plus petit scope capable de soutenir l'objectif de facon realiste.",
    },
  },
  recurringNote:
    "Tous les tarifs sont indiques en USD. Le prix final depend du marche, de la complexite du site, de la concurrence, des besoins de contenu et de la vitesse d'execution. Contactez-nous ou demandez un audit gratuit pour obtenir le cadrage le plus precis.",
  scopeNote:
    "Les plans d'entree sont volontairement concentres. Si vos objectifs exigent production de contenu, implementation technique, SEO multi-marche ou execution continue, Taskcover recommandera un scope plus large.",
  factors: {
    eyebrow: "Pourquoi le prix varie",
    title: "Le prix exact depend du systeme search a construire.",
    description:
      "Une zone de service locale ne se price pas comme une categorie nationale ou un programme multi-pays. Ces facteurs definissent le scope.",
    items: [
      {
        label: "Portee du marche",
        description:
          "La concurrence locale, nationale ou globale change le niveau de strategie, contenu et support technique requis.",
      },
      {
        label: "Complexite du site",
        description:
          "Les grands sites, frameworks JavaScript, migrations ou CMS difficiles demandent un travail technique plus profond.",
      },
      {
        label: "Besoins de contenu",
        description:
          "Une feuille de route est plus legere que des briefs continus, QA editoriale, refreshs et autorite.",
      },
      {
        label: "Surfaces de recherche",
        description:
          "Google organique, local packs, reponses IA, PPC et resultats internationaux ajoutent des chantiers differents.",
      },
      {
        label: "Vitesse d'execution",
        description:
          "Les delais courts demandent un rythme de revue plus serre, plus d'implication senior et moins de dependances ouvertes.",
      },
      {
        label: "Support de l'equipe interne",
        description:
          "Le prix change selon que votre equipe execute ou que Taskcover porte strategie, QA et support d'implementation.",
      },
    ],
  },
  tabs: {
    eyebrow: "Menu tarifaire",
    title: "Choisir la voie search adaptee au probleme.",
    description:
      "Utilisez les onglets pour comparer prix de depart, limites de scope et prochaine etape. Les prix sont des points de depart, pas des devis fixes.",
    compareLink: "Comparer tous les plans",
    ariaLabel: "Categories de tarifs",
    items: [
      {
        id: "local",
        label: "SEO local",
        eyebrow: "Base locale ciblee",
        title: "Tarifs SEO local",
        intro:
          "Pour les entreprises qui doivent ameliorer leur visibilite dans une ville, une zone de service ou un petit groupe de marches locaux.",
        plans: [
          {
            id: "local-starter",
            name: "Local SEO Starter",
            price: "A partir de $1,000/mois",
            positioning:
              "Pour les entreprises locales qui ont besoin d'une base de recherche locale propre.",
            bestFor: [
              "Une localisation principale ou une zone de service",
              "Entreprise de service locale",
              "Restaurant, clinique, service professionnel ou hotellerie locale",
              "Petit site avec complexite technique limitee",
            ],
            includes: [
              "Revue Google Business Profile et recommandations d'optimisation",
              "Carte des mots-cles et intentions locales",
              "Revue d'une page de localisation ou zone de service prioritaire",
              "Revue basique de coherence citation/NAP",
              "Recommandations sur les signaux d'avis",
              "Snapshot concurrentiel local",
              "Checklist mensuelle de visibilite locale",
              "Reporting simple",
            ],
            scopeGuard:
              "Concu pour une localisation ou une zone de service ciblee. Multi-sites, production de contenu, remediation technique, PPC et digital PR demandent un scope plus large.",
            minimum: "Minimum 3 mois",
            addOn: "Localisations supplementaires a partir de $300-$500/localisation/mois",
            cta: { label: "Demarrer par un audit local", href: "/free-seo-audit" },
          },
          {
            id: "local-growth",
            name: "Local Growth / Multi-location",
            price: "A partir de $2,500/mois",
            positioning:
              "Un scope sur mesure compact pour les entreprises avec plusieurs sites, plus de contenu ou une complexite locale.",
            bestFor: [
              "Deux localisations prioritaires ou plus",
              "Visibilite franchise ou agences",
              "Architecture de pages locales",
              "Besoins de preuve locale et reporting",
            ],
            includes: [
              "Carte d'intention multi-sites",
              "Revue de structure des pages locales",
              "Guidance Google Business Profile par localisation prioritaire",
              "Revue concurrentielle locale et gaps de contenu",
              "Roadmap mensuelle de visibilite search",
            ],
            scopeGuard:
              "Utilise quand le starter est trop limite mais que l'entreprise n'a pas encore besoin d'un systeme national.",
            cta: { label: "Demander un scope local", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "national",
        label: "SEO national",
        eyebrow: "Croissance sur un pays",
        title: "Tarifs SEO national",
        intro:
          "Pour les entreprises qui concurrencent sur un pays pour des categories, services, SaaS, eCommerce, education, legal, sante ou services professionnels.",
        plans: [
          {
            id: "national-foundation",
            name: "National SEO Foundation",
            price: "A partir de $2,500/mois",
            positioning:
              "Pour obtenir clarte technique, cartographie de demande search et roadmap serieuse avant d'augmenter l'execution.",
            bestFor: [
              "Un marche pays",
              "Mots-cles nationaux de categorie ou service",
              "SaaS, eCommerce, education, legal, sante ou services professionnels",
              "Entreprise ayant besoin de roadmap technique et contenu",
            ],
            includes: [
              "Carte nationale des mots-cles et intentions",
              "Revue SEO technique",
              "Recommandations d'architecture de site",
              "Revue SERP concurrentielle",
              "Planification gaps de contenu et clusters",
              "Strategie de maillage interne",
              "Snapshot de preparation AI Search",
              "Roadmap et reporting mensuels",
            ],
            cta: { label: "Construire la base", href: "/book-a-call" },
          },
          {
            id: "national-growth",
            name: "National SEO Growth System",
            price: "A partir de $4,500/mois",
            recommended: true,
            positioning:
              "Le plan d'execution recommande pour les entreprises en croissance qui doivent connecter technique, autorite de contenu, AI Search et reporting.",
            bestFor: [
              "Entreprise serieuse en phase de croissance",
              "SEO technique plus autorite de contenu plus AI Search plus reporting",
              "Mots-cles commerciaux non locaux",
              "Demande qualifiee, pas seulement trafic",
            ],
            includes: [
              "Roadmap SEO technique",
              "Planification d'autorite de contenu",
              "Optimisation AI Search",
              "Ameliorations de maillage interne",
              "Reporting d'intelligence search",
              "Recommandations de parcours conversion",
              "Revue strategique mensuelle",
              "Recommandations de confiance basees sur preuves/cas clients",
            ],
            cta: { label: "Discuter du systeme growth", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "global",
        label: "SEO global",
        eyebrow: "Expansion multi-marche",
        title: "Tarifs SEO global",
        intro:
          "Pour les marques qui vendent dans plusieurs pays, langues ou systemes de recherche regionaux ou l'architecture et la localisation comptent.",
        plans: [
          {
            id: "global-expansion",
            name: "Global SEO Expansion",
            price: "A partir de $7,500/mois",
            positioning:
              "Pour les marques en expansion sur plusieurs pays, langues ou parcours search locaux.",
            bestFor: [
              "USA plus Canada plus Australie",
              "Recherche multi-pays",
              "SEO multilingue",
              "Marches anglais, francais et espagnol",
              "SaaS, education, voyage, eCommerce, franchise ou marques internationales",
            ],
            includes: [
              "Architecture SEO multi-marche",
              "Cartographie d'intention pays/langue",
              "SEO technique international",
              "Revue hreflang/localisation si pertinente",
              "Strategie de mots-cles regionale",
              "Strategie de localisation du contenu",
              "Revue de coherence entite et AI Search",
              "Reporting par marche",
            ],
            cta: { label: "Planifier le scope global", href: "/book-a-call" },
          },
          {
            id: "enterprise-authority",
            name: "Enterprise / Multi-Market Authority",
            price: "Sur mesure a partir de $12,000/mois",
            positioning:
              "Tarif sur mesure pour programmes enterprise, migration, autorite, secteurs regules ou multi-parties prenantes.",
            bestFor: [
              "Site enterprise",
              "Grande architecture technique",
              "Migrations",
              "Nombreuses parties prenantes",
              "Campagnes digital PR / autorite",
              "Plusieurs marches/langues",
              "Secteurs regules ou sensibles a la confiance",
            ],
            includes: [
              "Architecture de croissance search enterprise",
              "Planification migration et stakeholders",
              "Gouvernance technique, contenu, AI Search et autorite",
              "Modele de reporting marche par marche",
              "Conseil senior et planification d'execution",
            ],
            scopeGuard:
              "Les programmes enterprise et multi-marche complexes exigent toujours un prix sur mesure.",
            cta: { label: "Demander un scope sur mesure", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "websites",
        label: "Developpement de site web",
        eyebrow: "Sites prets pour la recherche",
        title: "Tarifs developpement de site web",
        intro:
          "Pour les entreprises qui ont besoin d'un site rapide, structure, pret a convertir, avec architecture SEO, bases de visibilite IA, analytics et capture de leads integres des le premier jour.",
        subcopy:
          "Les prix sont des points de depart. Le scope final depend du nombre de pages, de la profondeur du contenu, des integrations, de la complexite de migration, des exigences multilingues et du calendrier.",
        plans: [
          {
            id: "website-launch",
            name: "Website Launch",
            price: "A partir de $3,500 one-time",
            positioning:
              "Un site professionnel pret pour la recherche pour les nouvelles entreprises qui ont besoin d'une base solide avant d'etendre contenu ou campagnes.",
            bestFor: [
              "Nouvelles entreprises ayant besoin d'un site professionnel pret pour la recherche",
              "Sites de services concentres",
              "Fondateurs qui remplacent un site de depart trop leger",
            ],
            includes: [
              "4-6 pages cles",
              "Strategie site web et sitemap",
              "UX/UI responsive",
              "Structure de pages prete pour la recherche",
              "Setup SEO on-page de base",
              "Metadonnees principales",
              "Schema de base",
              "Formulaire contact / lead",
              "Analytics et consent readiness",
              "QA lancement",
            ],
            scopeGuard:
              "Ideal pour les lancements concentres. Plus de pages, integrations sur mesure, multilingue et migration demandent un scope plus large.",
            cta: { label: "Demarrer un projet site web", href: "/contact" },
          },
          {
            id: "growth-website",
            name: "Growth Website",
            price: "A partir de $6,500 one-time",
            recommended: true,
            positioning:
              "Le build recommande pour les entreprises qui veulent SEO, visibilite IA et generation de leads des le premier jour.",
            bestFor: [
              "Entreprises qui veulent SEO, visibilite IA et generation de leads des le premier jour",
              "Marques B2B ou services avec plusieurs offres",
              "Equipes qui preparent une croissance SEO continue",
            ],
            includes: [
              "8-12 pages strategiques",
              "Mapping mots-cles/pages",
              "Architecture pages services",
              "Design UX/UI",
              "Developpement responsive",
              "Fondation SEO/GEO",
              "Schema et structure de maillage interne",
              "Flux capture de leads",
              "Preparation Cal.com",
              "Preparation Resend",
              "Evenements analytics prets",
              "Optimisation performance",
              "QA lancement",
            ],
            cta: { label: "Demarrer un projet site web", href: "/contact" },
          },
          {
            id: "seo-rebuild-migration",
            name: "SEO Rebuild + Migration",
            price: "A partir de $9,500 one-time",
            positioning:
              "Un chemin de refonte pour les sites existants qui doivent ameliorer UX et performance sans perdre de valeur search.",
            bestFor: [
              "Sites existants qui ont besoin d'une refonte sans perdre leur valeur search",
              "Sites avec dette technique ou architecture faible",
              "Equipes qui prevoient changement d'URL, CMS ou framework",
            ],
            includes: [
              "Audit technique du site",
              "Inventaire des URLs",
              "Mapping de redirections",
              "Nettoyage structure contenu",
              "Plan de migration SEO",
              "Rebuild / redesign",
              "Optimisation performance",
              "Nettoyage schema",
              "Controle indexation",
              "Continuite analytics",
              "QA pre-lancement et post-lancement",
            ],
            scopeGuard:
              "Le risque de migration se scope apres inventaire. Gros sites, changements CMS et redirections multilingues peuvent necessiter un tarif sur mesure.",
            cta: { label: "Planifier une refonte sure", href: "/book-a-call" },
          },
          {
            id: "custom-growth-platform",
            name: "Custom Growth Platform",
            price: "Sur mesure, a partir de $15,000+",
            positioning:
              "Systemes web sur mesure pour projets multilingues, CMS, CRM, multi-sites ou riches en integrations.",
            bestFor: [
              "Builds complexes, multilingues, CMS, CRM ou multi-localisations",
              "Hubs de contenu et systemes Insights",
              "Entreprises avec workflows ou routage de leads avances",
            ],
            includes: [
              "Site multilingue",
              "Content hub / systeme Insights",
              "Workflow CMS/admin",
              "Preparation integration CRM / HubSpot",
              "Routage de leads avance",
              "Dashboards sur mesure",
              "Architecture multi-localisations",
              "Integration booking/paiement",
              "Migration complexe",
              "Setup Cloudflare/hebergement sur mesure",
            ],
            cta: { label: "Demander un scope sur mesure", href: "/book-a-call" },
          },
        ],
        notes: [
          "Website Care commence a $199/mois.",
          "Growth Support commence a $750/mois.",
          "Consultez le service Developpement de site web pour les livrables, la QA lancement et le systeme de croissance.",
        ],
        cta: { label: "Voir le service Developpement de site web", href: "/services/website-development" },
      },
      {
        id: "mentor",
        label: "SEO Mentor",
        eyebrow: "Conseil senior",
        title: "Tarifs SEO Mentor",
        intro:
          "SEO Mentor s'adresse aux equipes qui veulent un jugement SEO senior sans confier toutes les taches a une agence.",
        subcopy:
          "Utilisez-le pour challenger la strategie, revoir les decisions techniques et contenu, former les equipes internes et installer un rythme de croissance search.",
        plans: [
          {
            id: "mentor-office-hours",
            name: "SEO Mentor Office Hours",
            price: "A partir de $1,000/mois",
            positioning:
              "Feedback senior cible pour fondateurs, marketers et petites equipes qui executent en interne.",
            bestFor: [
              "Fondateur ou marketer qui gere le SEO en interne",
              "Petite equipe ayant besoin de feedback senior",
              "Revue de decisions SEO prioritaires",
            ],
            includes: [
              "1 session strategie mensuelle",
              "Questions SEO asynchrones",
              "Revue des decisions SEO prioritaires",
              "Revue de 1-2 pages ou briefs cles/mois",
              "Guidance legere technique/contenu/AI Search",
              "Liste d'actions mensuelle",
            ],
            scopeGuard:
              "Conseil uniquement. Pas d'implementation, redaction, developpement ou gestion de campagne inclus.",
            minimum: "Minimum 3 mois",
            cta: { label: "Demarrer le mentorat", href: "/book-a-call" },
          },
          {
            id: "mentor-growth-advisory",
            name: "SEO Mentor Growth Advisory",
            price: "A partir de $1,500/mois",
            recommended: true,
            positioning:
              "Le plan mentor recommande pour les equipes avec capacite interne mais priorisation SEO incertaine.",
            bestFor: [
              "Marketer interne ou fondateur ayant besoin de guidance SEO continue",
              "Equipe contenu/dev avec capacite mais priorisation floue",
              "Entreprise qui veut roadmap et support decisionnel",
            ],
            includes: [
              "2 sessions strategie/conseil mensuelles",
              "Revue de roadmap SEO",
              "Revue des priorites SEO techniques",
              "Revue strategie contenu et briefs",
              "Guidance AI Search / entites",
              "Revue maillage interne et autorite",
              "Memo decisionnel mensuel",
              "Support asynchrone de revue",
            ],
            cta: { label: "Choisir Growth Advisory", href: "/book-a-call" },
          },
          {
            id: "mentor-team-enablement",
            name: "SEO Mentor Team Enablement",
            price: "A partir de $2,500/mois",
            positioning:
              "Formation, QA et processus pour equipes internes contenu, SEO et dev.",
            bestFor: [
              "Equipes contenu",
              "SEO interne junior/mid-level",
              "Equipe dev plus marketing ayant besoin d'un process SEO",
              "Entreprise qui veut monter en competence",
            ],
            includes: [
              "2-3 workshops/revues mensuels",
              "Curriculum de formation equipe",
              "QA de briefs contenu",
              "QA SEO technique",
              "Mise en place de workflow SEO",
              "Standards editoriaux",
              "Process de maillage interne",
              "Revue de mesure",
              "Module de formation AI Search",
              "Support office-hours",
            ],
            cta: { label: "Activer l'equipe", href: "/book-a-call" },
          },
          {
            id: "executive-advisory",
            name: "Executive Search Advisory",
            price: "A partir de $4,500/mois",
            positioning:
              "Direction search senior pour dirigeants qui arbitrent budget, equipe, fournisseurs et expansion.",
            bestFor: [
              "CMO",
              "Fondateur",
              "Head of growth",
              "Entreprise multi-marche",
              "Leadership decidant agence/interne/hybride",
            ],
            includes: [
              "Session executive mensuelle",
              "Revue des opportunites de croissance search",
              "Priorisation de roadmap",
              "Revue agences/fournisseurs",
              "Guidance hiring et structure equipe",
              "Revue mesure et KPI",
              "Guidance expansion marche",
              "Synthese prete pour leadership",
            ],
            cta: { label: "Reserver Executive Advisory", href: "/book-a-call" },
          },
          {
            id: "custom-mentorship",
            name: "Custom SEO Mentorship",
            price: "Sur mesure",
            positioning:
              "Conseil sur mesure pour programmes multi-marche, enterprise, formation, migration, PPC ou AI Search.",
            bestFor: [
              "Conseil multi-marche",
              "Construction d'equipe SEO interne",
              "Programme de formation corporate",
              "Conseil SEO plus PPC plus AI Search",
              "Programme de workshops trimestriels",
              "Conseil migration",
              "Gouvernance enterprise",
            ],
            includes: [
              "Cadence de conseil sur mesure",
              "Planification de workshops",
              "Modele de gouvernance et QA",
              "Enablement leadership et equipe",
            ],
            cta: { label: "Demander un mentorat sur mesure", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "audits",
        label: "Audits & Add-ons",
        eyebrow: "Diagnostics et support canal",
        title: "Tarifs audits, PPC et add-ons",
        intro:
          "Les audits clarifient le bon scope. Les add-ons soutiennent demande payante, planification contenu, projets techniques, localisation et autorite.",
        plans: [
          {
            id: "free-audit",
            name: "Audit SEO gratuit",
            price: "$0",
            positioning:
              "Diagnostic rapide pour comprendre si Local, National, Global, Mentor, PPC ou sur mesure convient.",
            bestFor: ["Vous ne savez pas par ou commencer", "Besoin de priorisation initiale", "Besoin d'un chemin vers le prix exact"],
            includes: ["Revue site et marche", "Problemes prioritaires", "Prochain scope recommande"],
            cta: { label: "Obtenir l'audit gratuit", href: "/free-seo-audit" },
          },
          {
            id: "search-growth-audit",
            name: "Search Growth Audit",
            price: "A partir de $1,500 one-time",
            positioning: "Audit concentre sur demande, contenu, technique et fit commercial search.",
            bestFor: ["Planification growth", "Clarte roadmap", "Priorisation avant mensuel"],
            includes: ["Revue demande search", "Roadmap priorisee", "Recommandation de scope"],
            cta: { label: "Commencer par un audit", href: "/work/sample-audits" },
          },
          {
            id: "technical-audit",
            name: "Technical SEO Audit",
            price: "A partir de $2,500 one-time",
            positioning: "Revue technique crawl, indexation, rendu, architecture et risques performance.",
            bestFor: ["Sites complexes", "Problemes CMS ou framework", "Preparation migration"],
            includes: ["Carte des problemes techniques", "Correctifs prioritaires", "Recommandations pretes pour implementation"],
            cta: { label: "Voir les audits exemples", href: "/work/sample-audits" },
          },
          {
            id: "ai-search-review",
            name: "AI Search Visibility Review",
            price: "A partir de $1,500 one-time",
            positioning: "Revue clarte d'entite, preparation aux reponses, citations et coherence sources.",
            bestFor: ["Visibilite reponses IA", "Coherence entite", "Gaps d'autorite contenu"],
            includes: ["Snapshot preparation IA", "Revue entites et citations", "Liste d'actions"],
            cta: { label: "Revoir la visibilite IA", href: "/work/sample-audits/ai-search-visibility-review" },
          },
          {
            id: "ppc-organic-review",
            name: "PPC + Organic Intelligence Review",
            price: "A partir de $2,500 one-time",
            positioning: "Revue paid et organic pour identifier capture de demande, gaspillage et chevauchements.",
            bestFor: ["Equipes paid search", "Planification SEO plus SEM", "Chevauchement mots-cles et landing pages"],
            includes: ["Revue requetes paid/organic", "Carte d'opportunites landing pages", "Intelligence budget"],
            cta: { label: "Revoir PPC + organic", href: "/work/sample-audits/ppc-organic-intelligence" },
          },
          {
            id: "international-market-map",
            name: "International SEO Market Map",
            price: "A partir de $3,500 one-time",
            positioning: "Carte marche pour expansion multi-pays, multilingue ou regionale.",
            bestFor: ["Expansion USA, Canada, Australie", "Decisions langue/marche", "Planification localisation"],
            includes: ["Carte d'intention marche", "Revue localisation technique", "Roadmap marches prioritaires"],
            cta: { label: "Cartographier le SEO international", href: "/work/sample-audits/international-seo-market-map" },
          },
          {
            id: "ppc-management",
            name: "PPC Management",
            price: "A partir de $1,500/mois ou 10-12% du spend publicitaire, le montant le plus eleve",
            positioning: "Gestion paid search alignee sur l'intelligence organique et la demande commerciale.",
            bestFor: ["Capture rapide de demande payante", "Alignement search et PPC", "Controle budget"],
            includes: ["Revue structure campagne", "Intelligence requetes search", "Recommandations landing pages", "Reporting mensuel"],
            scopeGuard: "Le spend publicitaire n'est pas inclus.",
            cta: { label: "Discuter du scope PPC", href: "/book-a-call" },
          },
          {
            id: "content-cluster-planning",
            name: "Content Cluster Planning",
            price: "A partir de $1,500/projet",
            positioning: "Planification clusters, briefs et direction de maillage interne.",
            bestFor: ["Equipes editoriales", "Construction d'autorite", "Planification contenu"],
            includes: ["Carte topic cluster", "Direction briefs", "Opportunites de maillage interne"],
          },
          {
            id: "digital-pr-authority",
            name: "Digital PR / Authority Campaign",
            price: "A partir de $3,000/projet",
            positioning: "Planification autorite et support digital PR sans liens ou placements garantis.",
            bestFor: ["Campagnes d'autorite", "Contenu expert", "Support preuve et citation"],
            includes: ["Revue angles campagne", "Carte opportunites autorite", "Planification outreach"],
            scopeGuard: "La digital PR n'inclut pas de liens garantis ni de placements garantis.",
          },
          {
            id: "technical-project",
            name: "Technical SEO Project",
            price: "A partir de $2,500/projet",
            positioning: "Support SEO technique cadre pour problemes specifiques ou plan d'implementation.",
            bestFor: ["Dette technique", "Changements CMS", "Support migration"],
            includes: ["Diagnostic probleme", "Priorisation correctifs", "Recommandations pretes pour developpeurs"],
          },
          {
            id: "localization-support",
            name: "Localization / International SEO Support",
            price: "Sur mesure",
            positioning: "Support sur mesure langue, pays, hreflang, localisation contenu et expansion marche.",
            bestFor: ["SEO multilingue", "Lancement multi-pays", "Strategie de contenu regionale"],
            includes: ["Revue localisation", "Cartographie pays/langue", "QA SEO international"],
          },
        ],
        notes: [
          "Le spend publicitaire n'est pas inclus.",
          "La digital PR n'inclut pas de liens garantis ni de placements garantis.",
          "Les audits peuvent definir le bon scope mensuel.",
        ],
        cta: { label: "Commencer par un audit", href: "/free-seo-audit" },
      },
    ],
  },
  comparison: {
    eyebrow: "Comparaison",
    title: "Comparer tous les scopes de depart.",
    description:
      "Utilisez ce tableau pour comprendre les differences avant de demander un devis precis.",
    contextTitle: "Comparer la voie tarifaire selectionnee.",
    contextDescription:
      "Chaque vue garde la comparaison proche de l'onglet consulte. Ouvrez la comparaison complete seulement si vous avez besoin de tous les scopes cote a cote.",
    fullComparisonLabel: "Voir la comparaison complete",
    hideFullComparisonLabel: "Masquer la comparaison complete",
    columns: [
      { id: "localStarter", label: "Local SEO Starter" },
      { id: "nationalFoundation", label: "National SEO Foundation" },
      { id: "nationalGrowth", label: "National SEO Growth" },
      { id: "globalExpansion", label: "Global SEO Expansion" },
      { id: "mentorGrowth", label: "SEO Mentor Growth" },
      { id: "enterpriseCustom", label: "Enterprise Custom" },
    ],
    rows: [
      {
        label: "Ideal pour",
        values: {
          localStarter: "Une localisation ou zone de service",
          nationalFoundation: "Roadmap sur un pays",
          nationalGrowth: "Execution growth serieuse",
          globalExpansion: "Expansion multi-pays",
          mentorGrowth: "Guidance equipe interne",
          enterpriseCustom: "Systemes multi-marche complexes",
        },
      },
      {
        label: "Portee marche",
        values: {
          localStarter: "Locale",
          nationalFoundation: "Un pays",
          nationalGrowth: "Un pays",
          globalExpansion: "Plusieurs pays/langues",
          mentorGrowth: "Selon scope equipe",
          enterpriseCustom: "Enterprise / multi-marche",
        },
      },
      {
        label: "Execution incluse",
        values: {
          localStarter: "Guidance et checklist ciblees",
          nationalFoundation: "Roadmap d'abord",
          nationalGrowth: "Planification et QA execution",
          globalExpansion: "Planification multi-marche",
          mentorGrowth: "Conseil, pas implementation",
          enterpriseCustom: "Cadre au cas par cas",
        },
      },
      {
        label: "Conseil inclus",
        values: {
          localStarter: "Leger",
          nationalFoundation: "Mensuel",
          nationalGrowth: "Revue strategique mensuelle",
          globalExpansion: "Conseil par marche",
          mentorGrowth: "Service principal",
          enterpriseCustom: "Conseil senior",
        },
      },
      {
        label: "SEO technique",
        values: {
          localStarter: "Revue basique",
          nationalFoundation: "Revue et roadmap",
          nationalGrowth: "Roadmap et QA",
          globalExpansion: "Revue technique internationale",
          mentorGrowth: "Revue prioritaire",
          enterpriseCustom: "Avance",
        },
      },
      {
        label: "Strategie contenu",
        values: {
          localStarter: "Revue limitee page locale",
          nationalFoundation: "Gaps et clusters",
          nationalGrowth: "Planification autorite",
          globalExpansion: "Strategie localisation",
          mentorGrowth: "Revue briefs et strategie",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "Preparation AI Search",
        values: {
          localStarter: "Recommandations legeres",
          nationalFoundation: "Snapshot",
          nationalGrowth: "Optimisation incluse",
          globalExpansion: "Revue coherence entite",
          mentorGrowth: "Guidance incluse",
          enterpriseCustom: "Gouvernance sur mesure",
        },
      },
      {
        label: "Google Business Profile",
        values: {
          localStarter: "Inclus",
          nationalFoundation: "Si pertinent",
          nationalGrowth: "Si pertinent",
          globalExpansion: "Si les marches locaux comptent",
          mentorGrowth: "Conseil si besoin",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "SEO local",
        values: {
          localStarter: "Focus principal",
          nationalFoundation: "Scope support",
          nationalGrowth: "Scope support",
          globalExpansion: "Par marche",
          mentorGrowth: "Conseil si besoin",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "SEO international",
        values: {
          localStarter: "Non inclus",
          nationalFoundation: "Non inclus",
          nationalGrowth: "Limite",
          globalExpansion: "Focus principal",
          mentorGrowth: "Disponible selon scope",
          enterpriseCustom: "Central si besoin",
        },
      },
      {
        label: "Intelligence PPC",
        values: {
          localStarter: "Non inclus",
          nationalFoundation: "Optionnel",
          nationalGrowth: "Recommandations",
          globalExpansion: "Optionnel",
          mentorGrowth: "Disponible selon scope",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "Formation equipe",
        values: {
          localStarter: "Non incluse",
          nationalFoundation: "Legere",
          nationalGrowth: "Optionnelle",
          globalExpansion: "Optionnelle",
          mentorGrowth: "Disponible selon scope",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "Reporting",
        values: {
          localStarter: "Simple",
          nationalFoundation: "Mensuel",
          nationalGrowth: "Reporting intelligence search",
          globalExpansion: "Par marche",
          mentorGrowth: "Memo decisionnel",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "Cadence de revue",
        values: {
          localStarter: "Checklist mensuelle",
          nationalFoundation: "Mensuelle",
          nationalGrowth: "Revue strategique mensuelle",
          globalExpansion: "Mensuelle / par marche",
          mentorGrowth: "2 sessions/mois",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "Engagement minimum",
        values: {
          localStarter: "3 mois",
          nationalFoundation: "Selon scope",
          nationalGrowth: "Selon scope",
          globalExpansion: "Selon scope",
          mentorGrowth: "Selon scope",
          enterpriseCustom: "Sur mesure",
        },
      },
      {
        label: "Prix de depart",
        values: {
          localStarter: "A partir de $1,000/mois",
          nationalFoundation: "A partir de $2,500/mois",
          nationalGrowth: "A partir de $4,500/mois",
          globalExpansion: "A partir de $7,500/mois",
          mentorGrowth: "A partir de $1,500/mois",
          enterpriseCustom: "Sur mesure a partir de $12,000/mois",
        },
      },
    ],
    exactPricingNote:
      "Besoin d'un prix exact ? Demandez un audit gratuit ou reservez un appel strategie. Nous recommanderons le plus petit scope capable de soutenir vos objectifs de facon realiste.",
  },
  decisionGuide: {
    eyebrow: "Guide de decision",
    title: "Vous hesitez ? Choisissez votre situation.",
    description:
      "Choisissez la situation la plus proche et le selecteur tarifaire ira vers le bon point de depart.",
    ariaLabel: "Choisir votre situation tarifaire",
    paths: [
      {
        id: "local-visibility",
        tabId: "local",
        trigger: "J'ai besoin de visibilite locale",
        planName: "Local SEO Starter",
        startingPrice: "A partir de $1,000/mois",
        why: "Une base locale ciblee suffit souvent quand l'entreprise a une localisation principale, une zone de service et peu de complexite technique.",
        cta: { label: "Obtenir un audit local", href: "/free-seo-audit" },
      },
      {
        id: "national-demand",
        tabId: "national",
        trigger: "Je veux de la demande nationale",
        planName: "National SEO Growth System",
        startingPrice: "A partir de $4,500/mois",
        why: "La demande nationale exige souvent une carte search plus forte, une roadmap technique, autorite contenu, AI Search et reporting ensemble.",
        cta: { label: "Discuter growth system", href: "/book-a-call" },
      },
      {
        id: "cross-country",
        tabId: "global",
        trigger: "Je vends dans plusieurs pays",
        planName: "Global SEO Expansion",
        startingPrice: "A partir de $7,500/mois",
        why: "Le multi-pays exige architecture, intention marche, QA localisation et reporting par marche.",
        cta: { label: "Planifier le scope global", href: "/book-a-call" },
      },
      {
        id: "search-ready-website",
        tabId: "websites",
        trigger: "J'ai besoin d'un site pret pour la recherche",
        planName: "Growth Website",
        startingPrice: "A partir de $6,500 one-time",
        why: "Un site pret pour la croissance doit connecter architecture de pages, SEO technique, donnees structurees, capture de leads et analytics avant le lancement.",
        cta: { label: "Demarrer un projet site web", href: "/contact" },
      },
      {
        id: "senior-guidance",
        tabId: "mentor",
        trigger: "J'ai besoin d'un conseil SEO senior",
        planName: "SEO Mentor Growth Advisory",
        startingPrice: "A partir de $1,500/mois",
        why: "Votre equipe peut executer, mais la priorisation senior, la revue technique, la QA contenu et le support decisionnel reduisent le gaspillage.",
        cta: { label: "Demarrer le mentorat", href: "/book-a-call" },
      },
      {
        id: "audit-first",
        tabId: "audits",
        trigger: "Je veux commencer par un audit",
        planName: "Audit SEO gratuit",
        startingPrice: "$0",
        why: "Un diagnostic peut identifier le plus petit scope realiste avant de vous engager sur un programme mensuel.",
        cta: { label: "Audit SEO gratuit", href: "/free-seo-audit" },
      },
    ],
  },
  drivers: {
    eyebrow: "Facteurs de prix final",
    title: "Qu'est-ce qui influence le prix final ?",
    description:
      "Les prix ci-dessus sont des points de depart. Le prix le plus precis vient apres comprehension du site, marche, concurrence et besoins d'execution.",
    items: [
      { label: "Nombre de localisations", description: "Plus de sites ajoutent GBP, pages locales, reporting et reputation." },
      { label: "Nombre de pays/langues", description: "Plus de marches demandent localisation, controles techniques et mapping d'intention." },
      { label: "Taille du site", description: "Les grands sites demandent crawl, architecture, maillage interne et QA plus profonds." },
      { label: "Dette technique", description: "Indexation, rendu, vitesse, duplication et migrations augmentent la complexite." },
      { label: "Complexite CMS", description: "CMS custom, headless et limites workflow affectent la vitesse d'execution." },
      { label: "Production de contenu", description: "Strategie seule differe de redaction, edition, refreshs et QA." },
      { label: "Niveau de concurrence", description: "Les SERP difficiles exigent plus d'autorite, profondeur contenu, qualite technique et patience." },
      { label: "Besoins d'autorite/liens", description: "Digital PR et autorite sont scopes separement et ne garantissent jamais de placements." },
      { label: "Spend PPC", description: "Plus de spend demande plus de structure, revue requetes et QA conversion." },
      { label: "Reporting/analytics", description: "Analytics ou CRM confus demandent nettoyage avant reporting fiable." },
      { label: "Support interne", description: "Redacteurs, devs, marketers et dirigeants disponibles changent le modele." },
      { label: "Vitesse d'execution", description: "Les delais rapides demandent plus de temps senior et des cycles plus serres." },
    ],
  },
  includedExcluded: {
    eyebrow: "Clarte du scope",
    title: "Inclus vs non inclus sauf si cadre.",
    description:
      "Taskcover rend les scopes de depart clairs pour eviter qu'un plan d'entree ressemble a une campagne full-service.",
    includedTitle: "Inclus selon le scope",
    excludedTitle: "Non inclus sauf si cadre",
    included: [
      "Strategie SEO",
      "Revue technique",
      "Carte de demande search",
      "Roadmap contenu",
      "Preparation AI Search",
      "Maillage interne",
      "Architecture site web si scopee",
      "Reporting",
      "Revue mensuelle",
    ],
    excluded: [
      "Spend publicitaire",
      "Redaction complete de contenu",
      "Implementation developpement",
      "Frais de placement PR",
      "Backlinks garantis",
      "Classements garantis",
      "Revue legal/compliance",
      "Production de traduction",
      "Implementation CRM",
      "Developpement web sur mesure",
      "Outils payants detenus par le client",
    ],
  },
  customScope: {
    eyebrow: "Tarif sur mesure",
    title: "Besoin d'un scope sur mesure ?",
    description:
      "Si votre entreprise a plusieurs localisations, plusieurs marches, des exigences techniques complexes, un volume contenu eleve, du paid search ou des besoins d'equipe interne, nous construirons un scope sur mesure apres diagnostic.",
    useCases: [
      "SEO multi-sites",
      "SEO enterprise",
      "Migration de site",
      "Developpement de site web",
      "SEO international",
      "SEO multilingue",
      "Digital PR",
      "Production de contenu",
      "Integration PPC + SEO",
      "SEO Mentor pour equipes internes",
    ],
    primaryCta: { label: "Demander un tarif sur mesure", href: "/free-seo-audit" },
    secondaryCta: { label: "Reserver un appel", href: "/book-a-call" },
    note: "Pour le prix le plus precis, commencez par un audit SEO gratuit ou un appel strategie.",
  },
  proof: {
    eyebrow: "Preuve",
    title: "Utiliser les realisations verifiees pour comprendre le scope derriere le prix.",
    description:
      "Ces exemples montrent differents systemes de croissance search. Taskcover n'invente pas de metriques ni de garanties.",
    groups: [
      { label: "Preuves SEO local", caseStudySlugs: ["casa-madera", "the-bamboo-bar", "avis"] },
      { label: "Preuves SEO national", caseStudySlugs: ["british-university-vietnam", "matthew-jeffery-law-firm", "skatepro"] },
      { label: "Preuves SEO global", caseStudySlugs: ["agoda", "ccleaner", "fwd-insurance", "novaworld"] },
    ],
    cta: { label: "Voir tous les cas clients", href: "/work/case-studies" },
  },
  faq: {
    eyebrow: "FAQ tarifs",
    title: "Questions avant de choisir un scope.",
    items: [
      { q: "Quelle est la difference entre SEO local, national et global ?", a: "Le SEO local vise une ville, zone de service ou ensemble de localisations. Le SEO national cible un marche pays. Le SEO global gere plusieurs pays, langues, localisation et comportements de recherche par marche." },
      { q: "Pourquoi le SEO local commence a $1,000/mois ?", a: "Le starter est volontairement concentre : une localisation ou zone de service, revue locale, guidance Google Business Profile, snapshot concurrentiel et reporting simple. Ce n'est pas une campagne SEO full-service." },
      { q: "Puis-je commencer en SEO local puis evoluer ?", a: "Oui. Beaucoup d'entreprises commencent localement, puis passent au multi-sites, national, PPC, contenu ou technique apres diagnostic et roadmap." },
      { q: "Les projets de site web incluent-ils le SEO ?", a: "Oui. Les projets Developpement de site web incluent architecture prete pour la recherche, metadonnees principales, schema lorsque pertinent, chemins de maillage interne, performance, capture de leads et preparation analytics. Le contenu SEO continu et l'autorite sont scopes separement." },
      { q: "SEO Mentor est-il different de l'execution SEO ?", a: "Oui. SEO Mentor est centre sur le conseil. Il aide votre equipe a mieux decider, revoir les priorites et ameliorer le process. Implementation, redaction, developpement et campagne ne sont inclus que si scopes separement." },
      { q: "A qui s'adresse SEO Mentor ?", a: "SEO Mentor convient aux fondateurs, marketers, equipes SEO internes, equipes contenu, dirigeants et entreprises avec capacite d'execution mais besoin de direction SEO senior." },
      { q: "Notre equipe interne peut-elle executer pendant que Taskcover conseille ?", a: "Oui. C'est le meilleur fit pour SEO Mentor Growth Advisory et Team Enablement. Taskcover peut revoir roadmaps, briefs, priorites techniques, maillage interne, AI Search et reporting." },
      { q: "SEO Mentor peut-il inclure AI Search et PPC ?", a: "Oui, selon le scope. AI Search, entites, qualite contenu et intelligence PPC/organic peuvent etre inclus quand ces decisions affectent la croissance search." },
      { q: "Le spend publicitaire est-il inclus dans le PPC ?", a: "Non. La gestion PPC commence a $1,500/mois ou 10-12% du spend publicitaire, le montant le plus eleve. Le spend est separe et paye par le client." },
      { q: "La redaction de contenu est-elle incluse ?", a: "Strategie contenu, planning, briefs et QA peuvent etre inclus selon le plan. La redaction complete ou production a fort volume est scopee separement." },
      { q: "Garantissez-vous les classements ?", a: "Non. Taskcover ne garantit pas les classements, backlinks, placements, trafic ou revenu. Nous construisons des systemes search, priorisons le travail et reportons honnetement sur les progres et contraintes." },
      { q: "Travaillez-vous avec les USA, le Canada et l'Australie ?", a: "Oui. Taskcover soutient des programmes de croissance search pour USA, Canada et Australie, en local, national et multi-marche." },
      { q: "Pouvez-vous soutenir l'anglais, le francais et l'espagnol ?", a: "Oui. Taskcover peut soutenir strategie search, revue localisation et SEO international en anglais, francais et espagnol. La production de traduction est scopee separement." },
      { q: "Quel est l'engagement minimum ?", a: "Local SEO Starter et SEO Mentor Office Hours ont un minimum de 3 mois. Les autres scopes dependent du marche, de la complexite et des besoins d'execution." },
      { q: "Comment obtenir un devis exact ?", a: "Demandez un audit SEO gratuit ou reservez un appel strategie. Taskcover examinera site, marche, concurrence et besoins d'execution avant de recommander le plus petit scope realiste." },
    ],
  },
  finalCta: {
    eyebrow: "Prochaine etape",
    title: "Vous ne savez pas quel scope choisir ?",
    description:
      "Envoyez votre site et vos objectifs de marche. Taskcover recommandera le plus petit scope capable de soutenir vos objectifs de facon realiste.",
    primaryCta: { label: "Audit SEO gratuit", href: "/free-seo-audit" },
    secondaryCta: { label: "Reserver un appel", href: "/book-a-call" },
  },
  ui: {
    bestFor: "Ideal pour",
    includes: "Inclus",
    minimum: "Minimum",
    addOn: "Add-on",
    recommended: "Recommande",
    scopeGuard: "Limite de scope",
    notes: "Notes",
    startingPoint: "Point de depart",
    viewPlan: "Voir le plan",
    selectPath: "Choisir cette voie",
    recommendation: "Recommandation",
    compareRowHeader: "Detail du plan",
  },
} satisfies PricingContent;
