import type { SampleAudit, SampleAuditSlug, WorkContent } from "../work.types";
import { caseStudyDetails } from "./case-studies";

const disclosure =
  "Exemple de livrable illustratif. Il démontre la méthodologie de Taskcover et ne représente pas une mission client ni un résultat spécifique.";

const sampleOrder: SampleAuditSlug[] = [
  "technical-seo-audit",
  "ai-search-visibility-review",
  "content-gap-map",
  "local-seo-audit",
  "ecommerce-search-architecture",
  "international-seo-market-map",
  "ppc-organic-intelligence",
  "90-day-search-growth-roadmap",
];

function sample(input: {
  slug: SampleAuditSlug;
  title: string;
  shortLabel: string;
  focus: string;
  question: string;
  visual: string;
  inputs: string[];
  answers: string[];
  method: string[];
  findings: string[];
  priority: string[];
  output: string[];
  roadmap: string[];
  services: string[];
  industries: string[];
}): SampleAudit {
  const statuses = ["Critique", "Priorité élevée", "À examiner", "À surveiller"];
  return {
    id: `sample-${input.slug}`,
    type: "sample-audit",
    slug: input.slug,
    title: input.title,
    shortLabel: input.shortLabel,
    summary: input.focus,
    focus: input.focus,
    buyerQuestion: input.question,
    visualStyle: input.visual,
    eyebrow: "Livrable exemple",
    permissionStatus: "internal-only",
    verificationStatus: "not-applicable",
    publicDisclosure: true,
    requiredContextComplete: false,
    illustrative: true,
    disclosureText: disclosure,
    inputs: input.inputs.map((label) => ({ label, detail: "Entrée méthodologique, pas une preuve client." })),
    answers: input.answers,
    method: input.method.map((label, index) => ({
      label,
      detail: ["Collecter", "Diagnostiquer", "Prioriser", "Traduire"][index] ?? "Affiner",
      status: ["Cartographié", "Évalué", "Priorisé", "Prêt pour l'exécution"][index] ?? "Validé",
    })),
    findings: input.findings.map((label, index) => ({
      label,
      detail: statuses[index % statuses.length],
      status: statuses[index % statuses.length],
    })),
    priority: input.priority.map((label) => ({
      label,
      detail: "Évalué selon l'impact, les dépendances, la confiance et l'effort.",
      status: "Priorisé",
    })),
    outputPreview: input.output.map((label) => ({
      label,
      detail: "Structure d'exemple avec libellés qualitatifs.",
      status: "Illustratif",
    })),
    roadmap: input.roadmap.map((label) => ({
      label,
      detail: "Converti en actions, responsabilités et points de décision.",
      status: "Prêt",
    })),
    relatedServices: input.services,
    relatedIndustries: input.industries,
    deliverables: input.output,
    methodology: input.method,
    faq: [
      {
        q: "S'agit-il d'un audit client réel ?",
        a: "Non. C'est un exemple illustratif qui montre la structure d'analyse et de recommandation de Taskcover.",
      },
      {
        q: "La même structure peut-elle servir à une mission réelle ?",
        a: "Oui. Le travail réel utilise des données vérifiées, le contexte client, les règles de permission et des sources de mesure.",
      },
      {
        q: "Cet exemple promet-il un résultat ?",
        a: "Non. Il montre la logique de décision sans revendiquer de positions, trafic, prospects, revenus ni visibilité sur une plateforme.",
      },
    ],
    metaTitle: `${input.title} - exemple | Taskcover Agency`,
    metaDescription: `${input.title} illustratif montrant la méthodologie Taskcover sans nom client, fausse métrique ni résultat inventé.`,
  };
}

const samples = {
  "technical-seo-audit": sample({
    slug: "technical-seo-audit",
    title: "Audit SEO technique",
    shortLabel: "SEO technique",
    focus: "Architecture de crawl, indexation, rendu, schéma et risques de mise en production traduits en priorités.",
    question: "Quelles contraintes techniques limitent la recherche ou créent un risque futur ?",
    visual: "Architecture de crawl et registre de priorités",
    inputs: ["Chemins de crawl", "États d'indexation", "Comportement de rendu", "Couverture schema", "Historique des releases"],
    answers: ["Systèmes à traiter en priorité", "Points à surveiller", "Correctifs qui débloquent la suite"],
    method: ["Scan d'architecture", "Revue d'indexation", "Évaluation rendu et performance", "Traduction du risque release"],
    findings: ["Pattern d'indexation bloqué", "Risque de rendu par gabarit", "Schema à examiner", "Dépendance de migration"],
    priority: ["Accès recherche critique", "Correctifs de gabarit", "Contrôles validés", "File de surveillance"],
    output: ["Registre des problèmes", "Carte des états de crawl", "Table schema", "Checklist de release"],
    roadmap: ["Rétablir l'accès recherche", "Regrouper les changements", "Valider le déploiement", "Surveiller l'index"],
    services: ["technical-seo", "seo-audit", "seo-agency"],
    industries: ["saas-seo", "ecommerce-seo", "travel-seo"],
  }),
  "ai-search-visibility-review": sample({
    slug: "ai-search-visibility-review",
    title: "Revue de visibilité en recherche IA",
    shortLabel: "Visibilité IA",
    focus: "Clarté d'entité, surfaces de réponse, sources de citation, contenu structuré et signaux d'autorité.",
    question: "La marque est-elle compréhensible et citable dans les environnements de réponses IA ?",
    visual: "Graphe d'entité et carte des surfaces de réponse",
    inputs: ["Énoncés d'entité", "Couverture des sources", "Contenu structuré", "Autorité tierce", "Pages prêtes pour les réponses"],
    answers: ["Zones de clarté faibles", "Sources qui soutiennent les citations", "Formats de réponse à produire"],
    method: ["Extraction d'entités", "Revue des sources", "Évaluation des formats de réponse", "Cartographie de l'autorité"],
    findings: ["Relation d'entité incomplète", "Source de citation à examiner", "Opportunité de contenu structuré", "Dépendance de preuve tierce"],
    priority: ["Définition d'entité", "Renforcement des sources", "Production de blocs de réponse", "Validation de l'autorité"],
    output: ["Graphe d'entité", "Matrice des surfaces de réponse", "Registre des sources", "Roadmap de préparation IA"],
    roadmap: ["Clarifier les pages d'entité", "Renforcer les sources", "Ajouter des formats de réponse", "Revoir les preuves tierces"],
    services: ["ai-search-optimization", "content-marketing", "digital-pr-link-building"],
    industries: ["education-seo", "healthcare-seo", "legal-immigration-seo"],
  }),
  "content-gap-map": sample({
    slug: "content-gap-map",
    title: "Carte des lacunes de contenu",
    shortLabel: "Lacunes contenu",
    focus: "Clusters thématiques, intention, autorité, contenus de conversion, mises à jour et maillage interne.",
    question: "Où le contenu manque-t-il, soutient-il mal l'autorité ou se déconnecte-t-il de l'intention d'achat ?",
    visual: "Carte de clusters et matrice d'intention",
    inputs: ["Univers thématique", "Groupes d'intention", "Contenu existant", "Signaux d'autorité", "Parcours de conversion"],
    answers: ["Pages à créer", "Actifs à rafraîchir", "Liens internes à modifier"],
    method: ["Clustering thématique", "Cartographie d'intention", "Revue de couverture", "Alignement conversion"],
    findings: ["Écart en phase de décision", "Sujet d'autorité sous-développé", "Opportunité de mise à jour", "Chemin de lien interne à examiner"],
    priority: ["Sujets liés au revenu", "Clusters d'autorité", "File de rafraîchissement", "Pages de soutien conversion"],
    output: ["Carte de clusters", "Matrice d'intention", "Registre de couverture", "Liste d'opportunités de liens"],
    roadmap: ["Créer les écarts prioritaires", "Rafraîchir les actifs", "Connecter les pages", "Mesurer la couverture"],
    services: ["content-marketing", "seo-agency", "seo-audit"],
    industries: ["education-seo", "travel-seo", "saas-seo"],
  }),
  "local-seo-audit": sample({
    slug: "local-seo-audit",
    title: "Audit SEO local",
    shortLabel: "SEO local",
    focus: "Présence locale, fiche Google Business Profile, pages locales, avis, citations et parcours de conversion.",
    question: "Les acheteurs locaux peuvent-ils trouver, faire confiance et agir dans chaque zone desservie ?",
    visual: "Carte de présence locale et parcours de conversion",
    inputs: ["Pages locales", "Champs GBP", "Thèmes d'avis", "Cohérence des citations", "Pages de zone"],
    answers: ["Signaux locaux à renforcer", "Couverture de pages faible", "Parcours de conversion à améliorer"],
    method: ["Revue de présence", "Contrôle GBP", "Classification des avis", "Architecture des pages locales"],
    findings: ["Écart de contenu local", "Profil à compléter", "Cohérence de citation", "Friction de conversion"],
    priority: ["Signaux de localisation", "Pages de service", "Système d'avis", "Nettoyage du parcours"],
    output: ["Carte de présence", "Cadre GBP", "Table de citations", "Parcours local"],
    roadmap: ["Normaliser les données", "Améliorer les pages", "Renforcer les avis", "Valider les chemins de contact"],
    services: ["local-seo", "seo-audit", "content-marketing"],
    industries: ["franchise-local-seo", "healthcare-seo", "legal-immigration-seo"],
  }),
  "ecommerce-search-architecture": sample({
    slug: "ecommerce-search-architecture",
    title: "Revue d'architecture de recherche e-commerce",
    shortLabel: "Architecture e-commerce",
    focus: "Hiérarchie de catégories, découvrabilité produit, facettes, intention d'achat et liens internes.",
    question: "Les moteurs et les acheteurs parcourent-ils le catalogue sans confusion ni gaspillage ?",
    visual: "Arbre de catégories et carte des risques de facettes",
    inputs: ["Arbre de catégories", "Hiérarchie produit", "Règles de facettes", "Intention d'achat", "Chemins merchandising"],
    answers: ["Catégories à consolider", "Facettes risquées", "Lien entre intention et architecture"],
    method: ["Revue catalogue", "Classification des facettes", "Mapping intention-catégorie", "Revue du maillage"],
    findings: ["Contrôle des facettes à examiner", "Profondeur de catégorie déséquilibrée", "Dépendance produit", "Décalage d'intention"],
    priority: ["Contrôle indexable", "Catégories prioritaires", "Architecture produit", "Chemins merchandising"],
    output: ["Arbre de catégories", "Registre des facettes", "Carte d'intention", "Architecture de liens"],
    roadmap: ["Contrôler l'indexation", "Repenser les catégories clés", "Relier produits et guides", "Mesurer la qualité du crawl"],
    services: ["ecommerce-seo", "technical-seo", "content-marketing"],
    industries: ["ecommerce-seo", "travel-seo", "saas-seo"],
  }),
  "international-seo-market-map": sample({
    slug: "international-seo-market-map",
    title: "Carte de marché SEO international",
    shortLabel: "Carte internationale",
    focus: "Priorités pays/langues, profondeur de localisation, hreflang, intention régionale et séquence de déploiement.",
    question: "Quels marchés servir d'abord et quel niveau de localisation est nécessaire ?",
    visual: "Matrice pays-langue et tableau de déploiement",
    inputs: ["Pays cibles", "Langues couvertes", "Intention régionale", "Structure hreflang", "Ressources de localisation"],
    answers: ["Marchés prêts", "Besoins de localisation", "Signaux techniques à corriger"],
    method: ["Revue de marché", "Mapping profondeur linguistique", "Architecture hreflang", "Séquençage"],
    findings: ["Profondeur de localisation faible", "Hreflang à examiner", "Décalage d'intention régionale", "Dépendance de rollout"],
    priority: ["Préparation marché", "Architecture linguistique", "Contenu régional", "Validation technique"],
    output: ["Matrice pays-langue", "Tableau de localisation", "Architecture hreflang", "Séquence de rollout"],
    roadmap: ["Choisir les marchés", "Corriger l'architecture", "Produire le contenu régional", "Valider les signaux"],
    services: ["international-seo", "technical-seo", "content-marketing"],
    industries: ["travel-seo", "education-seo", "saas-seo"],
  }),
  "ppc-organic-intelligence": sample({
    slug: "ppc-organic-intelligence",
    title: "Revue d'intelligence PPC + organique",
    shortLabel: "PPC + organique",
    focus: "Intention partagée, chevauchement paid/organic, pages d'atterrissage, suivi de conversion et logique budgétaire.",
    question: "Où le paid et l'organique doivent-ils partager l'intelligence plutôt que se concurrencer ?",
    visual: "Carte d'intention partagée et registre de chevauchement",
    inputs: ["Termes de recherche", "Cibles organiques", "Pages d'atterrissage", "Suivi de conversion", "Alignement message"],
    answers: ["Ce que le paid apprend au SEO", "Où l'organique réduit le gaspillage", "Pages à aligner avant d'accélérer"],
    method: ["Classification d'intention", "Revue de chevauchement", "Alignement landing page", "Contrôle du tracking"],
    findings: ["Opportunité d'intention partagée", "Page mal alignée", "Tracking à examiner", "Écart de couverture organique"],
    priority: ["Termes à forte intention", "Correctifs pages", "Validation tracking", "Soutien contenu organique"],
    output: ["Carte d'intention", "Table paid-organic", "Tableau d'alignement", "Logique de priorité budgétaire"],
    roadmap: ["Classifier les termes", "Aligner les pages", "Valider le tracking", "Utiliser les apprentissages PPC"],
    services: ["ppc-management", "seo-agency", "content-marketing"],
    industries: ["saas-seo", "ecommerce-seo", "education-seo"],
  }),
  "90-day-search-growth-roadmap": sample({
    slug: "90-day-search-growth-roadmap",
    title: "Roadmap de croissance search sur 90 jours",
    shortLabel: "Roadmap 90 jours",
    focus: "Séquençage, responsabilités, dépendances, plan de mesure et points de décision pour 30/60/90 jours.",
    question: "Que faire d'abord, ensuite et plus tard sans promettre de positions dans un délai fixe ?",
    visual: "Tableau 30/60/90 et carte de dépendances",
    inputs: ["Constats d'audit", "Priorités business", "Capacité équipe", "Dépendances", "Préparation mesure"],
    answers: ["Actions à lancer", "Responsables par voie", "Décisions nécessaires avant exécution"],
    method: ["Synthèse des constats", "Mapping des dépendances", "Plan par responsables", "Conception de mesure"],
    findings: ["Dépendance critique", "Responsable à confirmer", "Confiance de mesure faible", "Point de décision requis"],
    priority: ["Premiers 30 jours", "Jours 31 à 60", "Jours 61 à 90", "Prochain point de décision"],
    output: ["Tableau d'exécution", "Voies de responsabilité", "Carte de dépendances", "Plan de mesure"],
    roadmap: ["Stabiliser les fondations", "Construire les actifs", "Valider l'implémentation", "Réviser et ajuster"],
    services: ["seo-agency", "seo-audit", "seo-mentor-service"],
    industries: ["saas-seo", "travel-seo", "franchise-local-seo"],
  }),
} satisfies Record<SampleAuditSlug, SampleAudit>;

export const work: WorkContent = {
  ui: {
    home: "Accueil",
    work: "Réalisations",
    breadcrumb: "Fil d'Ariane",
    disclosureLabel: "Mention",
    illustrativeSample: "Exemple illustratif",
    verifiedCaseStudy: "Cas client vérifié",
    verifiedClientResult: "Résultat client vérifié",
    confidentialEngagement: "Mission confidentielle",
    privateReference: "Référence privée",
    noPublicCaseStudiesTitle: "Aucun cas client nommé n'est affiché sans preuve vérifiée.",
    noPublicResultsTitle: "Aucun résultat client public n'est affiché sans contexte de mesure vérifié.",
    noPublicRegistryBody:
      "Taskcover publie uniquement les enregistrements avec permission publique vérifiée, preuve vérifiée, contexte complet, divulgation publique et formulation approuvée.",
    publicRegistry: "Registre public",
    evidenceRequired: "Preuves requises",
    measurementContext: "Contexte de mesure",
    explore: "Explorer",
    viewSample: "Voir l'exemple",
    getAudit: "Obtenir un audit SEO gratuit",
    bookCall: "Réserver un appel stratégique",
    relatedSamples: "Livrables exemples associés",
    relatedServices: "Services associés",
    relatedIndustries: "Secteurs associés",
    priority: "Priorité",
    status: "Statut",
    input: "Entrée",
    method: "Méthode",
    output: "Sortie",
    overview: "Vue d'ensemble",
    clientBackground: "Contexte client",
    challenge: "Défi",
    objectives: "Objectifs",
    strategy: "Stratégie",
    execution: "Exécution",
    servicesDelivered: "Services livrés",
    results: "Résultats",
    keyMetrics: "Indicateurs clés",
    visualGallery: "Galerie visuelle",
    keyLearning: "Enseignement clé",
    relatedMarkets: "Marchés liés",
    finalCta: "Prochaine étape",
    readCase: "Lire l'étude complète",
    viewCaseStudy: "Voir l'étude de cas",
    filterIndustry: "Filtrer par secteur",
    filterMarket: "Filtrer par marché",
    filterService: "Filtrer par service",
    clearFilters: "Effacer les filtres",
    resultCount: "{count} cas vérifiés",
    caseStudyLibrary: "Bibliothèque de cas vérifiés",
    featuredCaseStudy: "Étude de cas en vedette",
    verifiedOutcomesByGrowthLever: "Résultats vérifiés par levier de croissance",
    serviceToProofMap: "Carte service-preuve",
    usedInCaseStudies: "Utilisé dans {count} études de cas",
    viewService: "Voir le service",
    viewRelatedCases: "Voir les cas associés",
    growthLever: "Levier de croissance",
    metricContext: "Contexte de la métrique",
    caseToResultMatrix: "Matrice cas-résultat",
    resultCategories: "Catégories de résultats",
    industryMarketDistribution: "Répartition secteur et marché",
    resultHighlights: "Résultats vérifiés en évidence",
    relatedProof: "Preuve associée",
    allCases: "Tous les cas",
    client: "Client",
    focus: "Priorité",
    period: "Période",
    startingPoint: "Point de départ",
    workstream: "Flux de travail",
  },
  channelLinks: [
    { label: "Cas clients", href: "/work/case-studies", description: "Registre futur sûr pour des récits clients nommés lorsque les preuves sont approuvées." },
    { label: "Audits exemples", href: "/work/sample-audits", description: "Livrables illustratifs montrant comment Taskcover pense et structure le travail." },
    { label: "Cadres de croissance search", href: "/work/search-growth-frameworks", description: "Modèle opératoire qui transforme la recherche en exécution." },
    { label: "Résultats clients", href: "/work/client-results", description: "Standard de mesure pour publier des résultats vérifiés." },
  ],
  sampleAuditLinks: sampleOrder.map((slug) => ({ label: samples[slug].title, href: `/work/sample-audits/${slug}`, description: samples[slug].focus })),
  hub: {
    metaTitle: "Réalisations, audits exemples et systèmes de croissance search | Taskcover Agency",
    metaDescription: "Explorez les livrables exemples, le cadre de croissance search, les standards de cas client et les règles de publication des résultats vérifiés.",
    eyebrow: "Système de travail",
    h1: "De l'intelligence search à l'exécution",
    intro:
      "Le travail de Taskcover s'organise autour des preuves, du diagnostic, de la priorisation, de l'accompagnement d'implémentation, de la mesure et de l'apprentissage.",
    command: [
      { label: "Recherche", detail: "Marché, recherche, contenu, technique et contexte acheteur.", status: "Évalué" },
      { label: "Diagnostic", detail: "Contraintes, opportunités et niveau de confiance séparés.", status: "Validé" },
      { label: "Stratégie", detail: "Recommandations liées à la pertinence business et à la demande.", status: "Priorisé" },
      { label: "Roadmap", detail: "Actions séquencées par dépendance et capacité d'exécution.", status: "Cartographié" },
      { label: "Mesure", detail: "Source, baseline, période et contexte requis.", status: "Prêt pour exécution" },
      { label: "Itération", detail: "Les apprentissages redessinent le cycle suivant.", status: "Validé" },
    ],
    systemMap: [
      { label: "Audits exemples", detail: "Montrent la structure sans revendication client.", connectsTo: "Roadmaps" },
      { label: "Cadres search", detail: "Expliquent la logique opératoire.", connectsTo: "Voies d'exécution" },
      { label: "Cas clients", detail: "Affichés seulement avec permission et preuve vérifiées.", connectsTo: "Preuve publique" },
      { label: "Résultats clients", detail: "Exigent source, baseline, période et contexte.", connectsTo: "Reporting" },
      { label: "Roadmaps", detail: "Convertissent les constats en travail séquencé.", connectsTo: "Implémentation" },
      { label: "Reporting", detail: "Relie l'apprentissage à la confiance et aux limites.", connectsTo: "Itération" },
    ],
    actionFlow: [
      { label: "Recherche", detail: "Collecter le contexte et la demande.", status: "Évalué" },
      { label: "Diagnostic", detail: "Identifier blocages, écarts et leviers.", status: "Validé" },
      { label: "Priorisation", detail: "Juger impact, effort, dépendance et confiance.", status: "Priorisé" },
      { label: "Roadmap", detail: "Traduire en actions opérationnelles.", status: "Cartographié" },
      { label: "Support d'implémentation", detail: "Accompagner les changements dans les contraintes réelles.", status: "Prêt" },
      { label: "Mesure", detail: "Lire les résultats avec contexte et limites.", status: "Revu" },
    ],
    evidenceMatrix: [
      { label: "Exemple illustratif", detail: "Méthodologie publique sans identité ni résultat client.", status: "Autorisé avec mention" },
      { label: "Cas vérifié", detail: "Permission, contexte, preuve, wording et actifs requis.", status: "Piloté par preuve" },
      { label: "Résultat vérifié", detail: "Source, baseline, période, méthode et attribution requis.", status: "Piloté par preuve" },
      { label: "Mission confidentielle", detail: "Aucune identité, métrique, citation, capture ou URL exposée.", status: "Protégé" },
      { label: "Référence privée", detail: "Partagée seulement via un chemin qualifié et autorisé.", status: "Contrôlé" },
    ],
    cta: {
      title: "Commencer par un audit search qui peut devenir une roadmap d'exécution.",
      description: "L'audit initial peut couvrir santé technique, demande search, autorité contenu, préparation IA, opportunité marché et priorités 90 jours.",
      preview: ["Santé technique", "Demande search", "Autorité contenu", "Préparation IA", "Opportunité marché", "Priorités 90 jours"],
    },
  },
  pages: {
    "case-studies": {
      metaTitle: "Études de cas SEO vérifiées | Taskcover Agency",
      metaDescription: "Explorez 10 études de cas vérifiées de Taskcover Agency dans l'éducation, l'hospitalité, le juridique, l'eCommerce, le travel, le logiciel, l'immobilier et l'assurance.",
      eyebrow: "Bibliothèque de cas vérifiés",
      h1: "10 études de cas vérifiées de Taskcover Agency",
      intro: "Explorez des études de cas publiques détaillées avec récits, métriques, services, visuels et contexte source approuvés.",
    },
    "sample-audits": {
      metaTitle: "Audits SEO exemples et livrables | Taskcover Agency",
      metaDescription: "Explorez huit livrables illustratifs Taskcover couvrant SEO technique, IA, contenu, local, e-commerce, international, PPC et roadmaps.",
      eyebrow: "Livrables exemples",
      h1: "Voir comment Taskcover raisonne",
      intro: "Ces audits exemples démontrent la méthode, la structure d'analyse et la traduction en exécution sans représenter une mission client réelle.",
    },
    "search-growth-frameworks": {
      metaTitle: "Cadre opératoire de croissance search | Taskcover Agency",
      metaDescription: "Le cadre Découvrir, Diagnostiquer, Prioriser, Construire, Mesurer et Apprendre de Taskcover.",
      eyebrow: "Cadre opératoire",
      h1: "Le cadre opératoire de croissance search",
      intro: "La croissance search fonctionne comme un système : contexte, intelligence, priorisation, exécution, mesure et gouvernance.",
    },
    "client-results": {
      metaTitle: "Standard de publication des résultats clients vérifiés | Taskcover Agency",
      metaDescription: "Cadre Taskcover pour publier des résultats uniquement avec preuve vérifiée, permission publique, baseline, période, source et contexte.",
      eyebrow: "Standard des résultats",
      h1: "Des résultats avec contexte de mesure",
      intro: "Les résultats clients ne sont publiés que lorsque la preuve est vérifiée, la permission publique est claire et le contexte complet.",
    },
  },
  caseStudies: {
    registryIntro: "Ces études de cas nommées sont publiques parce que l'identité, le récit, les métriques, les visuels et la divulgation sont approuvés pour Taskcover Agency.",
    verification: [
      { label: "Permission d'identité", detail: "Le client approuve l'usage public du nom.", status: "Requis" },
      { label: "Contexte de mission", detail: "Portée, marché, services et contraintes documentés.", status: "Requis" },
      { label: "Source de mesure", detail: "Sources de résultat vérifiées et approuvées.", status: "Requis" },
      { label: "Wording et actifs", detail: "Claims, citations, captures et visuels relus.", status: "Requis" },
    ],
    requiredEvidence: ["Permission d'identité", "Contexte de mission", "Baseline", "Méthodologie", "Période", "Source de mesure", "Contexte de résultat", "Formulation approuvée", "Actifs approuvés"],
    structure: [
      { label: "Contexte", detail: "Le problème autorisé pour la mission.", status: "Documenté" },
      { label: "Méthode", detail: "Ce que Taskcover a changé ou conseillé.", status: "Expliqué" },
      { label: "Preuve", detail: "La source qui soutient la revendication.", status: "Vérifié" },
      { label: "Limites", detail: "Ce qui ne peut pas être attribué ou divulgué.", status: "Indiqué" },
    ],
    confidential: [
      { label: "Aucun identifiant privé", detail: "Noms, domaines, captures, citations et URLs restent masqués.", status: "Protégé" },
      { label: "Référence privée", detail: "Les références exigent qualification et permission.", status: "Contrôlé" },
      { label: "Preuve non exposée", detail: "Les documents internes ne deviennent pas publics par défaut.", status: "Privé" },
    ],
    cta: {
      title: "Vous voulez évaluer l'approche Taskcover pour votre marché ?",
      description: "Consultez les livrables exemples, puis demandez un audit pour votre contexte search.",
    },
  },
  sampleAudits: {
    selectorIntro: "Comparez les questions traitées par chaque livrable et la manière dont les constats deviennent des priorités.",
    comparison: [
      { label: "Risque technique", detail: "Architecture, indexation, rendu, schema et dépendances.", status: "Diagnostic" },
      { label: "Demande et contenu", detail: "Thèmes, intention, autorité, conversion et rafraîchissements.", status: "Stratégique" },
      { label: "Systèmes marché", detail: "Local, e-commerce, international et paid-organic.", status: "Opérationnel" },
      { label: "Plan d'exécution", detail: "Roadmaps, responsabilités, décisions et mesure.", status: "Actionnable" },
    ],
    everyAudit: ["Question acheteur", "Entrées de données", "Méthode d'analyse", "Structure des constats", "Logique de priorité", "Traduction en roadmap", "Mention visible"],
    priorityFlow: [
      { label: "Gravité", detail: "Ce qui bloque l'accès, la confiance ou la conversion.", status: "Évalué" },
      { label: "Pertinence business", detail: "Lien avec la demande acheteur.", status: "Cartographié" },
      { label: "Effort d'implémentation", detail: "Ressources et dépendances nécessaires.", status: "Estimé" },
      { label: "Confiance de mesure", detail: "Clarté de lecture des changements futurs.", status: "Qualifié" },
    ],
    disclosureTitle: "Les données illustratives ne sont pas des preuves client.",
    disclosureBody: disclosure,
    cta: {
      title: "Transformer une structure exemple en audit réel.",
      description: "Taskcover peut appliquer le cadre pertinent à votre site, marché, contenu ou plan de croissance search.",
    },
  },
  frameworks: {
    stages: [
      { label: "Découvrir", detail: "Modèle business, acheteurs, marché et surfaces search.", status: "Contexte" },
      { label: "Diagnostiquer", detail: "Contraintes techniques, écarts de demande, autorité et conversion.", status: "Intelligence" },
      { label: "Prioriser", detail: "Pertinence, demande, dépendance, effort et confiance.", status: "Décision" },
      { label: "Construire", detail: "Pages, correctifs, actifs d'autorité et mesure.", status: "Exécution" },
      { label: "Mesurer", detail: "Visibilité, couverture, santé, préparation et confiance reporting.", status: "Apprentissage" },
      { label: "Apprendre", detail: "Ajuster le cycle suivant selon les preuves et limites.", status: "Itération" },
    ],
    prioritization: [
      { label: "Pertinence business", detail: "L'action soutient-elle un acheteur ou marché utile ?", status: "Requis" },
      { label: "Demande search", detail: "Existe-t-il un signal de demande qualifiée ?", status: "Requis" },
      { label: "Dépendance technique", detail: "Un autre correctif doit-il précéder ?", status: "Séquencé" },
      { label: "Besoin d'autorité", detail: "Le sujet exige-t-il preuves, liens ou expertise ?", status: "Évalué" },
      { label: "Impact conversion", detail: "L'action améliore-t-elle le parcours sans claim inventé ?", status: "Qualifié" },
      { label: "Confiance de mesure", detail: "La performance future sera-t-elle lisible ?", status: "Qualifié" },
    ],
    execution: [
      { label: "Voie technique", detail: "Crawl, indexation, performance, schema, gabarits et migrations.", status: "Prêt" },
      { label: "Voie contenu", detail: "Briefs, pages, refresh, liens internes et réponses.", status: "Prêt" },
      { label: "Voie autorité", detail: "Preuves, RP numériques, citations et sources.", status: "Prêt" },
      { label: "Voie mesure", detail: "Tableaux, sources, baselines et revues.", status: "Prêt" },
    ],
    measurement: [
      { label: "Visibilité non-marque", detail: "Lue avec intention et contexte marché.", status: "Contextuel" },
      { label: "Santé technique", detail: "Signal opérationnel de crawl et rendu.", status: "Opérationnel" },
      { label: "Couverture contenu", detail: "Complétude thématique et parcours acheteur.", status: "Stratégique" },
      { label: "Préparation IA", detail: "Clarté d'entité et sources de citation.", status: "Qualifié" },
    ],
    governance: [
      { label: "Registre décisionnel", detail: "Pourquoi les priorités ont été choisies.", status: "Documenté" },
      { label: "Responsables", detail: "Qui agit et ce dont il a besoin.", status: "Assigné" },
      { label: "Cadence de revue", detail: "Quand les preuves changent les priorités.", status: "Planifié" },
      { label: "Règles de divulgation", detail: "Public, privé ou retenu.", status: "Contrôlé" },
    ],
    serviceMapping: [
      { label: "Stratégie SEO", detail: "Pilote le modèle opératoire.", status: "Cœur" },
      { label: "SEO technique", detail: "Traite les contraintes d'accès search.", status: "Fondation" },
      { label: "Marketing de contenu", detail: "Construit autour de la demande et l'autorité.", status: "Croissance" },
      { label: "Gestion PPC", detail: "Connecte les apprentissages paid aux décisions organiques.", status: "Connecté" },
    ],
    industryMapping: [
      { label: "Voyage", detail: "Architecture marché, destination et saisonnalité.", status: "Adapté" },
      { label: "Éducation", detail: "Programmes, confiance et décisions d'admission.", status: "Adapté" },
      { label: "Santé", detail: "Confiance locale et contenu prudent.", status: "Adapté" },
      { label: "SaaS et e-commerce", detail: "Architecture produit, catégorie et parcours d'achat.", status: "Adapté" },
    ],
    cta: {
      title: "Utiliser le cadre pour choisir la prochaine action.",
      description: "Un audit Taskcover transforme le modèle en priorités pour votre marché, votre site et vos contraintes.",
    },
  },
  clientResults: {
    registryIntro: "Les résultats publics exigent un contexte de mesure. Une métrique sans baseline, source, période et méthode peut induire en erreur.",
    requirements: [
      { label: "Preuve vérifiée", detail: "La source est contrôlable et approuvée.", status: "Requis" },
      { label: "Permission publique", detail: "Le client approuve la divulgation.", status: "Requis" },
      { label: "Baseline et période", detail: "Le point de départ et la fenêtre sont clairs.", status: "Requis" },
      { label: "Méthodologie pertinente", detail: "Le travail derrière le résultat est documenté.", status: "Requis" },
      { label: "Formulation approuvée", detail: "La revendication est relue et mesurée.", status: "Requis" },
    ],
    metricContext: [
      { label: "Demande organique qualifiée", detail: "La qualité prime sur la visibilité brute.", status: "Contexte" },
      { label: "Visibilité non-marque", detail: "Séparée de la demande marque quand possible.", status: "Contexte" },
      { label: "Santé technique", detail: "Interprétée comme signal opérationnel.", status: "Contexte" },
      { label: "Couverture contenu", detail: "Lue avec thèmes et parcours acheteur.", status: "Contexte" },
      { label: "Préparation IA", detail: "Évaluée comme préparation, pas comme claim plateforme.", status: "Contexte" },
      { label: "Qualité des leads", detail: "Seulement avec sources et limites approuvées.", status: "Contexte" },
    ],
    attribution: [
      "La performance search peut dépendre de la demande marché, saisonnalité, marque, plateformes, paid media, produit et releases.",
      "Taskcover ne publie pas de métrique isolée sans source, baseline, période, méthode et limites.",
      "Les preuves confidentielles restent privées même si elles soutiennent la décision interne.",
    ],
    confidential: [
      { label: "Identité non exposée", detail: "Noms, domaines, captures et URLs sont retenus.", status: "Protégé" },
      { label: "Métriques non exposées", detail: "Les métriques privées ne deviennent pas des claims anonymes.", status: "Protégé" },
      { label: "Pas d'approbation implicite", detail: "Le travail privé n'est pas une preuve publique.", status: "Protégé" },
    ],
    methodology: [
      { label: "Audit", detail: "La preuve informe ce qu'il faut changer.", status: "Entrée" },
      { label: "Roadmap", detail: "Les priorités séquencent le travail.", status: "Plan" },
      { label: "Implémentation", detail: "Les changements passent par les contraintes réelles.", status: "Action" },
      { label: "Revue de mesure", detail: "Les résultats se lisent avec contexte et limites.", status: "Apprentissage" },
    ],
    cta: {
      title: "Mesurer le travail avant de publier le résultat.",
      description: "Taskcover peut définir un cadre de mesure propre pour le reporting search futur.",
    },
  },
  samples,
  caseStudyDetails,
};
