import { localizePath, type Locale } from "@/lib/i18n";

export type SeoIntentRole =
  | "primary commercial intent"
  | "secondary commercial intent"
  | "informational support"
  | "proof/support page"
  | "lead conversion page"
  | "legal/trust page";

export type SeoFunnelStage =
  | "awareness"
  | "consideration"
  | "decision"
  | "conversion"
  | "trust";

export type SeoRecommendation =
  | "keep"
  | "improve"
  | "noindex"
  | "future page"
  | "avoid creating";

export type CommercialUrlIntent = {
  route: string;
  localeAvailability: readonly Locale[];
  indexable: boolean;
  pageType: string;
  primaryIntent: SeoIntentRole;
  funnelStage: SeoFunnelStage;
  primaryKeywordFamily: string;
  secondaryKeywordFamilies: readonly string[];
  commercialStrength: "low" | "medium" | "high";
  semReadiness: "ready" | "needs improvement" | "not ready";
  canonicalStatus: "localized canonical";
  hreflangStatus: "en/fr/es/x-default";
  internalLinkStatus: "strong" | "adequate" | "needs improvement";
  cannibalizationRisk: "low" | "medium" | "high";
  recommendation: SeoRecommendation;
};

export type KeywordFamilyMapEntry = {
  family: string;
  primaryUrl: string;
  supportingUrls: readonly string[];
  proofUrls: readonly string[];
  leadFunnelUrl: "/free-seo-audit" | "/book-a-call" | "/contact";
  relatedInsightUrls: readonly string[];
  notes: string;
  riskLevel: "low" | "medium" | "high";
};

export const commercialUrlIntentMap = [
  {
    route: "/",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "homepage",
    primaryIntent: "primary commercial intent",
    funnelStage: "consideration",
    primaryKeywordFamily: "search growth agency",
    secondaryKeywordFamilies: ["SEO agency", "AI search optimization", "SEO services"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "improve",
  },
  {
    route: "/services",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "services hub",
    primaryIntent: "primary commercial intent",
    funnelStage: "consideration",
    primaryKeywordFamily: "SEO services",
    secondaryKeywordFamilies: ["SEO agency", "technical SEO", "PPC management"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "improve",
  },
  {
    route: "/services/seo-agency",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "SEO agency",
    secondaryKeywordFamilies: ["SEO strategy", "search growth agency", "SEO consulting"],
    commercialStrength: "high",
    semReadiness: "ready",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/services/seo-audit",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "conversion",
    primaryKeywordFamily: "SEO audit",
    secondaryKeywordFamilies: ["SEO audit services", "technical SEO audit"],
    commercialStrength: "high",
    semReadiness: "ready",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/services/technical-seo",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "technical SEO",
    secondaryKeywordFamilies: ["technical SEO agency", "technical SEO audit"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/services/ai-search-optimization",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "AI search optimization",
    secondaryKeywordFamilies: ["GEO / generative engine optimization", "AI search agency"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/services/content-marketing",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "content marketing",
    secondaryKeywordFamilies: ["content authority", "SEO content marketing"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "low",
    recommendation: "keep",
  },
  {
    route: "/services/digital-pr-link-building",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "digital authority / digital PR",
    secondaryKeywordFamilies: ["link building", "authority building"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "adequate",
    cannibalizationRisk: "low",
    recommendation: "improve",
  },
  {
    route: "/services/local-seo",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "local SEO",
    secondaryKeywordFamilies: ["multi-location SEO", "franchise SEO"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "adequate",
    cannibalizationRisk: "medium",
    recommendation: "improve",
  },
  {
    route: "/services/international-seo",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "international SEO",
    secondaryKeywordFamilies: ["multilingual SEO", "English/French/Spanish SEO support"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/services/ppc-management",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "PPC management",
    secondaryKeywordFamilies: ["paid search management", "PPC and SEO strategy"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "adequate",
    cannibalizationRisk: "medium",
    recommendation: "improve",
  },
  {
    route: "/services/seo-mentor-service",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "service detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "SEO mentor",
    secondaryKeywordFamilies: ["SEO training / SEO advisory", "SEO consultant"],
    commercialStrength: "medium",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "adequate",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/industries",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "industries hub",
    primaryIntent: "secondary commercial intent",
    funnelStage: "consideration",
    primaryKeywordFamily: "industry-specific SEO agency",
    secondaryKeywordFamilies: ["travel SEO", "education SEO", "SaaS SEO"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "low",
    recommendation: "keep",
  },
  {
    route: "/industries/[slug]",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "industry detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "industry SEO",
    secondaryKeywordFamilies: ["travel SEO", "healthcare SEO", "legal SEO", "SaaS SEO"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "low",
    recommendation: "keep",
  },
  {
    route: "/markets/[slug]",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "market detail",
    primaryIntent: "primary commercial intent",
    funnelStage: "decision",
    primaryKeywordFamily: "market-specific SEO agency",
    secondaryKeywordFamilies: ["SEO agency USA", "SEO agency Canada", "SEO agency Australia"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/work/case-studies",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "case-study hub",
    primaryIntent: "proof/support page",
    funnelStage: "decision",
    primaryKeywordFamily: "SEO case studies",
    secondaryKeywordFamilies: ["SEO results", "SEO proof"],
    commercialStrength: "medium",
    semReadiness: "not ready",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "low",
    recommendation: "keep",
  },
  {
    route: "/work/sample-audits",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "sample audit hub",
    primaryIntent: "proof/support page",
    funnelStage: "decision",
    primaryKeywordFamily: "SEO sample audit",
    secondaryKeywordFamilies: ["technical SEO audit example", "AI search audit example"],
    commercialStrength: "medium",
    semReadiness: "not ready",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "low",
    recommendation: "keep",
  },
  {
    route: "/insights/[categorySlug]/[articleSlug]",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "insight article",
    primaryIntent: "informational support",
    funnelStage: "awareness",
    primaryKeywordFamily: "informational SEO support",
    secondaryKeywordFamilies: ["technical SEO checklist", "AI search measurement", "SEO vs PPC"],
    commercialStrength: "medium",
    semReadiness: "not ready",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
  {
    route: "/free-seo-audit",
    localeAvailability: ["en", "fr", "es"],
    indexable: true,
    pageType: "lead funnel",
    primaryIntent: "lead conversion page",
    funnelStage: "conversion",
    primaryKeywordFamily: "free SEO audit",
    secondaryKeywordFamilies: ["SEO audit", "SEO consultation"],
    commercialStrength: "high",
    semReadiness: "needs improvement",
    canonicalStatus: "localized canonical",
    hreflangStatus: "en/fr/es/x-default",
    internalLinkStatus: "strong",
    cannibalizationRisk: "medium",
    recommendation: "keep",
  },
] as const satisfies readonly CommercialUrlIntent[];

export const keywordFamilyMap = [
  {
    family: "SEO agency",
    primaryUrl: "/services/seo-agency",
    supportingUrls: ["/services", "/", "/methodology"],
    proofUrls: ["/work/case-studies", "/work/sample-audits/90-day-search-growth-roadmap"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/seo-guides/seo-2026-google-ai-search-revenue-growth"],
    notes: "Use the canonical service page, not a duplicate root-level /seo-agency page.",
    riskLevel: "medium",
  },
  {
    family: "search growth agency",
    primaryUrl: "/",
    supportingUrls: ["/services/seo-agency", "/methodology", "/work/search-growth-frameworks"],
    proofUrls: ["/work/case-studies", "/proof"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/seo-guides/seo-2026-google-ai-search-revenue-growth"],
    notes: "Homepage can own the broader brand/search-growth positioning; service page owns SEO agency.",
    riskLevel: "medium",
  },
  {
    family: "SEO services",
    primaryUrl: "/services",
    supportingUrls: ["/services/seo-agency", "/services/technical-seo", "/services/content-marketing"],
    proofUrls: ["/work/sample-audits", "/work/case-studies"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/seo-guides/seo-2026-google-ai-search-revenue-growth"],
    notes: "Hub intent is service selection, not a second broad agency page.",
    riskLevel: "medium",
  },
  {
    family: "SEO consultant",
    primaryUrl: "/services/seo-mentor-service",
    supportingUrls: ["/services/seo-agency", "/methodology"],
    proofUrls: ["/work/search-growth-frameworks"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/seo-mentor"],
    notes: "Mentor/advisory page is the closest existing fit; avoid a thin consultant clone.",
    riskLevel: "medium",
  },
  {
    family: "SEO consulting",
    primaryUrl: "/services/seo-agency",
    supportingUrls: ["/services/seo-mentor-service", "/methodology", "/how-we-work"],
    proofUrls: ["/work/case-studies"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/seo-guides/seo-2026-google-ai-search-revenue-growth"],
    notes: "Keep consulting mapped to strategy unless a future advisory page has distinct content.",
    riskLevel: "medium",
  },
  {
    family: "SEO strategy",
    primaryUrl: "/services/seo-agency",
    supportingUrls: ["/methodology", "/work/search-growth-frameworks"],
    proofUrls: ["/work/case-studies", "/work/sample-audits/90-day-search-growth-roadmap"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/seo-guides/seo-2026-google-ai-search-revenue-growth"],
    notes: "Existing service page title and H1 already target strategy and search-growth system intent.",
    riskLevel: "low",
  },
  {
    family: "SEO audit",
    primaryUrl: "/services/seo-audit",
    supportingUrls: ["/free-seo-audit", "/work/sample-audits", "/services/technical-seo"],
    proofUrls: ["/work/sample-audits/technical-seo-audit", "/work/sample-audits/90-day-search-growth-roadmap"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/technical-seo/technical-seo-audit-checklist-growing-websites"],
    notes: "Service page owns commercial audit intent; free audit funnel converts it.",
    riskLevel: "medium",
  },
  {
    family: "technical SEO",
    primaryUrl: "/services/technical-seo",
    supportingUrls: ["/services/seo-audit", "/industries/saas-seo", "/industries/ecommerce-seo"],
    proofUrls: ["/work/sample-audits/technical-seo-audit"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/technical-seo/technical-seo-audit-checklist-growing-websites"],
    notes: "Article remains informational support; service page owns commercial intent.",
    riskLevel: "medium",
  },
  {
    family: "AI search optimization",
    primaryUrl: "/services/ai-search-optimization",
    supportingUrls: ["/services/content-marketing", "/services/digital-pr-link-building"],
    proofUrls: ["/work/sample-audits/ai-search-visibility-review"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/ai-search/measure-ai-search-visibility"],
    notes: "AI Search/GEO intent is consolidated on the existing AI service page.",
    riskLevel: "medium",
  },
  {
    family: "GEO / generative engine optimization",
    primaryUrl: "/services/ai-search-optimization",
    supportingUrls: ["/services/content-marketing", "/proof/spokesperson"],
    proofUrls: ["/work/sample-audits/ai-search-visibility-review"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/ai-search/measure-ai-search-visibility"],
    notes: "Do not create a separate GEO page until there is distinct terminology demand and content depth.",
    riskLevel: "medium",
  },
  {
    family: "content marketing",
    primaryUrl: "/services/content-marketing",
    supportingUrls: ["/services/digital-pr-link-building", "/services/ai-search-optimization"],
    proofUrls: ["/work/sample-audits/content-gap-map"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/content-authority/content-rankings-citations-leads"],
    notes: "Service page owns commercial intent; content-authority article supports it.",
    riskLevel: "low",
  },
  {
    family: "digital authority / digital PR",
    primaryUrl: "/services/digital-pr-link-building",
    supportingUrls: ["/proof/media-features", "/proof/spokesperson"],
    proofUrls: ["/proof/brand-experience", "/work/case-studies"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/content-authority/content-rankings-citations-leads"],
    notes: "Avoid a separate digital PR page that duplicates authority-building service intent.",
    riskLevel: "low",
  },
  {
    family: "local SEO",
    primaryUrl: "/services/local-seo",
    supportingUrls: ["/industries/franchise-local-seo", "/markets/usa-seo-agency", "/markets/australia-seo-agency"],
    proofUrls: ["/work/sample-audits/local-seo-audit", "/work/case-studies/casa-madera", "/work/case-studies/avis"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/local-international-seo/international-seo-usa-canada-australia"],
    notes: "Local SEO service owns method; franchise industry owns vertical application.",
    riskLevel: "medium",
  },
  {
    family: "international SEO",
    primaryUrl: "/services/international-seo",
    supportingUrls: ["/markets/usa-seo-agency", "/markets/canada-seo-agency", "/markets/australia-seo-agency"],
    proofUrls: ["/work/sample-audits/international-seo-market-map"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/local-international-seo/international-seo-usa-canada-australia"],
    notes: "Market pages support regional intent; the service page owns international SEO.",
    riskLevel: "medium",
  },
  {
    family: "PPC management",
    primaryUrl: "/services/ppc-management",
    supportingUrls: ["/markets/usa-seo-agency", "/markets/australia-seo-agency"],
    proofUrls: ["/work/sample-audits/ppc-organic-intelligence"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/ppc-search-intelligence/seo-vs-ppc-search-growth-system"],
    notes: "PPC service owns commercial paid search intent; article supports strategy education.",
    riskLevel: "medium",
  },
  {
    family: "travel SEO",
    primaryUrl: "/industries/travel-seo",
    supportingUrls: ["/services/international-seo", "/services/local-seo", "/markets/australia-seo-agency"],
    proofUrls: ["/work/case-studies/agoda", "/work/case-studies/the-bamboo-bar"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/local-international-seo/international-seo-usa-canada-australia"],
    notes: "Industry page is already distinct from service pages.",
    riskLevel: "low",
  },
  {
    family: "education SEO",
    primaryUrl: "/industries/education-seo",
    supportingUrls: ["/services/content-marketing", "/services/international-seo", "/markets/canada-seo-agency"],
    proofUrls: ["/work/case-studies/british-university-vietnam"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/local-international-seo/international-seo-usa-canada-australia"],
    notes: "Education page has trust-led vertical depth and proof support.",
    riskLevel: "low",
  },
  {
    family: "healthcare SEO",
    primaryUrl: "/industries/healthcare-seo",
    supportingUrls: ["/services/local-seo", "/services/content-marketing"],
    proofUrls: ["/work/case-studies/fwd-insurance"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: [],
    notes: "Healthcare and wellness should stay consolidated until proof depth increases.",
    riskLevel: "low",
  },
  {
    family: "legal SEO",
    primaryUrl: "/industries/legal-immigration-seo",
    supportingUrls: ["/services/local-seo", "/services/content-marketing", "/markets/canada-seo-agency"],
    proofUrls: ["/work/case-studies/matthew-jeffery-law-firm"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: [],
    notes: "Legal and immigration share one high-trust vertical page to avoid thin split pages.",
    riskLevel: "low",
  },
  {
    family: "SaaS SEO",
    primaryUrl: "/industries/saas-seo",
    supportingUrls: ["/services/technical-seo", "/services/content-marketing", "/services/international-seo"],
    proofUrls: ["/work/case-studies/ccleaner", "/work/sample-audits/technical-seo-audit"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/seo-guides/seo-2026-google-ai-search-revenue-growth"],
    notes: "SaaS page owns vertical intent; technical SEO remains supporting service.",
    riskLevel: "low",
  },
  {
    family: "eCommerce SEO",
    primaryUrl: "/industries/ecommerce-seo",
    supportingUrls: ["/services/ecommerce-seo", "/services/technical-seo"],
    proofUrls: ["/work/case-studies/skatepro", "/work/sample-audits/ecommerce-search-architecture"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: [],
    notes: "Industry and service overlap is intentional: industry page for vertical, service page for capability.",
    riskLevel: "medium",
  },
  {
    family: "franchise SEO",
    primaryUrl: "/industries/franchise-local-seo",
    supportingUrls: ["/services/local-seo", "/markets/usa-seo-agency"],
    proofUrls: ["/work/case-studies/avis", "/work/sample-audits/local-seo-audit"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: [],
    notes: "Do not build city pages; franchise page should explain scale without doorway behavior.",
    riskLevel: "low",
  },
  {
    family: "SEO agency USA",
    primaryUrl: "/markets/usa-seo-agency",
    supportingUrls: ["/services/seo-agency", "/services/local-seo", "/services/ppc-management"],
    proofUrls: ["/work/case-studies/casa-madera"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/local-international-seo/international-seo-usa-canada-australia"],
    notes: "Market page is distinct and should not be replaced with city/location pages.",
    riskLevel: "medium",
  },
  {
    family: "SEO agency Canada",
    primaryUrl: "/markets/canada-seo-agency",
    supportingUrls: ["/services/international-seo", "/industries/legal-immigration-seo", "/industries/education-seo"],
    proofUrls: ["/work/case-studies/matthew-jeffery-law-firm", "/work/case-studies/avis"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/local-international-seo/international-seo-usa-canada-australia"],
    notes: "Canada page owns bilingual/provincial market intent.",
    riskLevel: "medium",
  },
  {
    family: "SEO agency Australia",
    primaryUrl: "/markets/australia-seo-agency",
    supportingUrls: ["/services/seo-agency", "/services/local-seo", "/services/ppc-management"],
    proofUrls: ["/work/case-studies/the-bamboo-bar", "/work/case-studies/skatepro"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: ["/insights/local-international-seo/international-seo-usa-canada-australia"],
    notes: "Australia page owns market intent without claiming physical local presence.",
    riskLevel: "medium",
  },
  {
    family: "SEO case studies",
    primaryUrl: "/work/case-studies",
    supportingUrls: ["/work", "/proof"],
    proofUrls: ["/work/case-studies/british-university-vietnam", "/work/case-studies/avis"],
    leadFunnelUrl: "/book-a-call",
    relatedInsightUrls: [],
    notes: "Proof page supports commercial pages; it should not compete as an agency sales page.",
    riskLevel: "low",
  },
  {
    family: "SEO sample audit",
    primaryUrl: "/work/sample-audits",
    supportingUrls: ["/services/seo-audit", "/free-seo-audit"],
    proofUrls: ["/work/sample-audits/technical-seo-audit", "/work/sample-audits/ai-search-visibility-review"],
    leadFunnelUrl: "/free-seo-audit",
    relatedInsightUrls: ["/insights/technical-seo/technical-seo-audit-checklist-growing-websites"],
    notes: "Sample audit hub is proof/support; SEO audit service remains commercial.",
    riskLevel: "medium",
  },
] as const satisfies readonly KeywordFamilyMapEntry[];

export const noindexCommercialExclusions = [
  "/admin",
  "/admin/insights/[id]/preview",
  "/thank-you",
] as const;

export function localizedCommercialRoute(path: string, locale: Locale): string {
  return localizePath(path, locale);
}
