import { buildInsightArticle } from "../insights.helpers";
import { getSharedSources } from "../insights.registry";
import type { InsightsContent } from "../insights.types";

const ctaAudit = { label: "Solicitar auditoria SEO gratuita", href: "/free-seo-audit" };
const ctaCall = { label: "Reservar llamada estrategica", href: "/book-a-call" };

export const insights: InsightsContent = {
  ui: {
    insights: "Analisis",
    home: "Inicio",
    allCategories: "Todas las categorias",
    featured: "Dossier destacado",
    latest: "Ultimos analisis",
    readArticle: "Leer articulo",
    readMore: "Leer mas",
    searchPlaceholder: "Buscar por tema, servicio o palabra clave",
    filterByCategory: "Categoria",
    filterByTopic: "Tema",
    filterByService: "Servicio",
    noResults: "No hay analisis publicados que coincidan con esos filtros.",
    minutes: "min de lectura",
    published: "Publicado",
    updated: "Actualizado",
    tableOfContents: "Tabla de contenidos",
    executiveSummary: "Resumen ejecutivo",
    keyTakeaways: "Puntos clave",
    sources: "Fuentes y referencias",
    relatedServices: "Servicios relacionados",
    relatedSample: "Muestra relacionada",
    relatedArticles: "Articulos relacionados",
    startFreeAudit: "Iniciar auditoria gratuita",
    author: "Autor",
    finalCta: "Siguiente paso",
    categoryContext: "Contexto de la categoria",
    topicCluster: "Mapa del cluster",
    recommendedPaths: "Rutas de lectura recomendadas",
    sourceLabel: "Fuente",
    accessed: "Consultado",
    evidence: "Evidencia",
    searchGrowthMap: "Mapa de crecimiento search",
  },
  hub: {
    eyebrow: "Analisis Taskcover",
    h1: "Pensamiento de crecimiento search para Google, busqueda con IA e ingresos.",
    description:
      "Biblioteca editorial multilingue sobre estrategia SEO, fundamentos tecnicos, autoridad de contenido, visibilidad en IA, inteligencia PPC y SEO internacional.",
    featuredTitle: "Empieza con el dossier de search 2026",
    topicMapTitle: "Un mapa de crecimiento search, no un archivo generico de blog",
    topicMapDescription:
      "La biblioteca se organiza por decisiones comerciales: fundamentos, autoridad, visibilidad en respuestas IA, inteligencia paid-organic, expansion de mercado y capacitacion.",
    pathsTitle: "Rutas de lectura recomendadas",
    paths: [
      {
        title: "Para fundadores y lideres de marketing",
        body: "Empieza con el panorama search 2026 y despues conecta SEO y PPC en un solo modelo.",
        href: "/insights/seo-guides/seo-2026-google-ai-search-revenue-growth",
      },
      {
        title: "Para equipos tecnicos y de producto",
        body: "Usa la checklist de auditoria tecnica antes de migraciones, lanzamientos y despliegues internacionales.",
        href: "/insights/technical-seo/technical-seo-audit-checklist-growing-websites",
      },
      {
        title: "Para contenido y autoridad",
        body: "Crea activos que respondan a la intencion, merezcan citas y conecten con una accion clara.",
        href: "/insights/content-authority/content-rankings-citations-leads",
      },
    ],
    cta: {
      title: "Convierte la lectura en un plan de crecimiento search.",
      body: "Usa la auditoria gratuita o una llamada estrategica para aplicar estos marcos a tu sitio, mercados y objetivos.",
      primary: ctaAudit,
      secondary: ctaCall,
    },
  },
  author: {
    name: "Taskcover Editorial Team",
    description:
      "Taskcover Editorial Team publica guias practicas sobre SEO, busqueda con IA, autoridad de contenido, inteligencia paid search y estrategia de crecimiento search.",
  },
  categories: {
    "seo-guides": {
      slug: "seo-guides",
      label: "Guias SEO",
      eyebrow: "Guias estrategicas",
      h1: "Guias SEO para crecimiento search",
      description: "Marcos para priorizar SEO, Google organico, respuestas IA, autoridad y resultados comerciales.",
      context: "Esta categoria ayuda a decidir que debe producir el SEO, como se conecta con ingresos y que priorizar primero.",
      visualVariant: "guide",
      relatedServices: [{ label: "Agencia SEO", href: "/services/seo-agency" }, { label: "Auditoria SEO", href: "/services/seo-audit" }],
      relatedIndustries: [{ label: "SEO para SaaS", href: "/industries/saas-seo" }],
      relatedMarkets: [{ label: "Agencia SEO USA", href: "/markets/usa-seo-agency" }],
      curatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth"],
      cta: { title: "Necesitas una hoja de ruta search?", body: "Empieza con un diagnostico antes de elegir tacticas.", primary: ctaAudit },
    },
    "ai-search": {
      slug: "ai-search",
      label: "Busqueda IA & GEO",
      eyebrow: "Visibilidad en respuestas",
      h1: "Busqueda con IA y GEO",
      description: "Medicion de menciones de marca, citas, entidades y fuentes en experiencias de respuesta con IA.",
      context: "La medicion de IA sirve como inteligencia direccional, no como atribucion perfecta.",
      visualVariant: "ai",
      relatedServices: [{ label: "Optimizacion para busqueda IA", href: "/services/ai-search-optimization" }, { label: "Marketing de contenidos", href: "/services/content-marketing" }],
      relatedIndustries: [{ label: "SEO para Educacion", href: "/industries/education-seo" }],
      relatedMarkets: [{ label: "Agencia SEO Canada", href: "/markets/canada-seo-agency" }],
      curatedArticleSlugs: ["measure-ai-search-visibility"],
      cta: { title: "Mapea tus brechas de IA.", body: "Revisa entidades, fuentes y cobertura antes de perseguir tacticas.", primary: ctaCall },
    },
    "technical-seo": {
      slug: "technical-seo",
      label: "SEO tecnico",
      eyebrow: "Crawl, render, indice",
      h1: "Sistemas de SEO tecnico",
      description: "Auditorias de rastreo, indexacion, arquitectura, canonicals, rendimiento, datos estructurados, internacional y migraciones.",
      context: "El SEO tecnico debe reducir riesgo search y desbloquear rendimiento, no crear una lista infinita de alertas.",
      visualVariant: "technical",
      relatedServices: [{ label: "SEO tecnico", href: "/services/technical-seo" }, { label: "Auditoria SEO", href: "/services/seo-audit" }],
      relatedIndustries: [{ label: "SEO para e-commerce", href: "/industries/ecommerce-seo" }],
      relatedMarkets: [{ label: "Agencia SEO Australia", href: "/markets/australia-seo-agency" }],
      curatedArticleSlugs: ["technical-seo-audit-checklist-growing-websites"],
      cta: { title: "Audita la base tecnica.", body: "Usa una estructura de auditoria antes de invertir tiempo de ingenieria.", primary: { label: "Ver auditorias de muestra", href: "/work/sample-audits" } },
    },
    "content-authority": {
      slug: "content-authority",
      label: "Contenido & Autoridad digital",
      eyebrow: "Sistemas de autoridad",
      h1: "Contenido y autoridad digital",
      description: "Guias para contenido util, evidencia, enlaces internos, activos de PR digital y rutas de conversion.",
      context: "La autoridad nace de cobertura util, evidencia creible, entidades claras y caminos que ayudan a actuar.",
      visualVariant: "authority",
      relatedServices: [{ label: "Marketing de contenidos", href: "/services/content-marketing" }, { label: "PR digital y link building", href: "/services/digital-pr-link-building" }],
      relatedIndustries: [{ label: "SEO para Viajes", href: "/industries/travel-seo" }],
      relatedMarkets: [{ label: "Agencia SEO USA", href: "/markets/usa-seo-agency" }],
      curatedArticleSlugs: ["content-rankings-citations-leads"],
      cta: { title: "Construye autoridad con evidencia.", body: "Prioriza activos que puedan ganar rankings, citas, enlaces y leads calificados.", primary: ctaCall },
    },
    "local-international-seo": {
      slug: "local-international-seo",
      label: "SEO local & internacional",
      eyebrow: "Mercados y localizacion",
      h1: "SEO local e internacional",
      description: "Arquitectura de mercado, localizacion, autoridad local, hreflang y secuencia de despliegue multi-region.",
      context: "El SEO internacional funciona cuando estrategia, arquitectura, localizacion y autoridad se refuerzan.",
      visualVariant: "international",
      relatedServices: [{ label: "SEO internacional", href: "/services/international-seo" }, { label: "SEO local", href: "/services/local-seo" }],
      relatedIndustries: [{ label: "SEO para Viajes", href: "/industries/travel-seo" }, { label: "SEO para Educacion", href: "/industries/education-seo" }],
      relatedMarkets: [{ label: "Agencia SEO USA", href: "/markets/usa-seo-agency" }, { label: "Agencia SEO Canada", href: "/markets/canada-seo-agency" }, { label: "Agencia SEO Australia", href: "/markets/australia-seo-agency" }],
      curatedArticleSlugs: ["international-seo-usa-canada-australia"],
      cta: { title: "Planifica antes de traducir.", body: "Mapea mercados, idiomas y brechas de autoridad primero.", primary: ctaCall },
    },
    "ppc-search-intelligence": {
      slug: "ppc-search-intelligence",
      label: "PPC & Inteligencia search",
      eyebrow: "Paid y organico",
      h1: "PPC e inteligencia search",
      description: "Usar datos paid y organicos juntos sin afirmar que cada canal sirve en todos los casos.",
      context: "Paid search prueba y captura rapido; SEO compone cuando consulta, contenido y base lo justifican.",
      visualVariant: "ppc",
      relatedServices: [{ label: "Gestion PPC", href: "/services/ppc-management" }, { label: "Agencia SEO", href: "/services/seo-agency" }],
      relatedIndustries: [{ label: "SEO para franquicias y local", href: "/industries/franchise-local-seo" }],
      relatedMarkets: [{ label: "Agencia SEO USA", href: "/markets/usa-seo-agency" }],
      curatedArticleSlugs: ["seo-vs-ppc-search-growth-system"],
      cta: { title: "Une paid y organico.", body: "Usa consultas, landing pages y economia de conversion en conjunto.", primary: ctaCall },
    },
    "seo-mentor": {
      slug: "seo-mentor",
      label: "SEO Mentor",
      eyebrow: "Asesoria y aprendizaje",
      h1: "Hub SEO Mentor",
      description: "Contenido asesor para mejorar criterio SEO, habitos de revision y priorizacion.",
      context: "Esta categoria prepara futuros posts de mentorias y cura guias utiles de otros clusters.",
      visualVariant: "mentor",
      relatedServices: [{ label: "Servicio SEO Mentor", href: "/services/seo-mentor-service" }],
      relatedIndustries: [{ label: "SEO para SaaS", href: "/industries/saas-seo" }],
      relatedMarkets: [{ label: "Agencia SEO Canada", href: "/markets/canada-seo-agency" }],
      curatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "technical-seo-audit-checklist-growing-websites", "measure-ai-search-visibility", "content-rankings-citations-leads", "seo-vs-ppc-search-growth-system"],
      cta: { title: "Fortalece el criterio SEO interno.", body: "Usa mentorias para revisar estrategia, roadmaps y calidad de ejecucion.", primary: { label: "Explorar SEO Mentor", href: "/services/seo-mentor-service" } },
    },
  },
  articles: [
    buildInsightArticle({
      id: "insight-es-seo-2026",
      slug: "seo-2026-google-ai-search-revenue-growth",
      translationGroupId: "seo-2026",
      locale: "es",
      title: "SEO en 2026: Google, busqueda con IA y crecimiento de ingresos",
      excerpt: "Un modelo operativo para proteger visibilidad en Google, preparar respuestas IA, fortalecer autoridad y conectar SEO con ingresos.",
      category: "seo-guides",
      tags: ["Estrategia SEO", "Busqueda IA", "Ingresos", "Entidades"],
      readingTime: 12,
      coverImageAlt: "Dashboard search que conecta Google, busqueda IA, autoridad e ingresos.",
      coverImageCaption: "Un programa search debe conectar acceso tecnico, utilidad del contenido, autoridad y resultados comerciales.",
      focusKeyword: "SEO en 2026",
      secondaryKeywords: ["SEO busqueda IA", "crecimiento search", "estrategia Google organica"],
      intent: "Entender prioridades de SEO moderno.",
      audience: "Fundadores, CMOs, lideres SEO y equipos de ingresos",
      funnelStage: "consideration",
      coreQuestion: "Que debe priorizar una empresa cuando Google, respuestas IA e ingresos importan a la vez?",
      primaryEntity: "Optimizacion para motores de busqueda",
      supportingEntities: ["Google Search", "respuestas IA", "autoridad de contenido", "SEO tecnico", "medicion de conversion"],
      topicCluster: "Estrategia de crecimiento search",
      parentPillar: "Guias SEO",
      uniqueInformationGain: "Un marco de 90 dias que separa fundamentos, visibilidad, autoridad e instrumentacion de ingresos.",
      refreshTrigger: "Actualizar cuando cambien guias de Google, controles IA o arquitectura Taskcover.",
      sources: getSharedSources(["google-seo-starter", "google-helpful-content", "google-ai-features", "google-structured-data"]),
      claims: [{ id: "seo-no-guarantee", text: "Google no garantiza que los cambios SEO produzcan rankings inmediatos.", requiresEvidence: true, sourceIds: ["google-seo-starter"] }, { id: "people-first-content", text: "La guia de Google enfatiza contenido util, fiable y pensado para personas.", requiresEvidence: true, sourceIds: ["google-helpful-content"] }],
      originalInsights: ["Tratar la visibilidad IA como una capa adicional, no como sustituto de SEO.", "Instrumentar ingresos antes de escalar volumen de contenido."],
      serviceLinks: [{ label: "Agencia SEO", href: "/services/seo-agency" }, { label: "Optimizacion para busqueda IA", href: "/services/ai-search-optimization" }, { label: "Auditoria SEO", href: "/services/seo-audit" }],
      industryLinks: [{ label: "SEO para SaaS", href: "/industries/saas-seo" }],
      marketLinks: [{ label: "Agencia SEO USA", href: "/markets/usa-seo-agency" }, { label: "Agencia SEO Canada", href: "/markets/canada-seo-agency" }],
      caseStudyLinks: [{ label: "Marcos de crecimiento search", href: "/work/search-growth-frameworks" }],
      sampleAuditLinks: [{ label: "Roadmap search de 90 dias", href: "/work/sample-audits/90-day-search-growth-roadmap" }],
      relatedArticleSlugs: ["measure-ai-search-visibility", "seo-vs-ppc-search-growth-system", "content-rankings-citations-leads"],
      metaTitle: "SEO en 2026: Google, IA e ingresos",
      metaDescription: "Marco SEO 2026 para visibilidad en Google, busqueda IA, autoridad, medicion y crecimiento de ingresos.",
      breadcrumbLabel: "SEO en 2026",
      blocks: [
        { type: "direct-answer", title: "Respuesta directa", answer: "En 2026, SEO debe gestionarse como un sistema de crecimiento search: acceso tecnico, contenido util, claridad de entidades, autoridad, preparacion para respuestas IA y medicion de conversion." },
        { type: "key-takeaways", title: "Puntos clave", items: ["La visibilidad organica depende de paginas accesibles y utiles.", "La IA agrega una capa donde entidades, citas y fuentes importan.", "La medicion debe seguir demanda calificada, no solo rankings.", "El plan mas seguro corrige fundamentos antes de producir mas."] },
        { type: "heading", level: 2, text: "El panorama search es multicapa", id: "panorama-search" },
        { type: "paragraph", text: "Una empresa ya no compite solo por un enlace azul. Busca presencia en resultados organicos, elementos locales, respuestas IA, comparaciones y busquedas de marca." },
        { type: "paragraph", text: "El trabajo duradero sigue siendo claro: hacer el sitio accesible, explicar la oferta, publicar contenido que resuelva necesidades y facilitar el siguiente paso comercial." },
        { type: "evidence", claimId: "seo-no-guarantee", summary: "La guia de Google presenta SEO como mejoras para descubrimiento y comprension, sin promesas de ranking.", sourceIds: ["google-seo-starter"] },
        { type: "comparison-table", caption: "Modelo de prioridad SEO 2026.", columns: ["Capa", "Que revisar", "Pregunta de negocio"], rows: [["Fundamento tecnico", "Crawl, render, indice, canonicals, rendimiento", "Las paginas correctas son accesibles?"], ["Utilidad del contenido", "Intencion, profundidad, evidencia, enlaces internos", "La pagina ayuda mejor que alternativas?"], ["Entidad y autoridad", "Consistencia de marca, citas, activos PR", "La fuente es creible?"], ["Ingresos", "CTAs, formularios, analytics, calidad de lead", "La demanda puede convertirse en pipeline?"]] },
        { type: "heading", level: 2, text: "Preparacion para IA sin exagerar atribucion", id: "preparacion-ia" },
        { type: "paragraph", text: "Las superficies IA pueden citar, mencionar o resumir sin clic. La medicion direccional es util; prometer atribucion perfecta no lo es." },
        { type: "checklist", title: "Checklist de preparacion IA", items: [{ label: "Entidades claras", detail: "Usar informacion consistente de marca, servicios, mercados y autor." }, { label: "Secciones citables", detail: "Hacer definiciones, marcos y evidencias faciles de referenciar." }, { label: "Fuentes limpias", detail: "Citar fuentes primarias para afirmaciones factuales." }, { label: "Continuidad de conversion", detail: "Conectar guias con servicios, auditorias, casos y contacto." }] },
        { type: "steps", title: "Secuencia de 90 dias", steps: [{ title: "Dias 1-20: diagnosticar", body: "Auditar crawl, indexacion, plantillas, analitica y paginas con demanda actual." }, { title: "Dias 21-45: fortalecer", body: "Mejorar paginas prioritarias con respuestas, enlaces internos, schema y CTAs." }, { title: "Dias 46-70: crear autoridad", body: "Construir marcos, comparativas y guias con evidencia." }, { title: "Dias 71-90: revisar ingresos", body: "Comparar consultas, leads, conversiones asistidas y feedback comercial." }] },
        { type: "faq", items: [{ question: "La busqueda IA reemplaza al SEO?", answer: "No. Cambia como se descubre y mide la visibilidad, pero depende de fuentes accesibles, utiles y confiables." }, { question: "Aun conviene medir rankings?", answer: "Si, junto con cobertura de consultas, leads, conversiones asistidas, marca y menciones IA." }] },
        { type: "cta", title: "Necesitas un plan search de 90 dias?", body: "Empieza con una auditoria que separe riesgo tecnico, oportunidad de contenido, preparacion IA y medicion de ingresos.", primary: ctaAudit, secondary: ctaCall },
      ],
      faqItems: [{ question: "La busqueda IA reemplaza al SEO?", answer: "No. Cambia como se descubre y mide la visibilidad, pero depende de fuentes accesibles, utiles y confiables." }, { question: "Aun conviene medir rankings?", answer: "Si, junto con cobertura de consultas, leads, conversiones asistidas, marca y menciones IA." }],
    }),
    buildInsightArticle({
      id: "insight-es-ai-visibility",
      slug: "measure-ai-search-visibility",
      translationGroupId: "ai-visibility",
      locale: "es",
      title: "Como medir la visibilidad en la busqueda con IA",
      excerpt: "Un modelo honesto para medir cobertura de respuestas, menciones, citas, entidades, calidad de fuentes, competidores y limites.",
      category: "ai-search",
      tags: ["Visibilidad IA", "GEO", "Entidades", "Citas"],
      readingTime: 10,
      coverImageAlt: "Mapa de visibilidad IA con menciones, citas, fuentes y consultas.",
      coverImageCaption: "La medicion IA debe ser direccional, repetible y clara sobre sus limites.",
      focusKeyword: "medir visibilidad busqueda IA",
      secondaryKeywords: ["seguimiento visibilidad IA", "medicion GEO", "citas IA SEO"],
      intent: "Evaluar presencia en experiencias de respuesta IA.",
      audience: "Lideres SEO, contenido y marketing",
      funnelStage: "consideration",
      coreQuestion: "Como medir visibilidad IA sin fingir atribucion perfecta?",
      primaryEntity: "Visibilidad en busqueda con IA",
      supportingEntities: ["respuestas IA", "menciones de marca", "citas", "consistencia de entidad", "calidad de fuente"],
      topicCluster: "Busqueda IA & GEO",
      parentPillar: "Busqueda IA & GEO",
      uniqueInformationGain: "Un scorecard liviano que separa cobertura, citas, exactitud y limites.",
      refreshTrigger: "Actualizar cuando productos IA cambien fuentes, controles o comportamiento.",
      sources: getSharedSources(["google-ai-features", "google-helpful-content", "google-seo-starter"]),
      claims: [{ id: "ai-search-visibility", text: "Google documenta funciones IA como parte de Search y orienta a propietarios de sitios.", requiresEvidence: true, sourceIds: ["google-ai-features"] }],
      originalInsights: ["Separar presencia IA de rendimiento; la primera es inteligencia de visibilidad."],
      serviceLinks: [{ label: "Optimizacion para busqueda IA", href: "/services/ai-search-optimization" }, { label: "Marketing de contenidos", href: "/services/content-marketing" }],
      industryLinks: [{ label: "SEO para Educacion", href: "/industries/education-seo" }],
      sampleAuditLinks: [{ label: "Revision de visibilidad IA", href: "/work/sample-audits/ai-search-visibility-review" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "content-rankings-citations-leads", "technical-seo-audit-checklist-growing-websites"],
      metaTitle: "Como medir la visibilidad en busqueda con IA",
      metaDescription: "Marco para medir visibilidad IA: cobertura de respuestas, citas, menciones, entidades, calidad de fuentes y limites.",
      breadcrumbLabel: "Medir visibilidad IA",
      blocks: [
        { type: "direct-answer", title: "Respuesta directa", answer: "Mide la visibilidad IA con conjuntos de consultas repetibles, cobertura de respuestas, menciones de marca, citas, calidad de fuentes, exactitud de entidades y comparacion competitiva. Tratalo como inteligencia direccional." },
        { type: "key-takeaways", title: "Puntos clave", items: ["No es un unico ranking.", "Agrupa consultas por intencion, mercado y tema.", "Menciones y citas se miden por separado.", "La revision humana sigue siendo necesaria."] },
        { type: "paragraph", text: "La visibilidad puede significar ser citado, mencionado, resumido o estar ausente mientras competidores aparecen. Un score opaco mezcla senales y oculta la decision necesaria." },
        { type: "definition", term: "Visibilidad IA", definition: "Presencia observable, exactitud y calidad de cita de una marca o fuente en respuestas IA para un conjunto definido de consultas." },
        { type: "checklist", title: "Diseno del set de consultas", items: [{ label: "Intencion comercial", detail: "Incluir servicios, proveedores, precios y comparativas." }, { label: "Intencion informativa", detail: "Incluir guias, definiciones, checklists y marcos." }, { label: "Mercado", detail: "Separar USA, Canada, Australia, local y multilingue." }, { label: "Competidores", detail: "Seguir competidores, medios y fuentes oficiales estables." }] },
        { type: "comparison-table", caption: "Metricas de visibilidad IA.", columns: ["Metrica", "Que indica", "Limite"], rows: [["Cobertura", "El tema aparece en una respuesta", "No prueba influencia de marca"], ["Mencion", "La marca se nombra", "Puede ser debil sin contexto"], ["Cita", "Se cita una URL", "Los formatos varian"], ["Exactitud entidad", "Servicios y mercados son correctos", "Requiere revision manual"]] },
        { type: "callout", title: "Limite de medicion", body: "No reportes visibilidad IA como atribucion exacta de ingresos sin evidencia de clics, leads y ventas.", tone: "amber" },
        { type: "steps", title: "Flujo mensual", steps: [{ title: "Muestrear", body: "Ejecutar las mismas consultas y registrar cobertura, menciones, citas y competidores." }, { title: "Clasificar", body: "Marcar exacto, parcial, ausente o enganoso." }, { title: "Mapear", body: "Conectar brechas con paginas, entidades, servicios y fuentes." }, { title: "Actuar", body: "Mejorar la fuente y volver a revisar despues de un periodo razonable." }] },
        { type: "faq", items: [{ question: "Se puede medir perfectamente la visibilidad IA?", answer: "No. Puede medirse de forma direccional con metodologia repetible y limites documentados." }, { question: "Una cita vale mas que una mencion?", answer: "A menudo es mas accionable porque apunta a una URL, pero una mencion de calidad tambien puede importar." }] },
        { type: "cta", title: "Revisa tu metodo de visibilidad IA.", body: "Taskcover puede mapear cobertura actual y brechas de contenido, entidad y fuentes.", primary: { label: "Explorar busqueda IA", href: "/services/ai-search-optimization" }, secondary: ctaCall },
      ],
      faqItems: [{ question: "Se puede medir perfectamente la visibilidad IA?", answer: "No. Puede medirse de forma direccional con metodologia repetible y limites documentados." }, { question: "Una cita vale mas que una mencion?", answer: "A menudo es mas accionable porque apunta a una URL, pero una mencion de calidad tambien puede importar." }],
    }),
    buildInsightArticle({
      id: "insight-es-technical-audit",
      slug: "technical-seo-audit-checklist-growing-websites",
      translationGroupId: "technical-audit",
      locale: "es",
      title: "Checklist de auditoria SEO tecnica para sitios en crecimiento",
      excerpt: "Checklist priorizada para rastreo, indexacion, arquitectura, canonicals, render, Core Web Vitals, schema, internacional y migraciones.",
      category: "technical-seo",
      tags: ["SEO tecnico", "Auditoria SEO", "Core Web Vitals", "Indexacion"],
      readingTime: 14,
      coverImageAlt: "Tablero de auditoria tecnica con crawl, indice, arquitectura, rendimiento y schema.",
      coverImageCaption: "Una auditoria util convierte problemas en una roadmap priorizada.",
      focusKeyword: "checklist auditoria SEO tecnica",
      secondaryKeywords: ["auditoria SEO", "auditoria crawl", "auditoria indexacion"],
      intent: "Auditar tecnicamente un sitio en crecimiento.",
      audience: "Responsables SEO, producto, desarrolladores y duenos de sitios",
      funnelStage: "consideration",
      coreQuestion: "Que revisar en una auditoria SEO tecnica para un sitio en crecimiento?",
      primaryEntity: "Auditoria SEO tecnica",
      supportingEntities: ["crawl", "indexacion", "canonicalizacion", "Core Web Vitals", "schema", "hreflang"],
      topicCluster: "SEO tecnico",
      parentPillar: "SEO tecnico",
      uniqueInformationGain: "Un modelo que separa bloqueos, reduccion de riesgo y habilitadores de crecimiento.",
      refreshTrigger: "Actualizar cuando cambien guias de rendimiento, schema o internacional.",
      sources: getSharedSources(["google-seo-starter", "google-canonical", "google-structured-data", "google-hreflang", "web-vitals"]),
      claims: [{ id: "google-crawl-index", text: "Google descubre, rastrea e indexa paginas mediante sistemas automatizados y enlaces.", requiresEvidence: true, sourceIds: ["google-seo-starter"] }, { id: "core-web-vitals", text: "Core Web Vitals cubre carga, interaccion y estabilidad visual.", requiresEvidence: true, sourceIds: ["web-vitals"] }],
      originalInsights: ["Priorizar por impacto en indexacion y ruta de ingresos, no por volumen de alertas."],
      serviceLinks: [{ label: "SEO tecnico", href: "/services/technical-seo" }, { label: "Auditoria SEO", href: "/services/seo-audit" }],
      industryLinks: [{ label: "SEO para e-commerce", href: "/industries/ecommerce-seo" }, { label: "SEO para SaaS", href: "/industries/saas-seo" }],
      sampleAuditLinks: [{ label: "Auditoria SEO tecnica de muestra", href: "/work/sample-audits/technical-seo-audit" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "international-seo-usa-canada-australia", "content-rankings-citations-leads"],
      metaTitle: "Checklist de auditoria SEO tecnica",
      metaDescription: "Checklist SEO tecnica para crawl, indexacion, arquitectura, canonicals, render, Core Web Vitals, schema y migraciones.",
      breadcrumbLabel: "Checklist auditoria SEO tecnica",
      blocks: [
        { type: "direct-answer", title: "Respuesta directa", answer: "Una auditoria SEO tecnica debe verificar que las paginas correctas puedan rastrearse, renderizarse, indexarse, canonicalizarse, estructurarse, localizarse y medirse; despues debe priorizar correcciones por riesgo y valor." },
        { type: "key-takeaways", title: "Puntos clave", items: ["Trata bloqueos de indexacion antes que detalles de plantilla.", "Canonicals y redirecciones se encarecen al escalar.", "El rendimiento importa cuando afecta experiencia y conversion.", "Cada auditoria debe terminar con dueno, prioridad y validacion."] },
        { type: "checklist", title: "Crawl e indexacion", items: [{ label: "Directivas", detail: "Revisar robots.txt, noindex, canonicals y recursos bloqueados." }, { label: "Sitemap", detail: "Comparar URLs de sitemap con canonicas indexables." }, { label: "Enlaces internos", detail: "Confirmar que las paginas prioritarias son alcanzables." }, { label: "Codigos de estado", detail: "Mapear 3xx, 4xx y 5xx por plantilla e importancia." }] },
        { type: "paragraph", text: "Los sitios en crecimiento acumulan duplicados por filtros, parametros, archivos CMS y variantes locales. La auditoria decide que URLs existen, se consolidan o redirigen." },
        { type: "comparison-table", caption: "Modelo de prioridad tecnica.", columns: ["Problema", "Riesgo", "Accion"], rows: [["Paginas prioritarias bloqueadas", "Alto", "Quitar bloqueo y validar."], ["Canonicals contradictorios", "Alto", "Elegir URL representativa."], ["Cadenas de redireccion", "Medio", "Reducirlas en rutas importantes."], ["Enlaces internos debiles", "Medio", "Agregar enlaces contextuales."]] },
        { type: "paragraph", text: "El render debe confirmar que usuarios y robots ven contenido, enlaces y CTAs utiles. El schema debe coincidir con contenido visible." },
        { type: "checklist", title: "Render y rendimiento", items: [{ label: "Contenido critico", detail: "Validar copy, enlaces y detalles de servicio en HTML renderizado." }, { label: "Core Web Vitals", detail: "Priorizar plantillas con trafico o leads." }, { label: "Schema", detail: "Evitar ratings, premios o reseñas no soportadas." }, { label: "Imagenes", detail: "Reservar dimensiones y alt text significativo." }] },
        { type: "steps", title: "Roadmap post-auditoria", steps: [{ title: "Estabilizar", body: "Corregir bloqueos de crawl, indice, render o tracking." }, { title: "Consolidar", body: "Resolver duplicados, canonicals, redirecciones y arquitectura." }, { title: "Mejorar", body: "Fortalecer schema, enlazado, rendimiento y plantillas." }, { title: "Validar", body: "Re-rastrear, inspeccionar, monitorear y documentar." }] },
        { type: "cta", title: "Necesitas una roadmap tecnica?", body: "Taskcover convierte datos de crawl, plantillas y prioridades en una roadmap SEO lista para ejecutar.", primary: { label: "Explorar SEO tecnico", href: "/services/technical-seo" }, secondary: { label: "Ver auditoria de muestra", href: "/work/sample-audits/technical-seo-audit" } },
      ],
    }),
    buildInsightArticle({
      id: "insight-es-seo-ppc",
      slug: "seo-vs-ppc-search-growth-system",
      translationGroupId: "seo-ppc",
      locale: "es",
      title: "SEO vs PPC: como construir un solo sistema de crecimiento search",
      excerpt: "Usar SEO y PPC juntos mediante intencion, landing pages, consultas, tracking, pruebas, presupuesto y reporting.",
      category: "ppc-search-intelligence",
      tags: ["SEO vs PPC", "PPC", "Inteligencia search", "Paginas de aterrizaje"],
      readingTime: 11,
      coverImageAlt: "Dashboard paid y organico con consultas, landing pages y conversiones.",
      coverImageCaption: "SEO y PPC funcionan mejor cuando comparten inteligencia de consultas y aprendizaje de conversion.",
      focusKeyword: "SEO vs PPC",
      secondaryKeywords: ["estrategia SEO PPC", "paid organic search", "crecimiento search"],
      intent: "Comparar SEO y PPC y combinarlos inteligentemente.",
      audience: "Lideres de marketing, paid media, SEO y fundadores",
      funnelStage: "consideration",
      coreQuestion: "Cuando usar SEO, PPC o ambos como sistema?",
      primaryEntity: "Search marketing",
      supportingEntities: ["SEO", "PPC", "landing pages", "consultas", "tracking conversion"],
      topicCluster: "PPC & Inteligencia search",
      parentPillar: "Crecimiento search",
      uniqueInformationGain: "Un modelo que evita afirmar que SEO y PPC siempre son igual de adecuados.",
      refreshTrigger: "Actualizar cuando cambien tracking paid, consentimiento o servicios Taskcover.",
      sources: getSharedSources(["google-seo-starter", "google-helpful-content"]),
      claims: [{ id: "people-first-content", text: "El contenido util y la experiencia siguen siendo centrales para SEO duradero.", requiresEvidence: true, sourceIds: ["google-helpful-content"] }],
      originalInsights: ["PPC compra velocidad; SEO compone ajuste. El sistema comun es la intencion search."],
      serviceLinks: [{ label: "Gestion PPC", href: "/services/ppc-management" }, { label: "Agencia SEO", href: "/services/seo-agency" }, { label: "SEO local", href: "/services/local-seo" }],
      sampleAuditLinks: [{ label: "Revision PPC + organico", href: "/work/sample-audits/ppc-organic-intelligence" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "content-rankings-citations-leads", "measure-ai-search-visibility"],
      metaTitle: "SEO vs PPC: un sistema de crecimiento search",
      metaDescription: "Compara SEO y PPC y combina paid y organico con intencion, landing pages, tracking, consultas, pruebas y reporting.",
      breadcrumbLabel: "SEO vs PPC",
      blocks: [
        { type: "direct-answer", title: "Respuesta directa", answer: "SEO y PPC no deben tratarse como rivales. Usa PPC para velocidad, pruebas y captura de demanda; usa SEO para descubrimiento duradero y autoridad cuando mercado y sitio lo soporten." },
        { type: "key-takeaways", title: "Puntos clave", items: ["PPC sirve para velocidad y control.", "SEO sirve para cobertura duradera y autoridad.", "Ambos deben compartir consultas, landing pages y conversion.", "Algunos mercados justifican un canal primero."] },
        { type: "comparison-table", caption: "Modelo SEO/PPC.", columns: ["Pregunta", "Senal SEO", "Senal PPC"], rows: [["Velocidad requerida?", "Medio/largo plazo", "Captura inmediata"], ["Intencion estable?", "Demanda recurrente", "Temporal o prueba"], ["Pagina de aterrizaje?", "Profundidad y enlaces", "Claridad de conversion"], ["Aprendizaje?", "Search Console y leads", "Terminos y CPA"]] },
        { type: "paragraph", text: "La misma persona puede hacer clic en un anuncio, comparar resultados organicos y convertir despues de una busqueda de marca. Por eso el mapa de intencion es mas util que el debate de canales." },
        { type: "decision-framework", title: "Marco de decision", criteria: [{ signal: "Intencion alta, autoridad baja, urgencia de pipeline", action: "Usar PPC mientras se mejora SEO." }, { signal: "Demanda informativa estable", action: "Invertir en contenido SEO y enlaces internos." }, { signal: "Oferta o mensaje no probado", action: "Probar con PPC antes de construir cluster SEO." }, { signal: "CPC alto y leads pobres", action: "Revisar landing, exclusiones y alternativas organicas." }] },
        { type: "checklist", title: "Reporting integrado", items: [{ label: "Temas de consulta", detail: "Agrupar terminos pagados y consultas organicas." }, { label: "Paginas de aterrizaje", detail: "Medir conversion, profundidad, velocidad y mensaje." }, { label: "Presupuesto", detail: "Comparar costo por lead calificado y oportunidad organica." }, { label: "Registro de decisiones", detail: "Documentar que pasa de prueba paid a inversion SEO." }] },
        { type: "cta", title: "Conecta decisiones SEO y PPC.", body: "Taskcover convierte datos de consultas, paginas y economia de canal en un sistema de crecimiento search.", primary: { label: "Explorar Gestion PPC", href: "/services/ppc-management" }, secondary: { label: "Explorar Agencia SEO", href: "/services/seo-agency" } },
      ],
    }),
    buildInsightArticle({
      id: "insight-es-international",
      slug: "international-seo-usa-canada-australia",
      translationGroupId: "international-seo",
      locale: "es",
      title: "SEO internacional para Estados Unidos, Canada y Australia",
      excerpt: "Planificar SEO internacional con intencion de mercado, localizacion, hreflang, canonicals, arquitectura, autoridad local y secuencia.",
      category: "local-international-seo",
      tags: ["SEO internacional", "USA", "Canada", "Australia", "Hreflang"],
      readingTime: 13,
      coverImageAlt: "Mapa de arquitectura de mercado para SEO en USA, Canada y Australia.",
      coverImageCaption: "El SEO internacional es estrategia de mercado antes que traduccion.",
      focusKeyword: "SEO internacional USA Canada Australia",
      secondaryKeywords: ["agencia SEO USA", "agencia SEO Canada", "agencia SEO Australia", "hreflang SEO"],
      intent: "Planificar SEO en tres mercados ingleses con localizacion.",
      audience: "Lideres de marketing que expanden a Norteamerica y Australia",
      funnelStage: "consideration",
      coreQuestion: "Como planificar SEO en USA, Canada y Australia?",
      primaryEntity: "SEO internacional",
      supportingEntities: ["hreflang", "canonicalizacion", "localizacion", "arquitectura de mercado", "intencion regional"],
      topicCluster: "SEO local & internacional",
      parentPillar: "SEO internacional",
      uniqueInformationGain: "Un marco de secuencia para mercados de ingles con consideraciones francesas y espanolas.",
      refreshTrigger: "Actualizar cuando cambien paginas de mercado, hreflang o prioridades de localizacion.",
      sources: getSharedSources(["google-hreflang", "google-canonical", "google-seo-starter"]),
      claims: [{ id: "hreflang-alternates", text: "Google documenta hreflang para informar versiones localizadas de una pagina.", requiresEvidence: true, sourceIds: ["google-hreflang"] }],
      originalInsights: ["La localizacion debe seguir demanda y contexto de conversion, no solo disponibilidad de idioma."],
      serviceLinks: [{ label: "SEO internacional", href: "/services/international-seo" }, { label: "SEO local", href: "/services/local-seo" }],
      industryLinks: [{ label: "SEO para Viajes", href: "/industries/travel-seo" }, { label: "SEO para Educacion", href: "/industries/education-seo" }],
      marketLinks: [{ label: "Agencia SEO USA", href: "/markets/usa-seo-agency" }, { label: "Agencia SEO Canada", href: "/markets/canada-seo-agency" }, { label: "Agencia SEO Australia", href: "/markets/australia-seo-agency" }],
      sampleAuditLinks: [{ label: "Mapa de mercado SEO internacional", href: "/work/sample-audits/international-seo-market-map" }],
      relatedArticleSlugs: ["technical-seo-audit-checklist-growing-websites", "seo-2026-google-ai-search-revenue-growth", "content-rankings-citations-leads"],
      metaTitle: "SEO internacional para USA, Canada y Australia",
      metaDescription: "Planifica SEO internacional para USA, Canada y Australia con localizacion, hreflang, canonicals, arquitectura y secuencia.",
      breadcrumbLabel: "SEO internacional USA Canada Australia",
      blocks: [
        { type: "direct-answer", title: "Respuesta directa", answer: "El SEO internacional para USA, Canada y Australia empieza con intencion de mercado y arquitectura, luego alinea localizacion, hreflang, canonicals, autoridad local, adaptacion de contenido y secuencia." },
        { type: "key-takeaways", title: "Puntos clave", items: ["No asumas que la misma pagina en ingles sirve para todos.", "Canada puede requerir ingles y frances segun la audiencia.", "El espanol puede apoyar audiencias hispanas en USA si hay encaje.", "Hreflang ayuda cuando existen equivalentes localizados reales."] },
        { type: "paragraph", text: "USA, Canada y Australia comparten parte de la demanda en ingles, pero no las mismas expectativas, competidores, terminos, pruebas locales ni contextos comerciales." },
        { type: "comparison-table", caption: "Consideraciones por mercado.", columns: ["Mercado", "Consideracion SEO", "Implicacion de contenido"], rows: [["USA", "Consultas competitivas y variacion local", "Segmentar por servicio, sector e intencion local."], ["Canada", "Necesidades en ingles y frances", "Planificar contenido bilingue cuando demanda y operaciones lo justifiquen."], ["Australia", "Terminologia y competidores locales", "Adaptar ejemplos, lenguaje y senales de confianza."]] },
        { type: "paragraph", text: "Elige una estructura URL que el negocio pueda mantener. Hreflang debe describir paginas equivalentes, no disfrazar duplicados sin valor de mercado." },
        { type: "checklist", title: "Checks internacionales", items: [{ label: "Mapa de mercado", detail: "Definir servicios, sectores y regiones que merecen paginas." }, { label: "Profundidad de localizacion", detail: "Adaptar terminos, pruebas, ofertas y CTAs." }, { label: "Hreflang", detail: "Incluir auto-referencias y equivalentes reales." }, { label: "Autoridad", detail: "Construir relevancia local con recursos, citas y enlaces internos." }] },
        { type: "steps", title: "Secuencia recomendada", steps: [{ title: "Elegir un cluster", body: "Empezar con el mercado de mejor fit entre servicio, demanda y operacion." }, { title: "Localizar paginas prioritarias", body: "Adaptar servicios, mercados y guias de alta intencion." }, { title: "Validar senales", body: "Revisar canonicals, hreflang, enlaces internos, sitemaps e indexacion." }, { title: "Expandir con evidencia", body: "Usar datos search, calidad de leads y feedback comercial." }] },
        { type: "cta", title: "Planifica la arquitectura de mercado.", body: "Mapea USA, Canada y Australia antes de escalar paginas localizadas.", primary: { label: "Explorar SEO internacional", href: "/services/international-seo" }, secondary: ctaCall },
      ],
    }),
    buildInsightArticle({
      id: "insight-es-content-authority",
      slug: "content-rankings-citations-leads",
      translationGroupId: "content-authority",
      locale: "es",
      title: "Como crear contenido que gane rankings, citas y leads",
      excerpt: "Marco de autoridad de contenido para intencion, informacion nueva, input experto, entidades, activos citables, PR digital, enlaces, conversion y refresh.",
      category: "content-authority",
      tags: ["Marketing de contenidos", "Autoridad digital", "Information gain", "Enlaces internos"],
      readingTime: 12,
      coverImageAlt: "Mapa de autoridad de contenido con intencion, evidencia, entidades, citas, enlaces y leads.",
      coverImageCaption: "El contenido util debe servir al lector y al sistema search que lo rodea.",
      focusKeyword: "contenido rankings citas leads",
      secondaryKeywords: ["autoridad contenido SEO", "contenido citable", "estrategia contenido SEO"],
      intent: "Crear contenido que funcione en search y apoye resultados comerciales.",
      audience: "Equipos de contenido, SEO, PR digital y marketing",
      funnelStage: "consideration",
      coreQuestion: "Como crear contenido que pueda rankear, ser citado y generar leads calificados?",
      primaryEntity: "Autoridad de contenido",
      supportingEntities: ["intencion search", "information gain", "input experto", "PR digital", "enlaces internos", "conversion"],
      topicCluster: "Contenido & Autoridad digital",
      parentPillar: "Marketing de contenidos",
      uniqueInformationGain: "Un sistema que une utilidad, valor de cita, PR digital y conversion sin densidad de keywords.",
      refreshTrigger: "Actualizar cuando cambien fuentes, servicios o evidencia de rendimiento.",
      sources: getSharedSources(["google-helpful-content", "google-seo-starter", "google-structured-data"]),
      claims: [{ id: "people-first-content", text: "Google recomienda contenido util, fiable y pensado para personas.", requiresEvidence: true, sourceIds: ["google-helpful-content"] }],
      originalInsights: ["Un activo de contenido debe merecer una accion siguiente: guardar, clic interno, cita, pregunta comercial o refresh."],
      serviceLinks: [{ label: "Marketing de contenidos", href: "/services/content-marketing" }, { label: "PR digital y link building", href: "/services/digital-pr-link-building" }, { label: "Optimizacion para busqueda IA", href: "/services/ai-search-optimization" }, { label: "SEO Mentor", href: "/services/seo-mentor-service" }],
      caseStudyLinks: [{ label: "Casos de estudio", href: "/work/case-studies" }],
      sampleAuditLinks: [{ label: "Mapa de brechas de contenido", href: "/work/sample-audits/content-gap-map" }],
      relatedArticleSlugs: ["seo-2026-google-ai-search-revenue-growth", "measure-ai-search-visibility", "technical-seo-audit-checklist-growing-websites"],
      metaTitle: "Crear contenido que gane rankings, citas y leads",
      metaDescription: "Marco de contenido SEO para intencion, informacion nueva, expertise, entidades, citas, PR digital, enlaces internos, leads y refresh.",
      breadcrumbLabel: "Contenido, citas y leads",
      blocks: [
        { type: "direct-answer", title: "Respuesta directa", answer: "El contenido gana rankings, citas y leads cuando responde a una intencion clara, agrega interpretacion original, usa evidencia creible, cubre entidades correctas, se integra al sitio y ofrece un siguiente paso natural." },
        { type: "key-takeaways", title: "Puntos clave", items: ["La intencion es el inicio, no toda la estrategia.", "La informacion nueva viene de interpretacion, ejemplos y evidencia.", "El contenido citable necesita claims, fuentes y marcos claros.", "Las rutas de lead deben ser utiles, no forzadas."] },
        { type: "paragraph", text: "La intencion dice que quiere lograr el lector. La informacion nueva explica por que tu pagina merece existir. Reescribir los mismos consejos que la competencia no basta." },
        { type: "checklist", title: "Entradas de informacion nueva", items: [{ label: "Input experto", detail: "Capturar criterio real sin inventar citas ni credenciales." }, { label: "Marcos de decision", detail: "Ayudar a elegir que hacer." }, { label: "Bloques de evidencia", detail: "Citar fuentes primarias para afirmaciones factuales." }, { label: "Ejemplos operativos", detail: "Conectar el concepto con auditorias, briefs, roadmaps o ventas." }] },
        { type: "comparison-table", caption: "Activos de contenido y uso.", columns: ["Activo", "Mejor uso", "Ruta de lead"], rows: [["Checklist", "Evaluacion operativa", "Auditoria SEO o mentor"], ["Marco", "Decision estrategica", "Llamada estrategica"], ["Comparativa", "Evaluacion de opciones", "Pagina de servicio"], ["Lista de evidencia", "Confianza y citas", "PR digital"]] },
        { type: "paragraph", text: "Los enlaces internos deben explicar relaciones. Una guia sobre contenido citable puede enlazar naturalmente a content marketing, PR digital, busqueda IA, casos, auditorias y SEO Mentor." },
        { type: "related-service", title: "SEO Mentor como ruta de habilitacion", href: "/services/seo-mentor-service", summary: "SEO Mentor ayuda a equipos a fortalecer briefs, revisiones, criterio de contenido y priorizacion." },
        { type: "steps", title: "Flujo de refresh", steps: [{ title: "Inspeccionar demanda", body: "Revisar consultas, leads, objeciones de ventas y cambios de competidores." }, { title: "Verificar evidencia", body: "Actualizar fuentes, afirmaciones, ejemplos y schema." }, { title: "Mejorar rutas", body: "Agregar enlaces a servicios, auditorias, casos y mercados." }, { title: "Documentar", body: "Registrar que cambio en lugar de actualizar fechas sin sustancia." }] },
        { type: "faq", items: [{ question: "Debe seguirse una densidad de palabra clave?", answer: "No. Un buen brief cubre intencion, entidades, evidencia y decisiones del lector." }, { question: "El contenido puede ayudar con citas en IA?", answer: "Puede mejorar la comprension y la posibilidad de referencia, pero nadie puede garantizar una cita." }] },
        { type: "cta", title: "Construye contenido con autoridad y ruta a ingresos.", body: "Taskcover ayuda a conectar guias utiles, autoridad digital, busqueda IA y conversion.", primary: { label: "Explorar Marketing de contenidos", href: "/services/content-marketing" }, secondary: { label: "Explorar PR digital", href: "/services/digital-pr-link-building" } },
      ],
      faqItems: [{ question: "Debe seguirse una densidad de palabra clave?", answer: "No. Un buen brief cubre intencion, entidades, evidencia y decisiones del lector." }, { question: "El contenido puede ayudar con citas en IA?", answer: "Puede mejorar la comprension y la posibilidad de referencia, pero nadie puede garantizar una cita." }],
    }),
  ],
};
