import type { LeadsContent } from "@/content/leads.types";

export const leads: LeadsContent = {
  locale: "es",
  recipientEmail: "business@taskcover.com",
  common: {
    back: "Volver",
    continue: "Continuar",
    submit: "Enviar solicitud",
    submitting: "Enviando...",
    retry: "Intentar de nuevo",
    directEmail: "Escribir a business@taskcover.com",
    requiredNote: "Los campos obligatorios estan indicados.",
    optional: "Opcional",
    consentText:
      "Acepto que Taskcover use esta informacion para revisar mi solicitud y contactarme sobre servicios relevantes de crecimiento en busqueda.",
    honeypotLabel: "Deja este campo vacio",
    unavailableTitle: "El envio en linea no esta disponible temporalmente.",
    unavailableBody:
      "Puedes enviar tu solicitud directamente a business@taskcover.com. Los datos ingresados permanecen en esta pagina para reintentar o escribir al equipo.",
    temporaryError:
      "La solicitud no pudo entregarse ahora. Intentalo de nuevo o escribe directamente a business@taskcover.com.",
    spamError:
      "La solicitud no pudo aceptarse. Revisa el formulario e intentalo de nuevo, o escribe directamente a business@taskcover.com.",
    validationSummary: "Revisa los campos marcados antes de continuar.",
    mailSubjects: {
      "seo-audit": "Solicitud de auditoria SEO gratis",
      "strategy-call": "Solicitud de llamada estrategica",
      "general-contact": "Solicitud de contacto Taskcover",
      "media-inquiry": "Consulta de medios para Taskcover",
      "private-reference": "Solicitud de referencia privada",
      "data-request": "Solicitud de datos Taskcover",
      partnership: "Consulta de partnership",
      "seo-mentor": "Consulta SEO Mentor",
      "ppc-inquiry": "Consulta PPC",
      other: "Consulta Taskcover",
    },
    turnstileLabel: "Verificacion de seguridad",
  },
  fields: {
    name: { label: "Nombre completo", placeholder: "Jane Nguyen" },
    workEmail: { label: "Email laboral", placeholder: "jane@empresa.com" },
    company: { label: "Empresa", placeholder: "Empresa u organizacion" },
    role: { label: "Rol", placeholder: "Marketing lead, fundador, operador" },
    websiteUrl: { label: "URL del sitio", placeholder: "https://ejemplo.com" },
    market: { label: "Mercado principal" },
    industry: { label: "Industria" },
    serviceInterests: { label: "Servicios de interes" },
    currentTrafficRange: { label: "Trafico organico mensual actual" },
    paidSearchActivity: { label: "Esta activo paid search?" },
    primaryChallenge: { label: "Principal desafio de crecimiento en busqueda", placeholder: "Que bloquea visibilidad, leads o ejecucion?" },
    goals: { label: "Objetivo de negocio principal", placeholder: "Que debe ayudar a lograr la busqueda?" },
    timeline: { label: "Plazo deseado" },
    investmentRange: { label: "Inversion mensual estimada en crecimiento de busqueda" },
    preferredTimeZone: { label: "Zona horaria preferida" },
    preferredCallWindows: { label: "Ventanas preferidas para llamada" },
    message: { label: "Mensaje", placeholder: "Comparte contexto, enlaces, restricciones o preguntas utiles." },
    engagementType: { label: "Tipo de engagement" },
    publication: { label: "Publicacion o plataforma", placeholder: "Publicacion, podcast, newsletter o programa" },
    topic: { label: "Tema", placeholder: "Busqueda, visibilidad IA, SEO tecnico, SEO local..." },
    deadline: { label: "Fecha limite", placeholder: "Fecha o timing si aplica" },
    requestedFormat: { label: "Formato solicitado" },
  },
  validation: {
    required: "Este campo es obligatorio.",
    email: "Ingresa un email laboral valido.",
    url: "Ingresa una URL de sitio valida.",
    consent: "El consentimiento es obligatorio antes de enviar.",
    selectRequired: "Elige al menos una opcion.",
    length: "Este campo es demasiado largo.",
    malformed: "Este valor no es compatible.",
    callWindows: "Elige dos o tres ventanas preferidas para llamada.",
  },
  options: {
    markets: [
      { value: "usa", label: "Estados Unidos" },
      { value: "canada", label: "Canada" },
      { value: "australia", label: "Australia" },
      { value: "multiple", label: "Varios mercados" },
      { value: "other", label: "Otro" },
    ],
    industries: [
      { value: "travel-hospitality", label: "Viajes y hospitalidad" },
      { value: "education", label: "Educacion" },
      { value: "healthcare-wellness", label: "Salud y bienestar" },
      { value: "legal-immigration", label: "Legal e inmigracion" },
      { value: "saas-technology", label: "SaaS y tecnologia" },
      { value: "ecommerce", label: "eCommerce" },
      { value: "franchise-multilocation", label: "Franquicia y multiubicacion" },
      { value: "other", label: "Otro" },
    ],
    services: [
      { value: "seo-agency", label: "Estrategia SEO" },
      { value: "technical-seo", label: "SEO tecnico" },
      { value: "ai-search-optimization", label: "Optimizacion para busqueda IA" },
      { value: "content-marketing", label: "Marketing de contenidos" },
      { value: "digital-pr-link-building", label: "PR digital y autoridad" },
      { value: "local-seo", label: "SEO local" },
      { value: "ecommerce-seo", label: "SEO eCommerce" },
      { value: "international-seo", label: "SEO internacional" },
      { value: "seo-audit", label: "Auditoria SEO" },
      { value: "ppc-management", label: "Gestion PPC" },
      { value: "seo-mentor-service", label: "Servicio SEO Mentor" },
    ],
    traffic: [
      { value: "unknown", label: "No estoy seguro" },
      { value: "under-1000", label: "Menos de 1.000 visitas/mes" },
      { value: "1000-10000", label: "1.000-10.000 visitas/mes" },
      { value: "10000-50000", label: "10.000-50.000 visitas/mes" },
      { value: "50000-plus", label: "50.000+ visitas/mes" },
    ],
    paidSearch: [
      { value: "yes", label: "Si" },
      { value: "no", label: "No" },
      { value: "planned", label: "Planeado" },
      { value: "not-sure", label: "No estoy seguro" },
    ],
    timelines: [
      { value: "urgent", label: "Necesita atencion ahora" },
      { value: "30-60-days", label: "30-60 dias" },
      { value: "quarter", label: "Este trimestre" },
      { value: "6-months", label: "Proximos 6 meses" },
      { value: "exploring", label: "Explorando opciones" },
    ],
    investments: [
      { value: "not-sure", label: "No estoy seguro" },
      { value: "under-2500", label: "Menos de USD 2.500/mes" },
      { value: "2500-5000", label: "USD 2.500-5.000/mes" },
      { value: "5000-10000", label: "USD 5.000-10.000/mes" },
      { value: "10000-plus", label: "USD 10.000+/mes" },
      { value: "project-based", label: "Proyecto puntual" },
    ],
    timeZones: [
      { value: "america-eastern", label: "Hora Este" },
      { value: "america-central", label: "Hora Central" },
      { value: "america-mountain", label: "Hora Montana" },
      { value: "america-pacific", label: "Hora Pacifico" },
      { value: "canada-eastern", label: "Hora Este Canada" },
      { value: "australia-eastern", label: "Hora Este Australia" },
      { value: "europe", label: "Europa" },
      { value: "asia", label: "Asia" },
      { value: "other", label: "Otra" },
    ],
    callWindows: [
      { value: "weekday-morning", label: "Manana entre semana" },
      { value: "weekday-midday", label: "Mediodia entre semana" },
      { value: "weekday-afternoon", label: "Tarde entre semana" },
      { value: "weekday-evening", label: "Noche entre semana" },
      { value: "flexible", label: "Flexible" },
    ],
    contactIntents: [
      { value: "seo-services", label: "Servicios SEO" },
      { value: "ppc", label: "Gestion PPC" },
      { value: "seo-mentor", label: "Servicio SEO Mentor" },
      { value: "media", label: "Consulta de medios" },
      { value: "private-reference", label: "Solicitud de referencia privada" },
      { value: "partnership", label: "Partnership" },
      { value: "general", label: "Pregunta general" },
      { value: "other", label: "Otro" },
    ],
    engagementTypes: [
      { value: "audit", label: "Auditoria o evaluacion" },
      { value: "ongoing", label: "Programa continuo de crecimiento" },
      { value: "consulting", label: "Consultoria o mentoría" },
    ],
    requestedFormats: [
      { value: "quote", label: "Cita escrita" },
      { value: "interview", label: "Entrevista" },
      { value: "briefing", label: "Briefing tecnico" },
    ],
  },
  freeAudit: {
    meta: { title: "Solicitud de auditoria SEO gratis | Taskcover Agency", description: "Solicita una auditoria SEO de Taskcover sobre salud tecnica, demanda search, autoridad de contenido, preparacion IA y prioridades de 90 dias." },
    eyebrow: "Evaluacion diagnostica",
    h1: "Solicita una auditoria SEO gratis",
    intro: "Comparte el contexto necesario para diagnosticar el sistema de busqueda detras de tu sitio, mercado, contenido y prioridades.",
    proof: "La solicitud de auditoria no promete rankings ni tiempo de respuesta. Ayuda a Taskcover a evaluar fit y el enfoque diagnostico correcto.",
    steps: [
      { title: "Contacto y sitio", description: "Quien eres y que sitio debe revisarse." },
      { title: "Contexto de negocio y busqueda", description: "Mercado, industria, servicios de interes y actividad actual." },
      { title: "Prioridades y plazo", description: "Que importa mas, cuando actuar y contexto opcional de inversion." },
    ],
    previewTitle: "Areas posibles de auditoria",
    previewIntro: "La revision adecuada depende de tu mercado y sitio, pero el diagnostico puede cubrir:",
    previewItems: ["Salud tecnica", "Demanda search", "Autoridad de contenido", "Preparacion para busqueda IA", "Oportunidad local o internacional", "Cruce paid y organico", "Prioridades de 90 dias"],
    privacyTitle: "Como se usa la informacion",
    privacyBody: "Los datos del formulario se usan solo para evaluar y responder tu solicitud. No se solicitan datos personales sensibles, financieros, de salud ni de cuentas.",
  },
  bookCall: {
    meta: { title: "Solicitar llamada estrategica | Taskcover Agency", description: "Solicita una llamada estrategica con Taskcover para SEO, busqueda IA, PPC, contenido, local, eCommerce, internacional o plan search." },
    eyebrow: "Planificador de sesion estrategica",
    h1: "Solicita una llamada estrategica",
    intro: "Comparte tu contexto de crecimiento y ventanas preferidas. Taskcover confirmara disponibilidad despues de que un adaptador configurado acepte la solicitud.",
    agendaTitle: "Que puede cubrir la sesion",
    agenda: ["Contexto de negocio", "Restricciones de busqueda", "Oportunidades prioritarias", "Fit para auditoria, advisory o ejecucion"],
    prepareTitle: "Contexto util para preparar",
    prepare: ["Sitio y mercado", "Actividad SEO o PPC actual", "Restricciones internas", "Fechas limite o decisiones importantes"],
    boundary: "Esta ruta recoge una solicitud de llamada estrategica. No confirma una cita de calendario hasta que exista un futuro adaptador de calendario.",
  },
  contact: {
    meta: { title: "Contactar a Taskcover Agency | Solicitudes search", description: "Contacta a Taskcover por servicios SEO, PPC, SEO Mentor, medios, referencias privadas, partnerships o preguntas generales." },
    eyebrow: "Mesa inteligente de solicitudes",
    h1: "Envia la solicitud correcta a Taskcover",
    intro: "Elige la intencion que mejor describa tu solicitud para evaluarla con el contexto adecuado.",
    deskTitle: "Mapa de enrutamiento",
    deskItems: ["Fit SEO y PPC", "Preguntas de mentoría", "Medios y comentario experto", "Calificacion de referencia privada", "Partnerships y solicitudes generales"],
    intentHelp: "La intencion seleccionada cambia los campos de contexto abajo.",
  },
  thankYou: {
    meta: { title: "Solicitud recibida | Taskcover Agency", description: "Confirmacion de solicitud Taskcover." },
    fallbackTitle: "Solicitud recibida",
    fallbackMessage: "El tipo de solicitud se registro de forma segura.",
    nextLabel: "Que pasa despues",
    studiesLabel: "Casos relevantes",
    samplesLabel: "Auditorias ejemplo relevantes",
    viewStudies: "Ver casos",
    viewSamples: "Ver auditorias ejemplo",
    analyticsHook: "Hook de analytics listo: thank_you_view",
    states: {
      "seo-audit": { title: "Solicitud de auditoria SEO recibida", message: "Tu solicitud diagnostica fue aceptada por la ruta de entrega configurada.", next: ["Taskcover revisa el sitio y contexto enviados.", "El equipo evalua fit, posibles areas de auditoria y siguientes pasos utiles.", "Esta pagina no garantiza un tiempo de respuesta."], studies: ["British University Vietnam", "Matthew Jeffery Law Firm", "SkatePro"], samples: ["Auditoria SEO tecnica", "Revision de visibilidad IA", "Roadmap search de 90 dias"], primaryCta: "Solicitar llamada estrategica", secondaryCta: "Explorar auditorias ejemplo" },
      "strategy-call": { title: "Solicitud de llamada estrategica recibida", message: "Tu solicitud de llamada fue entregada. No es una cita de calendario confirmada.", next: ["Taskcover revisa fit y disponibilidad.", "El equipo usa tus ventanas preferidas para evaluar opciones.", "Un futuro adaptador de calendario podra automatizar esto."], studies: ["Agoda", "FWD Insurance", "Casa Madera"], samples: ["Mapa de gaps de contenido", "Revision PPC + organico"], primaryCta: "Ver casos", secondaryCta: "Explorar servicios" },
      "media-inquiry": { title: "Consulta de medios recibida", message: "Tu solicitud de medios fue entregada para revision editorial.", next: ["Se revisan tema, formato y fecha limite.", "Taskcover evalua si un representante aprobado es adecuado.", "No se promete disponibilidad de portavoz."], studies: ["Agoda", "British University Vietnam"], samples: ["Revision de visibilidad IA", "Framework search"], primaryCta: "Explorar prueba", secondaryCta: "Volver a contacto" },
      "private-reference": { title: "Solicitud de referencia privada recibida", message: "Tu solicitud de referencia privada fue entregada para calificacion.", next: ["Taskcover revisa fit y limites de confidencialidad.", "No se exponen automaticamente nombres, detalles ni contactos privados.", "La disponibilidad se evalua caso por caso."], studies: ["Biblioteca de casos verificados", "Estandar de resultados"], samples: ["Auditoria SEO tecnica", "Roadmap 90 dias"], primaryCta: "Revisar estandar de prueba", secondaryCta: "Ver work" },
      "data-request": { title: "Solicitud de datos recibida", message: "Tu solicitud de privacidad o datos fue aceptada por la ruta de entrega configurada.", next: ["Taskcover revisa la categoria y el contexto enviados.", "Puede requerirse verificacion de identidad antes de actuar.", "No se garantiza tiempo de respuesta en esta pagina."], studies: ["Politica de privacidad", "Politica de cookies"], samples: ["Preferencias de cookies", "Solicitud de datos"], primaryCta: "Revisar privacidad", secondaryCta: "Gestionar preferencias de cookies" },
      "general-contact": { title: "Solicitud de contacto recibida", message: "Tu solicitud fue aceptada por la ruta de entrega configurada.", next: ["Taskcover revisa el mensaje y lo enruta por tema.", "Si es relevante, el equipo puede conectar la solicitud con un servicio, auditoria ejemplo o caso.", "No se garantiza tiempo de respuesta."], studies: ["Biblioteca de casos verificados", "Biblioteca de auditorias ejemplo"], samples: ["Mapa de gaps de contenido", "Auditoria SEO local"], primaryCta: "Solicitar llamada estrategica", secondaryCta: "Explorar servicios" },
      partnership: { title: "Consulta de partnership recibida", message: "Tu solicitud de partnership fue entregada para revision de fit.", next: ["Taskcover revisa alineacion, audiencia y limites operativos.", "No se implica disponibilidad de partnership.", "Podria solicitarse contexto adicional."], studies: ["Sistema de prueba y autoridad"], samples: ["Framework search"], primaryCta: "Explorar prueba", secondaryCta: "Volver a contacto" },
      "seo-mentor": { title: "Consulta SEO Mentor recibida", message: "Tu solicitud de mentoría fue entregada.", next: ["Taskcover revisa contexto del equipo y brechas de capacidad.", "El alcance de mentoría se evalua antes de confirmar.", "No se garantiza tiempo de respuesta."], studies: ["Servicio SEO Mentor"], samples: ["Roadmap 90 dias"], primaryCta: "Explorar SEO Mentor", secondaryCta: "Ver auditorias ejemplo" },
      "ppc-inquiry": { title: "Consulta PPC recibida", message: "Tu solicitud PPC fue entregada.", next: ["Taskcover revisa contexto paid search y cruce organico.", "El equipo evalua si gestion PPC o inteligencia search es el fit adecuado.", "No se garantiza tiempo de respuesta."], studies: ["Casa Madera", "FWD Insurance"], samples: ["Revision PPC + organico"], primaryCta: "Explorar gestion PPC", secondaryCta: "Ver work" },
      other: { title: "Solicitud recibida", message: "Tu solicitud fue aceptada por la ruta de entrega configurada.", next: ["Taskcover revisa y enruta el mensaje.", "Podria solicitarse contexto adicional.", "No se garantiza tiempo de respuesta."], studies: ["Biblioteca Work"], samples: ["Biblioteca de auditorias ejemplo"], primaryCta: "Explorar Work", secondaryCta: "Volver al inicio" },
      contact: { title: "Solicitud de contacto recibida", message: "Tu solicitud fue aceptada por la ruta de entrega configurada.", next: ["Taskcover revisa el tipo de solicitud y mensaje.", "El equipo evalua la siguiente ruta mas relevante.", "No se garantiza tiempo de respuesta."], studies: ["Biblioteca de casos verificados"], samples: ["Biblioteca de auditorias ejemplo"], primaryCta: "Solicitar llamada estrategica", secondaryCta: "Explorar Work" },
    },
  },
};
