import type { PricingContent } from "../pricing.types";

export const pricing = {
  metadata: {
    title: "Precios | Planes SEO y desarrollo web",
    description:
      "Explora los precios de Taskcover Agency para SEO local, SEO nacional, SEO global, desarrollo web, SEO Mentor, auditorias, gestion PPC y programas de crecimiento search a medida.",
  },
  breadcrumbs: {
    home: "Inicio",
    pricing: "Precios",
  },
  hero: {
    eyebrow: "Precios de crecimiento search",
    h1: "Precios para crecimiento search local, nacional y global",
    subheadline:
      "Empieza con una base SEO local enfocada o escala hacia crecimiento nacional y global con SEO, AI Search, PPC, autoridad de contenido y ejecucion tecnica.",
    primaryCta: { label: "Auditoria SEO gratuita", href: "/free-seo-audit" },
    secondaryCta: { label: "Reservar llamada", href: "/book-a-call" },
    signalChips: ["Local", "Nacional", "Global", "Web", "Mentor"],
    commandPanel: {
      title: "Panel de alcance",
      rows: [
        { label: "Punto de entrada", value: "Auditoria SEO gratuita" },
        { label: "Ejecucion recomendada", value: "National SEO Growth System" },
        { label: "Proyecto web", value: "Growth Website" },
        { label: "Asesoria recomendada", value: "SEO Mentor Growth Advisory" },
        { label: "Mercados complejos", value: "Alcance personalizado requerido" },
      ],
      note: "Cada engagement empieza con el alcance mas pequeno que puede apoyar el objetivo de forma realista.",
    },
  },
  recurringNote:
    "Todos los precios se muestran en USD. El precio final depende del mercado, la complejidad del sitio, la competencia, las necesidades de contenido y la velocidad de ejecucion. Contactanos o solicita una auditoria gratuita para obtener el alcance mas preciso.",
  scopeNote:
    "Los planes de entrada son intencionalmente enfocados. Si tus objetivos requieren produccion de contenido, implementacion tecnica, SEO multi-mercado o ejecucion continua, Taskcover recomendara un alcance mas amplio.",
  factors: {
    eyebrow: "Por que cambia el precio",
    title: "El precio exacto depende del sistema search que necesitas construir.",
    description:
      "Una zona de servicio local no se presupuesta igual que una categoria nacional o un programa multi-pais. Estos factores definen el alcance.",
    items: [
      { label: "Alcance de mercado", description: "La competencia local, nacional o global cambia el nivel de estrategia, contenido y soporte tecnico requerido." },
      { label: "Complejidad del sitio", description: "Sitios grandes, frameworks JavaScript, migraciones o CMS desordenados requieren trabajo tecnico mas profundo." },
      { label: "Necesidades de contenido", description: "Un roadmap es mas ligero que briefs continuos, QA editorial, actualizaciones y construccion de autoridad." },
      { label: "Superficies de busqueda", description: "Google organico, local packs, respuestas IA, PPC y resultados internacionales agregan lineas de trabajo distintas." },
      { label: "Velocidad de ejecucion", description: "Los plazos comprimidos requieren cadencia mas estrecha, mas participacion senior y dependencias mas claras." },
      { label: "Soporte del equipo interno", description: "El precio cambia si tu equipo ejecuta o si Taskcover debe llevar estrategia, QA y soporte de implementacion." },
    ],
  },
  tabs: {
    eyebrow: "Menu de precios",
    title: "Elige la via de crecimiento search que encaja con el problema.",
    description:
      "Usa las pestanas para revisar precios de partida, limites de alcance y el siguiente paso. Los precios son puntos de partida, no cotizaciones fijas.",
    compareLink: "Comparar todos los planes",
    ariaLabel: "Categorias de precios",
    items: [
      {
        id: "local",
        label: "SEO local",
        eyebrow: "Base local enfocada",
        title: "Precios de SEO local",
        intro:
          "Para empresas que necesitan mejorar visibilidad en una ciudad, una zona de servicio o un pequeno grupo de mercados locales.",
        plans: [
          {
            id: "local-starter",
            name: "Local SEO Starter",
            price: "Desde $1,000/mes",
            positioning: "Para negocios locales que necesitan una base limpia de busqueda local.",
            bestFor: [
              "Una ubicacion principal o zona de servicio",
              "Empresa local de servicios",
              "Restaurante, clinica, servicio profesional u hospitalidad local",
              "Sitio pequeno con complejidad tecnica limitada",
            ],
            includes: [
              "Revision de Google Business Profile y guia de optimizacion",
              "Mapa de keywords e intencion local",
              "Revision de una pagina principal de ubicacion o area de servicio",
              "Revision basica de consistencia citation/NAP",
              "Recomendaciones de senales de resenas",
              "Snapshot de competidores locales",
              "Checklist mensual de visibilidad local",
              "Reporting simple",
            ],
            scopeGuard:
              "Disenado para una ubicacion o zona de servicio enfocada. Multi-ubicacion, produccion de contenido, remediacion tecnica, PPC y digital PR requieren un alcance mayor.",
            minimum: "Minimo de 3 meses",
            addOn: "Ubicaciones adicionales desde $300-$500/ubicacion/mes",
            cta: { label: "Empezar con auditoria local", href: "/free-seo-audit" },
          },
          {
            id: "local-growth",
            name: "Local Growth / Multi-location",
            price: "Desde $2,500/mes",
            positioning:
              "Un alcance personalizado compacto para empresas con varias ubicaciones, mas contenido o complejidad local.",
            bestFor: [
              "Dos o mas ubicaciones prioritarias",
              "Visibilidad de franquicia o sucursales",
              "Arquitectura de paginas locales",
              "Necesidades de prueba local y reporting",
            ],
            includes: [
              "Mapa de intencion multi-ubicacion",
              "Revision de estructura de paginas de ubicacion",
              "Guia de Google Business Profile por ubicacion prioritaria",
              "Revision de competidores locales y gaps de contenido",
              "Roadmap mensual de visibilidad search",
            ],
            scopeGuard:
              "Se usa cuando el plan starter es demasiado estrecho pero la empresa aun no necesita un sistema nacional.",
            cta: { label: "Solicitar alcance local", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "national",
        label: "SEO nacional",
        eyebrow: "Crecimiento en un pais",
        title: "Precios de SEO nacional",
        intro:
          "Para empresas que compiten en un pais por demanda de categorias, servicios, SaaS, eCommerce, educacion, legal, salud o servicios profesionales.",
        plans: [
          {
            id: "national-foundation",
            name: "National SEO Foundation",
            price: "Desde $2,500/mes",
            positioning:
              "Para conseguir claridad tecnica, mapa de demanda search y roadmap serio antes de escalar la ejecucion.",
            bestFor: [
              "Un mercado pais",
              "Keywords nacionales de categoria o servicio",
              "SaaS, eCommerce, educacion, legal, salud o servicios profesionales",
              "Empresa que necesita roadmap tecnico y de contenido",
            ],
            includes: [
              "Mapa nacional de keywords e intenciones",
              "Revision tecnica SEO",
              "Recomendaciones de arquitectura del sitio",
              "Revision SERP competitiva",
              "Planificacion de gaps de contenido y topic clusters",
              "Estrategia de enlazado interno",
              "Snapshot de preparacion AI Search",
              "Roadmap y reporting mensual",
            ],
            cta: { label: "Construir la base", href: "/book-a-call" },
          },
          {
            id: "national-growth",
            name: "National SEO Growth System",
            price: "Desde $4,500/mes",
            recommended: true,
            positioning:
              "El plan de ejecucion recomendado para empresas en crecimiento que necesitan tecnico, autoridad de contenido, AI Search y reporting trabajando juntos.",
            bestFor: [
              "Empresa seria en etapa de crecimiento",
              "SEO tecnico mas autoridad de contenido mas AI Search mas reporting",
              "Keywords comerciales no locales",
              "Demanda cualificada, no solo trafico",
            ],
            includes: [
              "Roadmap tecnico SEO",
              "Planificacion de autoridad de contenido",
              "Optimizacion AI Search",
              "Mejoras de enlazado interno",
              "Reporting de inteligencia search",
              "Recomendaciones de rutas de conversion",
              "Revision estrategica mensual",
              "Recomendaciones de confianza basadas en prueba/casos",
            ],
            cta: { label: "Hablar del growth system", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "global",
        label: "SEO global",
        eyebrow: "Expansion multi-mercado",
        title: "Precios de SEO global",
        intro:
          "Para marcas que venden en varios paises, idiomas o sistemas regionales donde la arquitectura y la localizacion importan.",
        plans: [
          {
            id: "global-expansion",
            name: "Global SEO Expansion",
            price: "Desde $7,500/mes",
            positioning:
              "Para marcas que se expanden en varios paises, idiomas o journeys search de mercado.",
            bestFor: [
              "USA mas Canada mas Australia",
              "Busqueda multi-pais",
              "SEO multilingue",
              "Mercados en ingles, frances y espanol",
              "SaaS, educacion, viajes, eCommerce, franquicia o marcas internacionales",
            ],
            includes: [
              "Arquitectura SEO multi-mercado",
              "Mapa de intencion por pais/idioma",
              "SEO tecnico internacional",
              "Revision hreflang/localizacion cuando corresponda",
              "Estrategia regional de keywords",
              "Estrategia de localizacion de contenido",
              "Revision de coherencia de entidad y AI Search",
              "Reporting por mercado",
            ],
            cta: { label: "Planificar alcance global", href: "/book-a-call" },
          },
          {
            id: "enterprise-authority",
            name: "Enterprise / Multi-Market Authority",
            price: "Personalizado desde $12,000/mes",
            positioning:
              "Precio personalizado para programas enterprise, migracion, autoridad, regulados o con multiples stakeholders.",
            bestFor: [
              "Sitio enterprise",
              "Arquitectura tecnica grande",
              "Migraciones",
              "Muchos stakeholders",
              "Campanas digital PR / autoridad",
              "Multiples mercados/idiomas",
              "Industrias reguladas o sensibles a confianza",
            ],
            includes: [
              "Arquitectura enterprise de crecimiento search",
              "Planificacion de migracion y stakeholders",
              "Gobernanza tecnica, contenido, AI Search y autoridad",
              "Modelo de reporting por mercado",
              "Asesoria senior y planificacion de ejecucion",
            ],
            scopeGuard:
              "El trabajo enterprise y multi-mercado complejo siempre requiere precio personalizado.",
            cta: { label: "Solicitar alcance personalizado", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "websites",
        label: "Desarrollo web",
        eyebrow: "Sitios listos para busqueda",
        title: "Precios de desarrollo web",
        intro:
          "Para empresas que necesitan un sitio rapido, estructurado y listo para convertir, con arquitectura SEO, bases de visibilidad IA, analytics y captura de leads desde el primer dia.",
        subcopy:
          "Los precios son puntos de partida. El alcance final depende del numero de paginas, profundidad de contenido, integraciones, complejidad de migracion, requisitos multilingues y calendario.",
        plans: [
          {
            id: "website-launch",
            name: "Website Launch",
            price: "Desde $3,500 one-time",
            positioning:
              "Un sitio profesional listo para busqueda para nuevas empresas que necesitan una base correcta antes de escalar contenido o campanas.",
            bestFor: [
              "Nuevas empresas que necesitan un sitio profesional listo para busqueda",
              "Sitios de servicios enfocados",
              "Fundadores que reemplazan un sitio inicial limitado",
            ],
            includes: [
              "4-6 paginas principales",
              "Estrategia web y sitemap",
              "UX/UI responsive",
              "Estructura de paginas lista para busqueda",
              "Setup SEO on-page basico",
              "Metadatos principales",
              "Schema basico",
              "Formulario de contacto / lead",
              "Analytics y consent readiness",
              "QA de lanzamiento",
            ],
            scopeGuard:
              "Ideal para lanzamientos enfocados. Mas paginas, integraciones a medida, multilingue y migracion requieren un alcance mayor.",
            cta: { label: "Empezar un proyecto web", href: "/contact" },
          },
          {
            id: "growth-website",
            name: "Growth Website",
            price: "Desde $6,500 one-time",
            recommended: true,
            positioning:
              "El build recomendado para empresas que necesitan SEO, visibilidad IA y generacion de leads desde el primer dia.",
            bestFor: [
              "Empresas que necesitan SEO, visibilidad IA y generacion de leads desde el primer dia",
              "Marcas B2B o de servicios con varias ofertas",
              "Equipos que preparan crecimiento SEO continuo",
            ],
            includes: [
              "8-12 paginas estrategicas",
              "Mapeo keyword-a-pagina",
              "Arquitectura de paginas de servicio",
              "Diseno UX/UI",
              "Desarrollo responsive",
              "Base SEO/GEO",
              "Schema y estructura de enlazado interno",
              "Flujo de captura de leads",
              "Preparacion Cal.com",
              "Preparacion Resend",
              "Eventos analytics listos",
              "Optimizacion de performance",
              "QA de lanzamiento",
            ],
            cta: { label: "Empezar un proyecto web", href: "/contact" },
          },
          {
            id: "seo-rebuild-migration",
            name: "SEO Rebuild + Migration",
            price: "Desde $9,500 one-time",
            positioning:
              "Un camino de rediseno para sitios existentes que necesitan mejor UX y performance sin perder valor search.",
            bestFor: [
              "Sitios existentes que necesitan rediseno sin perder valor search",
              "Sitios con deuda tecnica o arquitectura debil",
              "Equipos que preparan cambios de URL, CMS o framework",
            ],
            includes: [
              "Auditoria tecnica del sitio",
              "Inventario de URLs",
              "Mapeo de redirecciones",
              "Limpieza de estructura de contenido",
              "Plan de migracion SEO",
              "Rebuild / redesign",
              "Optimizacion de performance",
              "Limpieza de schema",
              "Control de indexacion",
              "Continuidad analytics",
              "QA pre-lanzamiento y post-lanzamiento",
            ],
            scopeGuard:
              "El riesgo de migracion se define tras inventario. Sitios grandes, cambios CMS y redirecciones multilingues pueden requerir precio personalizado.",
            cta: { label: "Planificar un rebuild seguro", href: "/book-a-call" },
          },
          {
            id: "custom-growth-platform",
            name: "Custom Growth Platform",
            price: "Personalizado, desde $15,000+",
            positioning:
              "Sistemas web personalizados para builds multilingues, CMS, CRM, multi-ubicacion o con integraciones complejas.",
            bestFor: [
              "Builds complejos, multilingues, CMS, CRM o multi-ubicacion",
              "Content hubs y sistemas Insights",
              "Empresas con workflows o enrutamiento de leads avanzados",
            ],
            includes: [
              "Sitio multilingue",
              "Content hub / sistema Insights",
              "Workflow CMS/admin",
              "Preparacion integracion CRM / HubSpot",
              "Enrutamiento avanzado de leads",
              "Dashboards personalizados",
              "Arquitectura multi-ubicacion",
              "Integracion booking/pagos",
              "Migracion compleja",
              "Setup Cloudflare/hosting personalizado",
            ],
            cta: { label: "Solicitar alcance personalizado", href: "/book-a-call" },
          },
        ],
        notes: [
          "Website Care empieza desde $199/mes.",
          "Growth Support empieza desde $750/mes.",
          "Consulta el servicio Desarrollo web para ver entregables, QA de lanzamiento y detalles del sistema de crecimiento.",
        ],
        cta: { label: "Ver servicio Desarrollo web", href: "/services/website-development" },
      },
      {
        id: "mentor",
        label: "SEO Mentor",
        eyebrow: "Asesoria senior",
        title: "Precios de SEO Mentor",
        intro:
          "SEO Mentor es para equipos que quieren criterio SEO senior sin entregar cada tarea a una agencia.",
        subcopy:
          "Usalo para validar estrategia, revisar decisiones tecnicas y de contenido, formar equipos internos y crear un ritmo operativo de crecimiento search.",
        plans: [
          {
            id: "mentor-office-hours",
            name: "SEO Mentor Office Hours",
            price: "Desde $1,000/mes",
            positioning:
              "Feedback senior enfocado para fundadores, marketers y equipos pequenos que ejecutan SEO internamente.",
            bestFor: [
              "Fundador o marketer haciendo SEO internamente",
              "Equipo pequeno que necesita feedback senior",
              "Revision de decisiones SEO prioritarias",
            ],
            includes: [
              "1 sesion mensual de estrategia",
              "Preguntas SEO asincronas",
              "Revision de decisiones SEO prioritarias",
              "Revision de 1-2 paginas o briefs clave/mes",
              "Guia ligera tecnica/contenido/AI Search",
              "Lista mensual de acciones",
            ],
            scopeGuard:
              "Solo asesoria. No incluye implementacion, redaccion, desarrollo ni gestion de campanas.",
            minimum: "Minimo de 3 meses",
            cta: { label: "Empezar mentoria", href: "/book-a-call" },
          },
          {
            id: "mentor-growth-advisory",
            name: "SEO Mentor Growth Advisory",
            price: "Desde $1,500/mes",
            recommended: true,
            positioning:
              "El plan mentor recomendado para equipos con capacidad interna pero priorizacion SEO poco clara.",
            bestFor: [
              "Marketer interno o fundador que necesita guia SEO continua",
              "Equipo con capacidad de contenido/dev pero priorizacion poco clara",
              "Empresa que quiere roadmap y soporte de decision",
            ],
            includes: [
              "2 sesiones mensuales de estrategia/asesoria",
              "Revision de roadmap SEO",
              "Revision de prioridades tecnicas SEO",
              "Revision de estrategia de contenido y briefs",
              "Guia AI Search / entidades",
              "Revision de enlazado interno y autoridad",
              "Memo mensual de decisiones",
              "Soporte asincrono de revision",
            ],
            cta: { label: "Elegir Growth Advisory", href: "/book-a-call" },
          },
          {
            id: "mentor-team-enablement",
            name: "SEO Mentor Team Enablement",
            price: "Desde $2,500/mes",
            positioning:
              "Formacion, QA y procesos para equipos internos de contenido, SEO y desarrollo.",
            bestFor: [
              "Equipos de contenido",
              "SEO interno junior/mid-level",
              "Equipo dev mas marketing que necesita proceso SEO",
              "Empresa que quiere capacidad interna",
            ],
            includes: [
              "2-3 workshops/revisiones mensuales",
              "Curriculum de formacion de equipo",
              "QA de briefs de contenido",
              "QA tecnica SEO",
              "Setup de workflow SEO",
              "Estandares editoriales",
              "Proceso de enlazado interno",
              "Revision de medicion",
              "Modulo de formacion AI Search",
              "Soporte office-hours",
            ],
            cta: { label: "Habilitar el equipo", href: "/book-a-call" },
          },
          {
            id: "executive-advisory",
            name: "Executive Search Advisory",
            price: "Desde $4,500/mes",
            positioning:
              "Direccion senior de crecimiento search para ejecutivos que deciden presupuesto, equipo, vendors y expansion.",
            bestFor: [
              "CMO",
              "Fundador",
              "Head of growth",
              "Empresa multi-mercado",
              "Liderazgo decidiendo agencia/in-house/hibrido",
            ],
            includes: [
              "Sesion mensual ejecutiva",
              "Revision de oportunidad de crecimiento search",
              "Priorizacion de roadmap",
              "Revision de agencias/vendors",
              "Guia de hiring y estructura de equipo",
              "Revision de medicion y KPI",
              "Guia de expansion de mercado",
              "Resumen listo para leadership",
            ],
            cta: { label: "Reservar Executive Advisory", href: "/book-a-call" },
          },
          {
            id: "custom-mentorship",
            name: "Custom SEO Mentorship",
            price: "Personalizado",
            positioning:
              "Asesoria personalizada para multi-mercado, enterprise, formacion, migracion, PPC o AI Search.",
            bestFor: [
              "Asesoria multi-mercado",
              "Construccion de equipo SEO interno",
              "Programa de formacion corporativa",
              "Asesoria SEO mas PPC mas AI Search",
              "Programa trimestral de workshops",
              "Asesoria de migracion",
              "Gobernanza enterprise",
            ],
            includes: [
              "Cadencia de asesoria personalizada",
              "Planificacion de workshops",
              "Modelo de gobernanza y QA",
              "Enablement de liderazgo y equipo",
            ],
            cta: { label: "Solicitar mentoria personalizada", href: "/book-a-call" },
          },
        ],
      },
      {
        id: "audits",
        label: "Auditorias & Add-ons",
        eyebrow: "Diagnosticos y soporte de canal",
        title: "Precios de auditorias, PPC y add-ons",
        intro:
          "Las auditorias aclaran el alcance correcto. Los add-ons apoyan demanda pagada, planificacion de contenido, proyectos tecnicos, localizacion y autoridad.",
        plans: [
          {
            id: "free-audit",
            name: "Auditoria SEO gratuita",
            price: "$0",
            positioning:
              "Diagnostico rapido para entender si Local, Nacional, Global, Mentor, PPC o personalizado encaja.",
            bestFor: ["No sabes por donde empezar", "Necesitas priorizacion inicial", "Quieres camino hacia precio exacto"],
            includes: ["Revision de sitio y mercado", "Problemas prioritarios", "Siguiente alcance recomendado"],
            cta: { label: "Obtener auditoria gratuita", href: "/free-seo-audit" },
          },
          {
            id: "search-growth-audit",
            name: "Search Growth Audit",
            price: "Desde $1,500 one-time",
            positioning: "Auditoria enfocada en demanda, contenido, tecnica y fit comercial search.",
            bestFor: ["Planificacion growth", "Claridad de roadmap", "Priorizacion antes del mensual"],
            includes: ["Revision de demanda search", "Roadmap priorizado", "Recomendacion de alcance"],
            cta: { label: "Empezar con auditoria", href: "/work/sample-audits" },
          },
          {
            id: "technical-audit",
            name: "Technical SEO Audit",
            price: "Desde $2,500 one-time",
            positioning: "Revision tecnica de crawl, indexacion, renderizado, arquitectura y riesgo de rendimiento.",
            bestFor: ["Sitios complejos", "Problemas CMS o framework", "Preparacion de migracion"],
            includes: ["Mapa de problemas tecnicos", "Arreglos prioritarios", "Recomendaciones listas para implementar"],
            cta: { label: "Ver auditorias de muestra", href: "/work/sample-audits" },
          },
          {
            id: "ai-search-review",
            name: "AI Search Visibility Review",
            price: "Desde $1,500 one-time",
            positioning: "Revision de claridad de entidad, readiness para respuestas, citas y coherencia de fuentes.",
            bestFor: ["Visibilidad en respuestas IA", "Coherencia de entidad", "Gaps de autoridad de contenido"],
            includes: ["Snapshot de readiness IA", "Revision de entidad y citas", "Lista de acciones"],
            cta: { label: "Revisar visibilidad IA", href: "/work/sample-audits/ai-search-visibility-review" },
          },
          {
            id: "ppc-organic-review",
            name: "PPC + Organic Intelligence Review",
            price: "Desde $2,500 one-time",
            positioning: "Revision paid y organic para encontrar captura de demanda, desperdicio y solapamiento.",
            bestFor: ["Equipos paid search", "Planificacion SEO mas SEM", "Solapamiento de keywords y landing pages"],
            includes: ["Revision de queries paid/organic", "Mapa de oportunidad de landing pages", "Inteligencia de presupuesto"],
            cta: { label: "Revisar PPC + organic", href: "/work/sample-audits/ppc-organic-intelligence" },
          },
          {
            id: "international-market-map",
            name: "International SEO Market Map",
            price: "Desde $3,500 one-time",
            positioning: "Mapa de mercado para expansion multi-pais, multilingue o regional.",
            bestFor: ["Expansion USA, Canada, Australia", "Decisiones idioma/mercado", "Planificacion de localizacion"],
            includes: ["Mapa de intencion por mercado", "Revision tecnica de localizacion", "Roadmap de mercados prioritarios"],
            cta: { label: "Mapear SEO internacional", href: "/work/sample-audits/international-seo-market-map" },
          },
          {
            id: "ppc-management",
            name: "PPC Management",
            price: "Desde $1,500/mes o 10-12% del ad spend, lo que sea mayor",
            positioning: "Gestion paid search alineada con inteligencia organica y demanda comercial.",
            bestFor: ["Captura rapida de demanda pagada", "Alineacion search y PPC", "Control de presupuesto"],
            includes: ["Revision de estructura de campana", "Inteligencia de queries search", "Recomendaciones de landing pages", "Reporting mensual"],
            scopeGuard: "El ad spend no esta incluido.",
            cta: { label: "Hablar del alcance PPC", href: "/book-a-call" },
          },
          {
            id: "content-cluster-planning",
            name: "Content Cluster Planning",
            price: "Desde $1,500/proyecto",
            positioning: "Planificacion de topic clusters, briefs y direccion de enlazado interno.",
            bestFor: ["Equipos editoriales", "Construccion de autoridad", "Planificacion de contenido"],
            includes: ["Mapa de topic cluster", "Direccion de briefs", "Oportunidades de enlazado interno"],
          },
          {
            id: "digital-pr-authority",
            name: "Digital PR / Authority Campaign",
            price: "Desde $3,000/proyecto",
            positioning: "Planificacion de autoridad y soporte digital PR sin links o placements garantizados.",
            bestFor: ["Campanas de autoridad", "Contenido experto", "Soporte de prueba y citas"],
            includes: ["Revision de angulos de campana", "Mapa de oportunidades de autoridad", "Planificacion outreach"],
            scopeGuard: "Digital PR no incluye links garantizados ni placements garantizados.",
          },
          {
            id: "technical-project",
            name: "Technical SEO Project",
            price: "Desde $2,500/proyecto",
            positioning: "Soporte tecnico SEO acotado para problemas especificos o plan de implementacion.",
            bestFor: ["Deuda tecnica", "Cambios CMS", "Soporte de migracion"],
            includes: ["Diagnostico de problema", "Priorizacion de arreglos", "Recomendaciones listas para developers"],
          },
          {
            id: "localization-support",
            name: "Localization / International SEO Support",
            price: "Personalizado",
            positioning: "Soporte personalizado para idioma, pais, hreflang, localizacion de contenido y expansion.",
            bestFor: ["SEO multilingue", "Rollout multi-pais", "Estrategia regional de contenido"],
            includes: ["Revision de localizacion", "Mapeo pais/idioma", "QA SEO internacional"],
          },
        ],
        notes: [
          "El ad spend no esta incluido.",
          "Digital PR no incluye links garantizados ni placements garantizados.",
          "Las auditorias pueden definir el alcance mensual correcto.",
        ],
        cta: { label: "Empezar con auditoria", href: "/free-seo-audit" },
      },
    ],
  },
  comparison: {
    eyebrow: "Comparacion",
    title: "Compara todos los alcances de partida.",
    description:
      "Usa esta tabla para ver diferencias antes de pedir una cotizacion exacta.",
    contextTitle: "Compara la via de precios seleccionada.",
    contextDescription:
      "Cada vista mantiene la comparacion cerca de la pestana que estas revisando. Abre la comparacion completa solo cuando necesites todos los alcances lado a lado.",
    fullComparisonLabel: "Ver comparacion completa",
    hideFullComparisonLabel: "Ocultar comparacion completa",
    columns: [
      { id: "localStarter", label: "Local SEO Starter" },
      { id: "nationalFoundation", label: "National SEO Foundation" },
      { id: "nationalGrowth", label: "National SEO Growth" },
      { id: "globalExpansion", label: "Global SEO Expansion" },
      { id: "mentorGrowth", label: "SEO Mentor Growth" },
      { id: "enterpriseCustom", label: "Enterprise Custom" },
    ],
    rows: [
      {
        label: "Ideal para",
        values: {
          localStarter: "Una ubicacion o zona de servicio",
          nationalFoundation: "Roadmap de un pais",
          nationalGrowth: "Ejecucion growth seria",
          globalExpansion: "Expansion multi-pais",
          mentorGrowth: "Guia para equipo interno",
          enterpriseCustom: "Sistemas multi-mercado complejos",
        },
      },
      {
        label: "Alcance de mercado",
        values: {
          localStarter: "Local",
          nationalFoundation: "Un pais",
          nationalGrowth: "Un pais",
          globalExpansion: "Varios paises/idiomas",
          mentorGrowth: "Depende del equipo",
          enterpriseCustom: "Enterprise / multi-mercado",
        },
      },
      {
        label: "Ejecucion incluida",
        values: {
          localStarter: "Guia y checklist enfocadas",
          nationalFoundation: "Enfocado en roadmap",
          nationalGrowth: "Planificacion y QA de ejecucion",
          globalExpansion: "Planificacion multi-mercado",
          mentorGrowth: "Asesoria, no implementacion",
          enterpriseCustom: "Segun alcance",
        },
      },
      {
        label: "Asesoria incluida",
        values: {
          localStarter: "Ligera",
          nationalFoundation: "Mensual",
          nationalGrowth: "Revision estrategica mensual",
          globalExpansion: "Asesoria por mercado",
          mentorGrowth: "Servicio principal",
          enterpriseCustom: "Asesoria senior",
        },
      },
      {
        label: "SEO tecnico",
        values: {
          localStarter: "Revision basica",
          nationalFoundation: "Revision y roadmap",
          nationalGrowth: "Roadmap y QA",
          globalExpansion: "Revision tecnica internacional",
          mentorGrowth: "Revision prioritaria",
          enterpriseCustom: "Avanzado",
        },
      },
      {
        label: "Estrategia de contenido",
        values: {
          localStarter: "Revision limitada de pagina local",
          nationalFoundation: "Gaps y clusters",
          nationalGrowth: "Planificacion de autoridad",
          globalExpansion: "Estrategia de localizacion",
          mentorGrowth: "Revision de briefs y estrategia",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "Readiness AI Search",
        values: {
          localStarter: "Recomendaciones ligeras",
          nationalFoundation: "Snapshot",
          nationalGrowth: "Optimizacion incluida",
          globalExpansion: "Revision de coherencia de entidad",
          mentorGrowth: "Guia incluida",
          enterpriseCustom: "Gobernanza personalizada",
        },
      },
      {
        label: "Google Business Profile",
        values: {
          localStarter: "Incluido",
          nationalFoundation: "Si aplica",
          nationalGrowth: "Si aplica",
          globalExpansion: "Si los mercados locales importan",
          mentorGrowth: "Asesoria si hace falta",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "SEO local",
        values: {
          localStarter: "Foco principal",
          nationalFoundation: "Alcance de soporte",
          nationalGrowth: "Alcance de soporte",
          globalExpansion: "Por mercado",
          mentorGrowth: "Asesoria si hace falta",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "SEO internacional",
        values: {
          localStarter: "No incluido",
          nationalFoundation: "No incluido",
          nationalGrowth: "Limitado",
          globalExpansion: "Foco principal",
          mentorGrowth: "Disponible segun alcance",
          enterpriseCustom: "Central cuando aplica",
        },
      },
      {
        label: "Inteligencia PPC",
        values: {
          localStarter: "No incluido",
          nationalFoundation: "Opcional",
          nationalGrowth: "Recomendaciones",
          globalExpansion: "Opcional",
          mentorGrowth: "Disponible segun alcance",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "Formacion de equipo",
        values: {
          localStarter: "No incluida",
          nationalFoundation: "Ligera",
          nationalGrowth: "Opcional",
          globalExpansion: "Opcional",
          mentorGrowth: "Disponible segun alcance",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "Reporting",
        values: {
          localStarter: "Simple",
          nationalFoundation: "Mensual",
          nationalGrowth: "Reporting de inteligencia search",
          globalExpansion: "Por mercado",
          mentorGrowth: "Memo de decisiones",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "Cadencia de revision",
        values: {
          localStarter: "Checklist mensual",
          nationalFoundation: "Mensual",
          nationalGrowth: "Revision estrategica mensual",
          globalExpansion: "Mensual / por mercado",
          mentorGrowth: "2 sesiones/mes",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "Termino minimo",
        values: {
          localStarter: "3 meses",
          nationalFoundation: "Depende del alcance",
          nationalGrowth: "Depende del alcance",
          globalExpansion: "Depende del alcance",
          mentorGrowth: "Depende del alcance",
          enterpriseCustom: "Personalizado",
        },
      },
      {
        label: "Precio de partida",
        values: {
          localStarter: "Desde $1,000/mes",
          nationalFoundation: "Desde $2,500/mes",
          nationalGrowth: "Desde $4,500/mes",
          globalExpansion: "Desde $7,500/mes",
          mentorGrowth: "Desde $1,500/mes",
          enterpriseCustom: "Personalizado desde $12,000/mes",
        },
      },
    ],
    exactPricingNote:
      "Necesitas precio exacto? Solicita una auditoria gratuita o reserva una llamada estrategica. Recomendaremos el alcance mas pequeno que pueda apoyar tus objetivos de forma realista.",
  },
  decisionGuide: {
    eyebrow: "Guia de decision",
    title: "No estas seguro? Elige tu situacion.",
    description:
      "Elige la situacion mas cercana y el selector de precios ira al punto de partida correcto.",
    ariaLabel: "Elegir situacion de precios",
    paths: [
      {
        id: "local-visibility",
        tabId: "local",
        trigger: "Necesito visibilidad local",
        planName: "Local SEO Starter",
        startingPrice: "Desde $1,000/mes",
        why: "Una base local enfocada suele bastar cuando hay una ubicacion principal, una zona de servicio y poca complejidad tecnica.",
        cta: { label: "Obtener auditoria local", href: "/free-seo-audit" },
      },
      {
        id: "national-demand",
        tabId: "national",
        trigger: "Quiero demanda nacional",
        planName: "National SEO Growth System",
        startingPrice: "Desde $4,500/mes",
        why: "La demanda nacional suele requerir un mapa search mas fuerte, roadmap tecnico, autoridad de contenido, AI Search y reporting juntos.",
        cta: { label: "Hablar del growth system", href: "/book-a-call" },
      },
      {
        id: "cross-country",
        tabId: "global",
        trigger: "Vendo en varios paises",
        planName: "Global SEO Expansion",
        startingPrice: "Desde $7,500/mes",
        why: "Multi-pais requiere arquitectura, intencion de mercado, QA de localizacion y reporting por mercado.",
        cta: { label: "Planificar alcance global", href: "/book-a-call" },
      },
      {
        id: "search-ready-website",
        tabId: "websites",
        trigger: "Necesito un sitio listo para busqueda",
        planName: "Growth Website",
        startingPrice: "Desde $6,500 one-time",
        why: "Un sitio listo para crecimiento debe conectar arquitectura de paginas, SEO tecnico, datos estructurados, captura de leads y analytics antes del lanzamiento.",
        cta: { label: "Empezar un proyecto web", href: "/contact" },
      },
      {
        id: "senior-guidance",
        tabId: "mentor",
        trigger: "Necesito guia SEO senior",
        planName: "SEO Mentor Growth Advisory",
        startingPrice: "Desde $1,500/mes",
        why: "Tu equipo puede ejecutar, pero priorizacion senior, revision tecnica, QA de contenido y soporte de decision reducen trabajo perdido.",
        cta: { label: "Empezar mentoria", href: "/book-a-call" },
      },
      {
        id: "audit-first",
        tabId: "audits",
        trigger: "Quiero empezar con una auditoria",
        planName: "Auditoria SEO gratuita",
        startingPrice: "$0",
        why: "Un diagnostico puede identificar el alcance realista mas pequeno antes de comprometerte con un programa mensual.",
        cta: { label: "Auditoria SEO gratuita", href: "/free-seo-audit" },
      },
    ],
  },
  drivers: {
    eyebrow: "Factores de precio final",
    title: "Que afecta el precio final?",
    description:
      "Los precios anteriores son puntos de partida. El precio mas preciso llega despues de entender tu sitio, mercado, competencia y necesidades de ejecucion.",
    items: [
      { label: "Numero de ubicaciones", description: "Mas ubicaciones agregan GBP, paginas locales, reporting y reputacion." },
      { label: "Numero de paises/idiomas", description: "Mas mercados requieren localizacion, revisiones tecnicas y mapeo de intencion." },
      { label: "Tamano del sitio", description: "Sitios grandes requieren crawl, arquitectura, enlazado interno y QA mas profundos." },
      { label: "Deuda tecnica", description: "Indexacion, renderizado, velocidad, duplicacion y migraciones aumentan complejidad." },
      { label: "Complejidad CMS", description: "CMS custom, headless y limites de workflow afectan velocidad de ejecucion." },
      { label: "Produccion de contenido", description: "Estrategia sola difiere de redaccion, edicion, actualizaciones y QA." },
      { label: "Nivel de competencia", description: "SERPs dificiles necesitan mas autoridad, profundidad de contenido, calidad tecnica y paciencia." },
      { label: "Necesidades de autoridad/links", description: "Digital PR y autoridad se presupuestan aparte y nunca garantizan placements." },
      { label: "Spend PPC", description: "Mas spend exige mas estructura, revision de queries y QA de conversion." },
      { label: "Reporting/analytics", description: "Analytics o CRM desordenados requieren limpieza antes de reportar con confianza." },
      { label: "Soporte interno", description: "Writers, developers, marketers y ejecutivos disponibles cambian el modelo." },
      { label: "Velocidad de ejecucion", description: "Tiempos rapidos requieren mas tiempo senior y ciclos mas estrechos." },
    ],
  },
  includedExcluded: {
    eyebrow: "Claridad de alcance",
    title: "Incluido vs no incluido salvo que se alcance.",
    description:
      "Taskcover mantiene claros los alcances iniciales para que los planes de entrada no parezcan campanas full-service.",
    includedTitle: "Incluido por alcance",
    excludedTitle: "No incluido salvo que se alcance",
    included: [
      "Estrategia SEO",
      "Revision tecnica",
      "Mapa de demanda search",
      "Roadmap de contenido",
      "Readiness AI Search",
      "Enlazado interno",
      "Arquitectura web cuando se incluye en el alcance",
      "Reporting",
      "Revision mensual",
    ],
    excluded: [
      "Ad spend",
      "Redaccion completa de contenido",
      "Implementacion de desarrollo",
      "Tarifas de placement PR",
      "Backlinks garantizados",
      "Rankings garantizados",
      "Revision legal/compliance",
      "Produccion de traduccion",
      "Implementacion CRM",
      "Desarrollo web personalizado",
      "Herramientas pagadas propiedad del cliente",
    ],
  },
  customScope: {
    eyebrow: "Precio personalizado",
    title: "Necesitas un alcance personalizado?",
    description:
      "Si tu empresa tiene varias ubicaciones, varios mercados, requisitos tecnicos complejos, alto volumen de contenido, paid search o necesidades de equipo interno, construiremos un alcance personalizado despues de un diagnostico.",
    useCases: [
      "SEO multi-ubicacion",
      "SEO enterprise",
      "Migracion de sitio",
      "Desarrollo web",
      "SEO internacional",
      "SEO multilingue",
      "Digital PR",
      "Produccion de contenido",
      "Integracion PPC + SEO",
      "SEO Mentor para equipos internos",
    ],
    primaryCta: { label: "Solicitar precio personalizado", href: "/free-seo-audit" },
    secondaryCta: { label: "Reservar llamada", href: "/book-a-call" },
    note: "Para el precio mas preciso, empieza con una auditoria SEO gratuita o una llamada estrategica.",
  },
  proof: {
    eyebrow: "Prueba",
    title: "Usa trabajo verificado para entender el alcance detras del precio.",
    description:
      "Estos ejemplos muestran distintos sistemas de crecimiento search. Taskcover no inventa metricas ni garantias.",
    groups: [
      { label: "Prueba de SEO local", caseStudySlugs: ["casa-madera", "the-bamboo-bar", "avis"] },
      { label: "Prueba de SEO nacional", caseStudySlugs: ["british-university-vietnam", "matthew-jeffery-law-firm", "skatepro"] },
      { label: "Prueba de SEO global", caseStudySlugs: ["agoda", "ccleaner", "fwd-insurance", "novaworld"] },
    ],
    cta: { label: "Ver todos los casos", href: "/work/case-studies" },
  },
  faq: {
    eyebrow: "FAQ de precios",
    title: "Preguntas antes de elegir alcance.",
    items: [
      { q: "Cual es la diferencia entre SEO local, nacional y global?", a: "SEO local se centra en una ciudad, zona de servicio o ubicaciones. SEO nacional apunta a un mercado pais. SEO global gestiona varios paises, idiomas, localizacion y comportamiento search por mercado." },
      { q: "Por que Local SEO empieza en $1,000/mes?", a: "El plan starter es intencionalmente enfocado: una ubicacion o zona, revision local, guia de Google Business Profile, snapshot competitivo y reporting simple. No es una campana SEO full-service." },
      { q: "Puedo empezar con SEO local y subir despues?", a: "Si. Muchas empresas empiezan con alcance local, luego pasan a multi-ubicacion, nacional, PPC, contenido o tecnico despues del diagnostico y roadmap." },
      { q: "Los proyectos web incluyen SEO?", a: "Si. Los proyectos de Desarrollo web incluyen arquitectura lista para busqueda, metadatos principales, schema cuando aplica, rutas de enlazado interno, performance, captura de leads y preparacion analytics. El contenido SEO continuo y la autoridad se presupuestan aparte." },
      { q: "SEO Mentor es diferente de la ejecucion SEO?", a: "Si. SEO Mentor es asesoria. Ayuda a tu equipo a decidir mejor, revisar prioridades y mejorar proceso. Implementacion, redaccion, desarrollo y gestion de campanas no se incluyen salvo alcance separado." },
      { q: "Para quien es SEO Mentor?", a: "SEO Mentor encaja con fundadores, marketers, equipos SEO internos, equipos de contenido, ejecutivos y empresas con capacidad de ejecucion pero necesidad de direccion SEO senior." },
      { q: "Nuestro equipo interno puede ejecutar mientras Taskcover asesora?", a: "Si. Es el mejor fit para SEO Mentor Growth Advisory y Team Enablement. Taskcover puede revisar roadmaps, briefs, prioridades tecnicas, enlaces internos, AI Search y reporting." },
      { q: "SEO Mentor puede incluir AI Search y PPC?", a: "Si, segun el alcance. AI Search, entidades, calidad de contenido e inteligencia PPC/organic pueden incluirse cuando esas decisiones afectan el crecimiento search." },
      { q: "El ad spend esta incluido en PPC?", a: "No. La gestion PPC empieza desde $1,500/mes o 10-12% del ad spend, lo que sea mayor. El ad spend es separado y lo paga el cliente." },
      { q: "La redaccion de contenido esta incluida?", a: "Estrategia de contenido, planificacion, briefs y QA pueden incluirse segun el plan. Redaccion completa o produccion de alto volumen se presupuesta aparte." },
      { q: "Garantizan rankings?", a: "No. Taskcover no garantiza rankings, backlinks, placements, trafico ni ingresos. Construimos sistemas search, priorizamos el trabajo e informamos con honestidad sobre progreso y restricciones." },
      { q: "Trabajan con USA, Canada y Australia?", a: "Si. Taskcover apoya programas de crecimiento search para USA, Canada y Australia, incluyendo local, nacional y multi-mercado." },
      { q: "Pueden apoyar ingles, frances y espanol?", a: "Si. Taskcover puede apoyar estrategia search, revision de localizacion y SEO internacional en ingles, frances y espanol. La produccion de traduccion se presupuesta aparte." },
      { q: "Cual es el engagement minimo?", a: "Local SEO Starter y SEO Mentor Office Hours tienen minimo de 3 meses. Otros alcances dependen del mercado, la complejidad y las necesidades de ejecucion." },
      { q: "Como obtengo una cotizacion exacta?", a: "Solicita una auditoria SEO gratuita o reserva una llamada estrategica. Taskcover revisara sitio, mercado, competencia y necesidades antes de recomendar el alcance realista mas pequeno." },
    ],
  },
  finalCta: {
    eyebrow: "Siguiente paso",
    title: "No sabes que alcance elegir?",
    description:
      "Envia tu sitio web y objetivos de mercado. Taskcover recomendara el alcance mas pequeno que pueda apoyar tus objetivos de forma realista.",
    primaryCta: { label: "Auditoria SEO gratuita", href: "/free-seo-audit" },
    secondaryCta: { label: "Reservar llamada", href: "/book-a-call" },
  },
  ui: {
    bestFor: "Ideal para",
    includes: "Incluye",
    minimum: "Minimo",
    addOn: "Add-on",
    recommended: "Recomendado",
    scopeGuard: "Limite de alcance",
    notes: "Notas",
    startingPoint: "Punto de partida",
    viewPlan: "Ver plan",
    selectPath: "Elegir via",
    recommendation: "Recomendacion",
    compareRowHeader: "Detalle del plan",
  },
} satisfies PricingContent;
