import type { SampleAudit, SampleAuditSlug, WorkContent } from "../work.types";
import { caseStudyDetails } from "./case-studies";

const disclosure =
  "Entregable de muestra ilustrativo. Demuestra la metodología de Taskcover y no representa un proyecto ni un resultado de cliente específico.";

const sampleOrder: SampleAuditSlug[] = [
  "technical-seo-audit",
  "ai-search-visibility-review",
  "content-gap-map",
  "local-seo-audit",
  "ecommerce-search-architecture",
  "international-seo-market-map",
  "ppc-organic-intelligence",
  "90-day-search-growth-roadmap",
];

function sample(input: {
  slug: SampleAuditSlug;
  title: string;
  shortLabel: string;
  focus: string;
  question: string;
  visual: string;
  inputs: string[];
  answers: string[];
  method: string[];
  findings: string[];
  priority: string[];
  output: string[];
  roadmap: string[];
  services: string[];
  industries: string[];
}): SampleAudit {
  const statuses = ["Crítico", "Alta prioridad", "Revisar", "Monitorear"];
  return {
    id: `sample-${input.slug}`,
    type: "sample-audit",
    slug: input.slug,
    title: input.title,
    shortLabel: input.shortLabel,
    summary: input.focus,
    focus: input.focus,
    buyerQuestion: input.question,
    visualStyle: input.visual,
    eyebrow: "Entregable de muestra",
    permissionStatus: "internal-only",
    verificationStatus: "not-applicable",
    publicDisclosure: true,
    requiredContextComplete: false,
    illustrative: true,
    disclosureText: disclosure,
    inputs: input.inputs.map((label) => ({ label, detail: "Entrada metodológica, no evidencia de cliente." })),
    answers: input.answers,
    method: input.method.map((label, index) => ({
      label,
      detail: ["Recolectar", "Diagnosticar", "Priorizar", "Traducir"][index] ?? "Refinar",
      status: ["Mapeado", "Evaluado", "Priorizado", "Listo para ejecución"][index] ?? "Validado",
    })),
    findings: input.findings.map((label, index) => ({
      label,
      detail: statuses[index % statuses.length],
      status: statuses[index % statuses.length],
    })),
    priority: input.priority.map((label) => ({
      label,
      detail: "Evaluado por impacto, dependencia, confianza y esfuerzo.",
      status: "Priorizado",
    })),
    outputPreview: input.output.map((label) => ({
      label,
      detail: "Estructura de muestra con etiquetas cualitativas.",
      status: "Ilustrativo",
    })),
    roadmap: input.roadmap.map((label) => ({
      label,
      detail: "Convertido en acciones, responsables y decisiones.",
      status: "Listo",
    })),
    relatedServices: input.services,
    relatedIndustries: input.industries,
    deliverables: input.output,
    methodology: input.method,
    faq: [
      {
        q: "¿Es una auditoría real de cliente?",
        a: "No. Es una muestra ilustrativa que muestra cómo Taskcover estructura el análisis y las recomendaciones.",
      },
      {
        q: "¿La misma estructura sirve para un proyecto real?",
        a: "Sí. El trabajo real usa datos verificados, contexto del cliente, reglas de permiso y fuentes de medición.",
      },
      {
        q: "¿Esta muestra promete resultados?",
        a: "No. Explica la lógica de decisión sin afirmar rankings, tráfico, leads, ingresos ni visibilidad en plataformas.",
      },
    ],
    metaTitle: `${input.title} de muestra | Taskcover Agency`,
    metaDescription: `${input.title} ilustrativo que muestra la metodología de Taskcover sin nombres de clientes, métricas falsas ni resultados inventados.`,
  };
}

const samples = {
  "technical-seo-audit": sample({
    slug: "technical-seo-audit",
    title: "Auditoría SEO técnica",
    shortLabel: "SEO técnico",
    focus: "Arquitectura de rastreo, indexación, renderizado, schema y riesgo de lanzamientos traducidos en prioridades.",
    question: "¿Qué restricciones técnicas limitan la búsqueda o crean riesgo futuro?",
    visual: "Arquitectura de rastreo y registro de prioridades",
    inputs: ["Rutas de rastreo", "Estados de indexación", "Renderizado", "Cobertura schema", "Historial de releases"],
    answers: ["Sistemas que requieren atención", "Temas que pueden monitorearse", "Correcciones que desbloquean trabajo"],
    method: ["Escaneo de arquitectura", "Revisión de indexación", "Evaluación de renderizado", "Traducción de riesgo de release"],
    findings: ["Patrón de indexación bloqueado", "Riesgo de renderizado por plantilla", "Schema para revisar", "Dependencia de migración"],
    priority: ["Acceso crítico a búsqueda", "Correcciones de plantilla", "Controles validados", "Cola de monitoreo"],
    output: ["Registro de issues", "Mapa de estados de crawl", "Tabla de schema", "Checklist de release"],
    roadmap: ["Restaurar acceso", "Agrupar cambios", "Validar despliegue", "Monitorear indexación"],
    services: ["technical-seo", "seo-audit", "seo-agency"],
    industries: ["saas-seo", "ecommerce-seo", "travel-seo"],
  }),
  "ai-search-visibility-review": sample({
    slug: "ai-search-visibility-review",
    title: "Revisión de visibilidad en búsqueda con IA",
    shortLabel: "Visibilidad IA",
    focus: "Claridad de entidad, superficies de respuesta, fuentes de cita, contenido estructurado y autoridad.",
    question: "¿La marca es comprensible y citable en entornos de respuestas con IA?",
    visual: "Grafo de entidad y mapa de superficies de respuesta",
    inputs: ["Declaraciones de entidad", "Cobertura de fuentes", "Contenido estructurado", "Autoridad externa", "Páginas listas para respuestas"],
    answers: ["Dónde falta claridad", "Qué fuentes respaldan citas", "Qué formatos de respuesta crear"],
    method: ["Extracción de entidades", "Revisión de fuentes", "Evaluación de formatos", "Mapa de autoridad"],
    findings: ["Relación de entidad incompleta", "Fuente de cita para revisar", "Oportunidad de contenido estructurado", "Dependencia de prueba externa"],
    priority: ["Definición de entidad", "Refuerzo de fuentes", "Producción de respuestas", "Validación de autoridad"],
    output: ["Grafo de entidad", "Matriz de respuestas", "Registro de fuentes", "Roadmap de preparación IA"],
    roadmap: ["Aclarar páginas de entidad", "Reforzar fuentes", "Agregar formatos de respuesta", "Revisar pruebas externas"],
    services: ["ai-search-optimization", "content-marketing", "digital-pr-link-building"],
    industries: ["education-seo", "healthcare-seo", "legal-immigration-seo"],
  }),
  "content-gap-map": sample({
    slug: "content-gap-map",
    title: "Mapa de brechas de contenido",
    shortLabel: "Brechas de contenido",
    focus: "Clusters temáticos, intención, autoridad, contenido de conversión, refrescos y enlaces internos.",
    question: "¿Dónde falta contenido, soporte de autoridad o conexión con la intención del comprador?",
    visual: "Mapa de clusters y matriz de intención",
    inputs: ["Universo temático", "Grupos de intención", "Contenido existente", "Señales de autoridad", "Rutas de conversión"],
    answers: ["Páginas a crear", "Activos a refrescar", "Enlaces internos a cambiar"],
    method: ["Clustering temático", "Mapeo de intención", "Revisión de cobertura", "Alineación con conversión"],
    findings: ["Brecha de decisión", "Tema de autoridad subdesarrollado", "Oportunidad de refresco", "Ruta de enlaces para revisar"],
    priority: ["Temas relevantes al negocio", "Clusters de autoridad", "Cola de refresco", "Páginas de soporte a conversión"],
    output: ["Mapa de clusters", "Matriz de intención", "Registro de cobertura", "Lista de enlaces internos"],
    roadmap: ["Crear brechas prioritarias", "Refrescar activos", "Conectar páginas", "Medir cobertura"],
    services: ["content-marketing", "seo-agency", "seo-audit"],
    industries: ["education-seo", "travel-seo", "saas-seo"],
  }),
  "local-seo-audit": sample({
    slug: "local-seo-audit",
    title: "Auditoría SEO local",
    shortLabel: "SEO local",
    focus: "Presencia local, Google Business Profile, páginas locales, reseñas, citas y rutas de conversión.",
    question: "¿Los compradores locales pueden encontrar, confiar y actuar en cada área de servicio?",
    visual: "Mapa de presencia local y ruta de conversión",
    inputs: ["Páginas locales", "Campos de GBP", "Temas de reseñas", "Consistencia de citas", "Páginas por zona"],
    answers: ["Señales locales a reforzar", "Cobertura débil", "Rutas de conversión a mejorar"],
    method: ["Revisión de presencia", "Chequeo GBP", "Clasificación de reseñas", "Arquitectura local"],
    findings: ["Brecha de contenido local", "Perfil para revisar", "Citas inconsistentes", "Fricción de conversión"],
    priority: ["Señales de ubicación", "Páginas de servicio", "Sistema de reseñas", "Limpieza de rutas"],
    output: ["Mapa de presencia", "Marco GBP", "Tabla de citas", "Ruta local"],
    roadmap: ["Normalizar datos", "Mejorar páginas", "Fortalecer reseñas", "Validar rutas de contacto"],
    services: ["local-seo", "seo-audit", "content-marketing"],
    industries: ["franchise-local-seo", "healthcare-seo", "legal-immigration-seo"],
  }),
  "ecommerce-search-architecture": sample({
    slug: "ecommerce-search-architecture",
    title: "Revisión de arquitectura de búsqueda eCommerce",
    shortLabel: "Arquitectura eCommerce",
    focus: "Jerarquía de categorías, descubrimiento de productos, facetas, intención de compra y enlaces internos.",
    question: "¿Motores y compradores recorren el catálogo sin desperdicio ni confusión?",
    visual: "Árbol de categorías y mapa de riesgo de facetas",
    inputs: ["Árbol de categorías", "Jerarquía producto", "Reglas de facetas", "Intención de compra", "Rutas de merchandising"],
    answers: ["Categorías a consolidar", "Facetas con riesgo", "Relación entre intención y arquitectura"],
    method: ["Revisión de catálogo", "Clasificación de facetas", "Mapeo intención-categoría", "Revisión de enlaces"],
    findings: ["Control de facetas para revisar", "Profundidad desequilibrada", "Dependencia de producto", "Desalineación de intención"],
    priority: ["Control indexable", "Categorías prioritarias", "Arquitectura producto", "Ruta de merchandising"],
    output: ["Árbol de categorías", "Registro de facetas", "Mapa de intención", "Arquitectura de enlaces"],
    roadmap: ["Controlar indexación", "Reformar categorías clave", "Conectar productos y guías", "Medir calidad de crawl"],
    services: ["ecommerce-seo", "technical-seo", "content-marketing"],
    industries: ["ecommerce-seo", "travel-seo", "saas-seo"],
  }),
  "international-seo-market-map": sample({
    slug: "international-seo-market-map",
    title: "Mapa de mercado SEO internacional",
    shortLabel: "Mapa internacional",
    focus: "Prioridades país/idioma, profundidad de localización, hreflang, intención regional y secuencia de despliegue.",
    question: "¿Qué mercados deben servirse primero y qué profundidad de localización requieren?",
    visual: "Matriz país-idioma y tablero de despliegue",
    inputs: ["Países objetivo", "Cobertura de idioma", "Intención regional", "Estructura hreflang", "Recursos de localización"],
    answers: ["Mercados listos", "Necesidades de localización", "Señales técnicas a corregir"],
    method: ["Revisión de mercado", "Mapeo de idioma", "Arquitectura hreflang", "Secuencia de rollout"],
    findings: ["Localización insuficiente", "Hreflang para revisar", "Desajuste regional", "Dependencia de rollout"],
    priority: ["Preparación de mercado", "Arquitectura de idioma", "Contenido regional", "Validación técnica"],
    output: ["Matriz país-idioma", "Tablero de localización", "Arquitectura hreflang", "Secuencia de rollout"],
    roadmap: ["Elegir mercados", "Corregir arquitectura", "Crear contenido regional", "Validar señales"],
    services: ["international-seo", "technical-seo", "content-marketing"],
    industries: ["travel-seo", "education-seo", "saas-seo"],
  }),
  "ppc-organic-intelligence": sample({
    slug: "ppc-organic-intelligence",
    title: "Revisión de inteligencia PPC + orgánica",
    shortLabel: "PPC + orgánico",
    focus: "Intención compartida, superposición paid/organic, páginas de destino, tracking y lógica presupuestaria.",
    question: "¿Dónde deberían paid y orgánico compartir inteligencia en vez de competir a ciegas?",
    visual: "Mapa de intención compartida y registro de superposición",
    inputs: ["Términos de búsqueda", "Objetivos orgánicos", "Landing pages", "Tracking de conversión", "Alineación de mensaje"],
    answers: ["Dónde paid informa SEO", "Dónde orgánico reduce desperdicio", "Qué páginas alinear antes de escalar"],
    method: ["Clasificación de intención", "Revisión de superposición", "Alineación de landing", "Chequeo de tracking"],
    findings: ["Oportunidad de intención compartida", "Landing desalineada", "Tracking para revisar", "Brecha orgánica"],
    priority: ["Términos de alta intención", "Correcciones de landing", "Validación de tracking", "Soporte de contenido orgánico"],
    output: ["Mapa de intención", "Tabla paid-organic", "Tablero de alineación", "Lógica de prioridad presupuestaria"],
    roadmap: ["Clasificar términos", "Alinear páginas", "Validar tracking", "Usar aprendizajes PPC"],
    services: ["ppc-management", "seo-agency", "content-marketing"],
    industries: ["saas-seo", "ecommerce-seo", "education-seo"],
  }),
  "90-day-search-growth-roadmap": sample({
    slug: "90-day-search-growth-roadmap",
    title: "Roadmap de crecimiento en búsqueda de 90 días",
    shortLabel: "Roadmap 90 días",
    focus: "Secuencia, responsables, dependencias, medición y decisiones para 30/60/90 días.",
    question: "¿Qué debe hacerse primero, después y luego sin prometer rankings en un plazo fijo?",
    visual: "Tablero 30/60/90 y mapa de dependencias",
    inputs: ["Hallazgos de auditoría", "Prioridades del negocio", "Capacidad del equipo", "Dependencias", "Preparación de medición"],
    answers: ["Acciones iniciales", "Responsables por carril", "Decisiones necesarias antes de ejecutar"],
    method: ["Síntesis de hallazgos", "Mapeo de dependencias", "Plan por responsables", "Diseño de medición"],
    findings: ["Dependencia crítica", "Responsable por confirmar", "Brecha de confianza de medición", "Decisión requerida"],
    priority: ["Primeros 30 días", "Días 31-60", "Días 61-90", "Siguiente decisión"],
    output: ["Tablero de ejecución", "Carriles de responsables", "Mapa de dependencias", "Plan de medición"],
    roadmap: ["Estabilizar fundamentos", "Crear activos", "Validar implementación", "Revisar y ajustar"],
    services: ["seo-agency", "seo-audit", "seo-mentor-service"],
    industries: ["saas-seo", "travel-seo", "franchise-local-seo"],
  }),
} satisfies Record<SampleAuditSlug, SampleAudit>;

export const work: WorkContent = {
  ui: {
    home: "Inicio",
    work: "Proyectos",
    breadcrumb: "Miga de pan",
    disclosureLabel: "Aviso",
    illustrativeSample: "Muestra ilustrativa",
    verifiedCaseStudy: "Caso verificado",
    verifiedClientResult: "Resultado verificado",
    confidentialEngagement: "Proyecto confidencial",
    privateReference: "Referencia privada",
    noPublicCaseStudiesTitle: "No se muestran casos con nombres sin evidencia verificada.",
    noPublicResultsTitle: "No se muestran resultados públicos sin contexto de medición verificado.",
    noPublicRegistryBody:
      "Taskcover publica solo registros con permiso público verificado, evidencia verificada, contexto completo, divulgación pública y redacción aprobada.",
    publicRegistry: "Registro público",
    evidenceRequired: "Evidencia requerida",
    measurementContext: "Contexto de medición",
    explore: "Explorar",
    viewSample: "Ver muestra",
    getAudit: "Obtener auditoría SEO gratuita",
    bookCall: "Reservar llamada estratégica",
    relatedSamples: "Entregables relacionados",
    relatedServices: "Servicios relacionados",
    relatedIndustries: "Sectores relacionados",
    priority: "Prioridad",
    status: "Estado",
    input: "Entrada",
    method: "Método",
    output: "Salida",
    overview: "Resumen",
    clientBackground: "Contexto del cliente",
    challenge: "Desafío",
    objectives: "Objetivos",
    strategy: "Estrategia",
    execution: "Ejecución",
    servicesDelivered: "Servicios entregados",
    results: "Resultados",
    keyMetrics: "Métricas clave",
    visualGallery: "Galería visual",
    keyLearning: "Aprendizaje clave",
    relatedMarkets: "Mercados relacionados",
    finalCta: "Siguiente paso",
    readCase: "Leer el caso completo",
    viewCaseStudy: "Ver caso de estudio",
    filterIndustry: "Filtrar por industria",
    filterMarket: "Filtrar por mercado",
    filterService: "Filtrar por servicio",
    clearFilters: "Limpiar filtros",
    resultCount: "{count} casos verificados",
    caseStudyLibrary: "Biblioteca de casos verificados",
    featuredCaseStudy: "Caso destacado",
    verifiedOutcomesByGrowthLever: "Resultados verificados por palanca de crecimiento",
    serviceToProofMap: "Mapa servicio-prueba",
    usedInCaseStudies: "Usado en {count} casos",
    viewService: "Ver servicio",
    viewRelatedCases: "Ver casos relacionados",
    growthLever: "Palanca de crecimiento",
    metricContext: "Contexto de la métrica",
    caseToResultMatrix: "Matriz caso-resultado",
    resultCategories: "Categorías de resultado",
    industryMarketDistribution: "Distribución por industria y mercado",
    resultHighlights: "Resultados verificados destacados",
    relatedProof: "Prueba relacionada",
    allCases: "Todos los casos",
    client: "Cliente",
    focus: "Enfoque",
    period: "Periodo",
    startingPoint: "Punto de partida",
    workstream: "Flujo de trabajo",
  },
  channelLinks: [
    { label: "Casos de estudio", href: "/work/case-studies", description: "Registro futuro para historias de clientes cuando la evidencia esté aprobada." },
    { label: "Auditorías de muestra", href: "/work/sample-audits", description: "Entregables ilustrativos que muestran cómo Taskcover piensa y estructura el trabajo." },
    { label: "Marcos de crecimiento", href: "/work/search-growth-frameworks", description: "Modelo operativo que transforma investigación en ejecución." },
    { label: "Resultados de clientes", href: "/work/client-results", description: "Estándar de medición para publicar resultados verificados." },
  ],
  sampleAuditLinks: sampleOrder.map((slug) => ({ label: samples[slug].title, href: `/work/sample-audits/${slug}`, description: samples[slug].focus })),
  hub: {
    metaTitle: "Proyectos, auditorías de muestra y sistemas de crecimiento | Taskcover Agency",
    metaDescription: "Explora entregables de muestra, marco de crecimiento, estándares de casos y reglas para publicar resultados verificados.",
    eyebrow: "Sistema de trabajo",
    h1: "De inteligencia de búsqueda a ejecución",
    intro:
      "El trabajo de Taskcover se estructura alrededor de evidencia, diagnóstico, priorización, soporte de implementación, medición y aprendizaje.",
    command: [
      { label: "Investigación", detail: "Mercado, búsqueda, contenido, técnica y contexto comprador.", status: "Evaluado" },
      { label: "Diagnóstico", detail: "Restricciones, oportunidades y confianza separadas.", status: "Validado" },
      { label: "Estrategia", detail: "Recomendaciones conectadas a negocio y demanda.", status: "Priorizado" },
      { label: "Roadmap", detail: "Acciones ordenadas por dependencia y preparación.", status: "Mapeado" },
      { label: "Medición", detail: "Fuente, baseline, periodo y contexto requeridos.", status: "Listo para ejecución" },
      { label: "Iteración", detail: "El aprendizaje redefine el siguiente ciclo.", status: "Validado" },
    ],
    systemMap: [
      { label: "Auditorías de muestra", detail: "Muestran estructura sin claims de cliente.", connectsTo: "Roadmaps" },
      { label: "Marcos de crecimiento", detail: "Explican la lógica operativa.", connectsTo: "Carriles de ejecución" },
      { label: "Casos de estudio", detail: "Solo con permiso y evidencia verificados.", connectsTo: "Prueba pública" },
      { label: "Resultados", detail: "Exigen fuente, baseline, periodo y contexto.", connectsTo: "Reporting" },
      { label: "Roadmaps", detail: "Convierten hallazgos en trabajo secuenciado.", connectsTo: "Implementación" },
      { label: "Reporting", detail: "Une aprendizaje con confianza y límites.", connectsTo: "Iteración" },
    ],
    actionFlow: [
      { label: "Investigación", detail: "Recolectar contexto y demanda.", status: "Evaluado" },
      { label: "Diagnóstico", detail: "Encontrar bloqueos, brechas y palancas.", status: "Validado" },
      { label: "Modelo de prioridad", detail: "Evaluar impacto, esfuerzo, dependencia y confianza.", status: "Priorizado" },
      { label: "Roadmap", detail: "Traducir en acciones operables.", status: "Mapeado" },
      { label: "Soporte de implementación", detail: "Guiar cambios con restricciones reales.", status: "Listo" },
      { label: "Medición", detail: "Leer resultados con contexto y límites.", status: "Revisado" },
    ],
    evidenceMatrix: [
      { label: "Muestra ilustrativa", detail: "Metodología pública sin identidad ni resultado de cliente.", status: "Permitida con aviso" },
      { label: "Caso verificado", detail: "Permiso, contexto, evidencia, redacción y activos requeridos.", status: "Basado en evidencia" },
      { label: "Resultado verificado", detail: "Fuente, baseline, periodo, método y atribución requeridos.", status: "Basado en evidencia" },
      { label: "Proyecto confidencial", detail: "Sin identidad, métrica, cita, captura ni URL expuesta.", status: "Protegido" },
      { label: "Referencia privada", detail: "Compartida solo por ruta cualificada y autorizada.", status: "Controlado" },
    ],
    cta: {
      title: "Empieza con una auditoría que pueda convertirse en roadmap.",
      description: "La auditoría inicial puede revisar salud técnica, demanda, autoridad de contenido, preparación IA, oportunidad de mercado y prioridades de 90 días.",
      preview: ["Salud técnica", "Demanda de búsqueda", "Autoridad de contenido", "Preparación IA", "Oportunidad de mercado", "Prioridades 90 días"],
    },
  },
  pages: {
    "case-studies": {
      metaTitle: "Casos de estudio SEO verificados | Taskcover Agency",
      metaDescription: "Explora 10 casos de estudio verificados de Taskcover Agency en educación, hospitalidad, legal, eCommerce, travel, software, real estate y seguros.",
      eyebrow: "Biblioteca de casos verificados",
      h1: "10 casos de estudio verificados de Taskcover Agency",
      intro: "Explora casos públicos detallados con narrativas, métricas, servicios, visuales y contexto fuente aprobados.",
    },
    "sample-audits": {
      metaTitle: "Auditorías SEO de muestra y entregables | Taskcover Agency",
      metaDescription: "Explora ocho entregables ilustrativos de Taskcover sobre SEO técnico, IA, contenido, local, eCommerce, internacional, PPC y roadmaps.",
      eyebrow: "Entregables de muestra",
      h1: "Mira cómo piensa Taskcover",
      intro: "Estas auditorías de muestra demuestran metodología, estructura de análisis y traducción a ejecución sin representar proyectos reales.",
    },
    "search-growth-frameworks": {
      metaTitle: "Marco operativo de crecimiento en búsqueda | Taskcover Agency",
      metaDescription: "El marco Descubrir, Diagnosticar, Priorizar, Construir, Medir y Aprender de Taskcover.",
      eyebrow: "Marco operativo",
      h1: "El marco operativo de crecimiento en búsqueda",
      intro: "El crecimiento en búsqueda funciona como sistema: contexto, inteligencia, prioridades, ejecución, medición y gobierno.",
    },
    "client-results": {
      metaTitle: "Estándar de publicación de resultados verificados | Taskcover Agency",
      metaDescription: "Marco de Taskcover para publicar resultados solo con evidencia verificada, permiso público, baseline, periodo, fuente y contexto.",
      eyebrow: "Estándar de resultados",
      h1: "Resultados con contexto de medición",
      intro: "Los resultados se publican solo cuando la evidencia está verificada, el permiso público es claro y el contexto completo.",
    },
  },
  caseStudies: {
    registryIntro: "Estos casos con nombre son públicos porque identidad, narrativa, métricas, visuales y divulgación están aprobados para Taskcover Agency.",
    verification: [
      { label: "Permiso de identidad", detail: "El cliente aprueba el uso público del nombre.", status: "Requerido" },
      { label: "Contexto del proyecto", detail: "Alcance, mercado, servicios y restricciones documentados.", status: "Requerido" },
      { label: "Fuente de medición", detail: "Fuentes del resultado verificadas y aprobadas.", status: "Requerido" },
      { label: "Redacción y activos", detail: "Claims, citas, capturas y visuales revisados.", status: "Requerido" },
    ],
    requiredEvidence: ["Permiso de identidad", "Contexto del proyecto", "Baseline", "Metodología", "Periodo", "Fuente de medición", "Contexto del resultado", "Redacción aprobada", "Activos aprobados"],
    structure: [
      { label: "Contexto", detail: "El problema permitido para el trabajo.", status: "Documentado" },
      { label: "Método", detail: "Lo que Taskcover cambió o recomendó.", status: "Explicado" },
      { label: "Evidencia", detail: "La fuente que respalda el claim.", status: "Verificado" },
      { label: "Límites", detail: "Lo que no puede atribuirse o divulgarse.", status: "Declarado" },
    ],
    confidential: [
      { label: "Sin identificadores privados", detail: "Nombres, dominios, capturas, citas y URLs quedan ocultos.", status: "Protegido" },
      { label: "Referencia privada", detail: "Las referencias requieren cualificación y permiso.", status: "Controlado" },
      { label: "Evidencia no expuesta", detail: "Los documentos internos no se vuelven prueba pública por defecto.", status: "Privado" },
    ],
    cta: {
      title: "¿Quieres evaluar cómo Taskcover abordaría tu mercado?",
      description: "Revisa los entregables de muestra y solicita una auditoría para tu contexto de búsqueda.",
    },
  },
  sampleAudits: {
    selectorIntro: "Compara las preguntas que responde cada entregable y cómo los hallazgos se convierten en prioridades.",
    comparison: [
      { label: "Riesgo técnico", detail: "Arquitectura, indexación, renderizado, schema y dependencias.", status: "Diagnóstico" },
      { label: "Demanda y contenido", detail: "Temas, intención, autoridad, conversión y refrescos.", status: "Estratégico" },
      { label: "Sistemas de mercado", detail: "Local, eCommerce, internacional y paid-organic.", status: "Operativo" },
      { label: "Plan de ejecución", detail: "Roadmaps, responsables, decisiones y medición.", status: "Accionable" },
    ],
    everyAudit: ["Pregunta compradora", "Entradas de datos", "Método de análisis", "Estructura de hallazgos", "Lógica de prioridad", "Traducción a roadmap", "Aviso visible"],
    priorityFlow: [
      { label: "Severidad", detail: "Qué bloquea acceso, confianza o conversión.", status: "Evaluado" },
      { label: "Relevancia de negocio", detail: "Relación con demanda compradora.", status: "Mapeado" },
      { label: "Esfuerzo de implementación", detail: "Recursos y dependencias necesarias.", status: "Estimado" },
      { label: "Confianza de medición", detail: "Claridad para leer cambios futuros.", status: "Calificado" },
    ],
    disclosureTitle: "Los datos ilustrativos no son evidencia de cliente.",
    disclosureBody: disclosure,
    cta: {
      title: "Convierte una estructura de muestra en auditoría real.",
      description: "Taskcover puede aplicar el marco adecuado a tu sitio, mercado, contenido o plan de crecimiento.",
    },
  },
  frameworks: {
    stages: [
      { label: "Descubrir", detail: "Modelo de negocio, compradores, mercado y superficies de búsqueda.", status: "Contexto" },
      { label: "Diagnosticar", detail: "Restricciones técnicas, brechas de demanda, autoridad y conversión.", status: "Inteligencia" },
      { label: "Priorizar", detail: "Relevancia, demanda, dependencia, esfuerzo y confianza.", status: "Decisión" },
      { label: "Construir", detail: "Páginas, correcciones, activos de autoridad y medición.", status: "Ejecución" },
      { label: "Medir", detail: "Visibilidad, cobertura, salud, preparación y confianza reporting.", status: "Aprendizaje" },
      { label: "Aprender", detail: "Ajustar el siguiente ciclo con evidencia y límites.", status: "Iteración" },
    ],
    prioritization: [
      { label: "Relevancia de negocio", detail: "¿La acción apoya un comprador o mercado útil?", status: "Requerido" },
      { label: "Demanda de búsqueda", detail: "¿Existe una señal cualificada?", status: "Requerido" },
      { label: "Dependencia técnica", detail: "¿Debe ocurrir otra corrección primero?", status: "Secuenciado" },
      { label: "Necesidad de autoridad", detail: "¿El tema exige prueba, enlaces o experiencia?", status: "Evaluado" },
      { label: "Impacto de conversión", detail: "¿Mejora rutas sin inventar impacto?", status: "Calificado" },
      { label: "Confianza de medición", detail: "¿La performance futura será legible?", status: "Calificado" },
    ],
    execution: [
      { label: "Carril técnico", detail: "Crawl, indexación, performance, schema, plantillas y migraciones.", status: "Listo" },
      { label: "Carril contenido", detail: "Briefs, páginas, refrescos, enlaces internos y respuestas.", status: "Listo" },
      { label: "Carril autoridad", detail: "Prueba, PR digital, citas y fuentes.", status: "Listo" },
      { label: "Carril medición", detail: "Dashboards, fuentes, baselines y revisiones.", status: "Listo" },
    ],
    measurement: [
      { label: "Visibilidad no-marca", detail: "Leída con intención y contexto de mercado.", status: "Contextual" },
      { label: "Salud técnica", detail: "Señal operativa de crawl y renderizado.", status: "Operativo" },
      { label: "Cobertura de contenido", detail: "Completitud temática y camino comprador.", status: "Estratégico" },
      { label: "Preparación IA", detail: "Claridad de entidad y fuentes de cita.", status: "Calificado" },
    ],
    governance: [
      { label: "Registro de decisión", detail: "Por qué se eligieron prioridades.", status: "Documentado" },
      { label: "Responsables", detail: "Quién actúa y qué necesita.", status: "Asignado" },
      { label: "Cadencia de revisión", detail: "Cuándo la evidencia cambia prioridades.", status: "Planificado" },
      { label: "Reglas de divulgación", detail: "Público, privado o retenido.", status: "Controlado" },
    ],
    serviceMapping: [
      { label: "Estrategia SEO", detail: "Dirige el modelo operativo.", status: "Núcleo" },
      { label: "SEO técnico", detail: "Resuelve restricciones de acceso search.", status: "Base" },
      { label: "Marketing de contenidos", detail: "Construye alrededor de demanda y autoridad.", status: "Crecimiento" },
      { label: "Gestión PPC", detail: "Conecta aprendizajes paid con decisiones orgánicas.", status: "Conectado" },
    ],
    industryMapping: [
      { label: "Viajes", detail: "Arquitectura de mercado, destino y temporada.", status: "Adaptado" },
      { label: "Educación", detail: "Programas, confianza y decisiones de admisión.", status: "Adaptado" },
      { label: "Salud", detail: "Confianza local y contenido prudente.", status: "Adaptado" },
      { label: "SaaS y eCommerce", detail: "Arquitectura de producto, categoría y compra.", status: "Adaptado" },
    ],
    cta: {
      title: "Usa el marco para elegir la siguiente acción.",
      description: "Una auditoría de Taskcover convierte el modelo en prioridades para tu mercado, sitio y restricciones.",
    },
  },
  clientResults: {
    registryIntro: "Los resultados públicos requieren contexto de medición. Una métrica sin baseline, fuente, periodo y método puede confundir.",
    requirements: [
      { label: "Evidencia verificada", detail: "La fuente se puede revisar y está aprobada.", status: "Requerido" },
      { label: "Permiso público", detail: "El cliente aprueba divulgación pública.", status: "Requerido" },
      { label: "Baseline y periodo", detail: "El inicio y la ventana son claros.", status: "Requerido" },
      { label: "Metodología relevante", detail: "El trabajo detrás del resultado está documentado.", status: "Requerido" },
      { label: "Redacción aprobada", detail: "El claim está revisado y no exagerado.", status: "Requerido" },
    ],
    metricContext: [
      { label: "Demanda orgánica cualificada", detail: "La calidad importa más que visibilidad bruta.", status: "Contexto" },
      { label: "Visibilidad no-marca", detail: "Separada de marca cuando es posible.", status: "Contexto" },
      { label: "Salud técnica", detail: "Interpretada como señal operativa.", status: "Contexto" },
      { label: "Cobertura de contenido", detail: "Leída contra temas y camino comprador.", status: "Contexto" },
      { label: "Preparación IA", detail: "Evaluada como preparación, no como claim de plataforma.", status: "Contexto" },
      { label: "Calidad de leads", detail: "Solo con fuentes y límites aprobados.", status: "Contexto" },
    ],
    attribution: [
      "La performance puede depender de demanda, temporada, marca, plataformas, paid media, producto y releases.",
      "Taskcover no publica métricas aisladas sin fuente, baseline, periodo, método y límites.",
      "La evidencia confidencial sigue privada aunque apoye decisiones internas.",
    ],
    confidential: [
      { label: "Identidad no expuesta", detail: "Nombres, dominios, capturas y URLs se retienen.", status: "Protegido" },
      { label: "Métricas no expuestas", detail: "Las métricas privadas no se vuelven claims anónimos.", status: "Protegido" },
      { label: "Sin respaldo implícito", detail: "Trabajo privado no se usa como prueba pública.", status: "Protegido" },
    ],
    methodology: [
      { label: "Auditoría", detail: "La evidencia informa qué cambiar.", status: "Entrada" },
      { label: "Roadmap", detail: "Las prioridades secuencian el trabajo.", status: "Plan" },
      { label: "Implementación", detail: "Los cambios pasan por restricciones reales.", status: "Acción" },
      { label: "Revisión de medición", detail: "Los resultados se leen con contexto y límites.", status: "Aprendizaje" },
    ],
    cta: {
      title: "Mide el trabajo antes de publicar el resultado.",
      description: "Taskcover puede ayudar a definir un marco limpio de medición para reporting futuro.",
    },
  },
  samples,
  caseStudyDetails,
};
