import type { CaseMetric, CaseStudy, CaseStudySlug, WorkStep } from "../work.types";

function metric(input: Omit<CaseMetric, "verificationStatus" | "displayPublicly">): CaseMetric {
  return { ...input, verificationStatus: "verified", displayPublicly: true };
}

function steps(items: string[]): WorkStep[] {
  return items.map((item) => {
    const [label, detail = item] = item.split("::");
    return { label, detail, status: "Delivered" };
  });
}

function gallery(slug: CaseStudySlug, client: string, dims: [number, number][]): CaseStudy["visualGallery"] {
  return dims.map(([width, height], index) => ({
    src: `/case-studies/${slug}/image-${index + 1}.webp`,
    width,
    height,
    alt: `${client} approved case-study visual ${index + 1}`,
    caption: index === 0 ? `${client} engagement visual` : `${client} project evidence visual`,
  }));
}

function makeCase(input: Omit<CaseStudy, "id" | "type" | "permissionStatus" | "verificationStatus" | "publicDisclosure" | "illustrative" | "publicNarrativeApproved" | "approvedWording" | "approvedAssets" | "requiredContextComplete" | "sourceUrl">): CaseStudy {
  return {
    ...input,
    id: `case-${input.slug}`,
    type: "case-study",
    permissionStatus: "verified-public",
    verificationStatus: "verified",
    publicDisclosure: true,
    illustrative: false,
    publicNarrativeApproved: true,
    approvedWording: true,
    approvedAssets: true,
    requiredContextComplete: true,
  };
}

export const caseStudyOrder: CaseStudySlug[] = [
  "british-university-vietnam",
  "casa-madera",
  "the-bamboo-bar",
  "matthew-jeffery-law-firm",
  "skatepro",
  "agoda",
  "avis",
  "novaworld",
  "ccleaner",
  "fwd-insurance",
];

export const caseStudyDetails = {
  "british-university-vietnam": makeCase({
    slug: "british-university-vietnam",
    title: "British University Vietnam Search Growth Case Study",
    clientName: "British University Vietnam",
    shortName: "BUV",
    industry: "Education",
    industrySlug: "education-seo",
    industrySlugs: ["education-seo"],
    market: "Vietnam",
    marketSlugs: ["usa-seo-agency", "australia-seo-agency"],
    serviceSlugs: ["technical-seo", "content-marketing", "international-seo", "digital-pr-link-building"],
    eyebrow: "Education search growth",
    h1: "Expanding international education demand with technical SEO, content, UX, social signals, and authority.",
    metaTitle: "British University Vietnam SEO Case Study | Taskcover Agency",
    metaDescription: "Verified Taskcover Agency case study for British University Vietnam: organic traffic, keyword growth, UX, social/entity signals, and PR authority outcomes.",
    summary: "British University Vietnam moved from limited search coverage to broader international-education visibility with verified traffic, keyword, and PR outcomes.",
    heroSummary: "Taskcover Agency rebuilt BUV's search foundation around international education intent, program discovery, technical hygiene, UX, social/entity signals, and PR authority.",
    overview: "BUV needed stronger visibility after the pandemic as prospective students compared international degree options online. The engagement connected search architecture, content updates, UX improvements, social entity care, and media authority into one growth system.",
    clientBackground: "British University Vietnam is an international university in Vietnam offering UK-awarded degree pathways connected to institutions including the University of London, Staffordshire University, and the University of Stirling.",
    engagementPeriod: "Post-pandemic education search-growth engagement",
    startingPoint: "Only 110 keywords had meaningful top-ranking coverage. The website also carried a 72% bounce rate and average time on page of 1.2 minutes, showing weak engagement for new visitors.",
    challenge: "The university had to compete with well-funded domestic and international education brands while maintaining legally accurate recruitment messaging and modernizing the digital experience.",
    objectives: ["Increase qualified organic traffic from prospective students.", "Improve rankings for international education and program intent.", "Make the website easier to use and more useful for program discovery.", "Increase trusted brand visibility through news and education authority coverage."],
    strategy: ["Build an education keyword universe around UK degree pathways, admissions, programs, and international-study intent.", "Audit and refresh website content so program information matched search demand and student decision needs.", "Improve UX, load experience, and navigation so new visitors could move from discovery to enquiry.", "Use PR and entity reinforcement to strengthen public trust signals around BUV's global accreditations."],
    execution: steps(["Technical SEO::Reviewed content, indexing, page experience, and program discovery paths.", "Content expansion::Aligned existing pages and new copy with student search intent.", "UX improvement::Reduced friction in navigation and program exploration.", "PR authority::Supported coverage across education and news publications.", "Social/entity care::Strengthened Facebook, LinkedIn, and Instagram entity consistency."]),
    servicesDelivered: steps(["Technical SEO::Search access, performance, and page experience remediation.", "Content Marketing::Program and education-intent content refreshes.", "Digital PR::Authority coverage around institutional milestones.", "International SEO::Education-demand mapping for internationally oriented students."]),
    channels: ["Google organic search", "Website UX", "Education PR", "Facebook", "LinkedIn", "Instagram"],
    deliverables: ["SEO keyword map", "Technical and UX recommendations", "Content refresh plan", "PR and authority coverage plan", "Entity/social signal alignment"],
    results: ["Organic traffic increased from 18,300 to 25,200 visits per month.", "Organic research visibility increased 75%.", "Top Google keyword footprint expanded from 110 to 1,400 terms.", "More than 100 terms were in the competitive international education group.", "BUV appeared in 25+ press articles and 3 education TV programs."],
    metrics: [
      metric({ id: "buv-organic-traffic", label: "Organic traffic", value: "+37%", baseline: "18,300 visits/month", endValue: "25,200 visits/month", context: "Published source result for monthly organic traffic growth.", category: "Organic traffic" }),
      metric({ id: "buv-organic-research", label: "Organic research visibility", value: "+75%", context: "Published source result for organic research growth.", category: "Keyword visibility" }),
      metric({ id: "buv-keywords", label: "Top Google keywords", value: "1,400", baseline: "110", endValue: "1,400", context: "Published source result for keyword footprint growth.", category: "Keyword visibility" }),
      metric({ id: "buv-pr", label: "Authority coverage", value: "25+ articles", context: "Published source result across VietnamNet, VnExpress, and other education media.", category: "Press coverage" }),
    ],
    visualGallery: gallery("british-university-vietnam", "British University Vietnam", [[1080, 600], [1400, 634]]),
    keyLearning: "Education SEO works when program discovery, technical access, trust signals, and public authority are managed as one admissions journey rather than separate marketing tasks.",
    relatedServices: ["technical-seo", "content-marketing", "international-seo", "digital-pr-link-building"],
    relatedIndustries: ["education-seo"],
    relatedMarkets: ["usa-seo-agency", "australia-seo-agency"],
    relatedSampleAudits: ["technical-seo-audit", "content-gap-map", "international-seo-market-map"],
    finalCta: { title: "Build a search system for education demand.", description: "Taskcover can map your program intent, technical constraints, authority gaps, and conversion journey.", label: "Get a Free SEO Audit", href: "/free-seo-audit" },
    featuredOnHomepage: true,
    featuredOrder: 1,
  }),
  "casa-madera": makeCase({
    slug: "casa-madera",
    title: "Casa Madera Local Search Case Study",
    clientName: "Casa Madera",
    shortName: "Casa Madera",
    industry: "Restaurant and hospitality",
    industrySlug: "travel-seo",
    industrySlugs: ["travel-seo"],
    market: "Local hospitality",
    marketSlugs: ["usa-seo-agency"],
    serviceSlugs: ["local-seo", "content-marketing", "ppc-management"],
    eyebrow: "Restaurant local search",
    h1: "Building local dining visibility, reservation intent, and brand recognition for a Latin American restaurant concept.",
    metaTitle: "Casa Madera Local SEO Case Study | Taskcover Agency",
    metaDescription: "Verified restaurant local SEO case study for Casa Madera covering local search, content, UX, conversion, and Google Maps reputation outcomes.",
    summary: "Casa Madera grew from minimal search visibility to a steady local search presence with verified traffic, top ranking, and review outcomes.",
    heroSummary: "Taskcover Agency connected local SEO, menu and dining-intent content, web experience, reputation signals, and conversion paths for Casa Madera.",
    overview: "Casa Madera needed search visibility for diners discovering Latin American and Mexican dining experiences, events, cocktails, and reservations. The work focused on building a credible local search footprint from a weak baseline.",
    clientBackground: "Casa Madera is a restaurant concept centered on Latin American cuisine, Mexican dishes, cocktails, warm interiors, live music, and social dining occasions.",
    engagementPeriod: "Restaurant local search growth campaign through 2023",
    startingPoint: "Before 2021 the restaurant had no meaningful traffic, no notable keyword trend, low awareness, weak SEO execution, and low conversion.",
    challenge: "The restaurant category is crowded, visual expectations are high, and local search demand turns into revenue only when pages, maps, menu content, and reservation calls to action work together.",
    objectives: ["Build SEO from a minimal baseline.", "Increase local awareness and visibility.", "Improve website aesthetics and user experience.", "Turn more visitors into reservation or enquiry actions."],
    strategy: ["Target local restaurant, menu, cuisine, event, and dining-intent keywords.", "Optimize Google Business Profile and map presence with consistent restaurant information.", "Refresh content and media around dishes, atmosphere, events, and offers.", "Improve landing-page calls to action for reservations and menu exploration."],
    execution: steps(["Local SEO::Built local dining visibility around restaurant and cuisine intent.", "Content system::Created food, menu, culture, and event content opportunities.", "UX/CRO::Improved site clarity, page speed, mobile access, and reservation calls to action.", "Reputation support::Used Google Maps review context to reinforce trust."]),
    servicesDelivered: steps(["Local SEO::Local intent, maps, and nearby dining demand.", "Content Marketing::Restaurant, menu, event, and cuisine content.", "PPC Management::Paid support for immediate local demand where useful.", "Conversion Optimization::Landing-page and reservation path improvements."]),
    channels: ["Google organic search", "Google Maps", "Website", "Instagram", "Facebook", "YouTube"],
    deliverables: ["Local keyword map", "Google Business Profile improvements", "Content plan", "Landing page and CTA recommendations", "Reputation signal review"],
    results: ["Average traffic reached more than 3,000 visits per month.", "Organic traffic reached 5,947 in December 2023.", "45 keywords reached top 3.", "88 keywords reached top 10.", "Google Maps rating averaged 4.3 stars with mostly positive feedback."],
    metrics: [
      metric({ id: "casa-traffic", label: "Average monthly traffic", value: "3,000+", context: "Published source result for average monthly visits.", category: "Organic traffic" }),
      metric({ id: "casa-peak-traffic", label: "Organic traffic peak", value: "5,947", timeframe: "December 2023", context: "Published source result for December 2023 organic traffic.", category: "Organic traffic" }),
      metric({ id: "casa-top3", label: "Top 3 keywords", value: "45", context: "Published source result for Casa Madera and menu-related keyword rankings.", category: "Top 3 rankings" }),
      metric({ id: "casa-top10", label: "Top 10 keywords", value: "88", context: "Published source result for Google top 10 keyword visibility.", category: "Top 10 rankings" }),
    ],
    visualGallery: gallery("casa-madera", "Casa Madera", [[1080, 600], [1400, 630]]),
    keyLearning: "Restaurant SEO has to connect local discovery, sensory content, reputation, and booking actions; traffic alone does not create diners.",
    relatedServices: ["local-seo", "content-marketing", "ppc-management"],
    relatedIndustries: ["travel-seo"],
    relatedMarkets: ["usa-seo-agency"],
    relatedSampleAudits: ["local-seo-audit", "content-gap-map", "ppc-organic-intelligence"],
    finalCta: { title: "Turn local dining demand into booked tables.", description: "Taskcover can review your local visibility, menu content, reputation signals, and booking path.", label: "Review local SEO", href: "/services/local-seo" },
    featuredOnHomepage: false,
  }),
  "the-bamboo-bar": makeCase({
    slug: "the-bamboo-bar",
    title: "The Bamboo Bar Luxury Hospitality Case Study",
    clientName: "The Bamboo Bar",
    shortName: "Bamboo Bar",
    industry: "Luxury hospitality",
    industrySlug: "travel-seo",
    industrySlugs: ["travel-seo"],
    market: "Thailand",
    marketSlugs: ["australia-seo-agency"],
    serviceSlugs: ["local-seo", "content-marketing", "ppc-management"],
    eyebrow: "Luxury hospitality search",
    h1: "Improving Bangkok nightlife discovery for a luxury cocktail bar inside Mandarin Oriental Bangkok.",
    metaTitle: "The Bamboo Bar SEO Case Study | Taskcover Agency",
    metaDescription: "Verified luxury hospitality case study for The Bamboo Bar covering Bangkok local search, travel intent, UX, paid media, and review outcomes.",
    summary: "The Bamboo Bar strengthened Bangkok local search visibility with verified top rankings, monthly organic traffic, UX, and review outcomes.",
    heroSummary: "Taskcover Agency aligned local keywords, travel and nightlife intent, booking UX, content, and paid support for a luxury hospitality search journey.",
    overview: "The Bamboo Bar needed to be discoverable for travelers and locals searching for luxury cocktails, jazz, nightlife, and Mandarin Oriental Bangkok experiences.",
    clientBackground: "The Bamboo Bar is a renowned luxury bar in Mandarin Oriental Bangkok, known for classic tropical design, distinctive cocktails, and live jazz experiences.",
    engagementPeriod: "Hospitality SEO and digital marketing campaign through 2023",
    startingPoint: "Before 2022 the site had no meaningful traffic. From 2022 traffic improved but remained inconsistent, and before 2023 keyword visibility was limited.",
    challenge: "Traffic had declined from 8,171 to 6,142 between October and December 2022, while Bangkok nightlife SEO and social attention were highly competitive.",
    objectives: ["Build stable SEO visibility for Bangkok nightlife and bar intent.", "Reach more than 5,000 organic visits per month.", "Improve top 3 and top 10 keyword footprint.", "Improve website usability for menus, events, contact, and bookings."],
    strategy: ["Use long-tail and local keywords tied to Bangkok bars, cocktails, jazz, nightlife, and Mandarin Oriental context.", "Create content around cocktails, events, and venue experience.", "Improve mobile usability, page speed, menu access, event information, and booking flow.", "Coordinate Google Ads, Facebook Ads, and social activity with organic search."],
    execution: steps(["Local SEO::Mapped Bangkok nightlife and luxury bar demand.", "Content production::Supported cocktail, event, and experience content.", "UX refresh::Improved navigation, speed, mobile usability, and booking paths.", "Paid and social coordination::Used paid campaigns and social media to reinforce demand."]),
    servicesDelivered: steps(["Local SEO::Bangkok local and travel search visibility.", "Content Marketing::Luxury hospitality content and event discovery.", "PPC Management::Google Ads and Facebook Ads support.", "UX Optimization::Menu, event, contact, and booking path improvements."]),
    channels: ["Google organic search", "Google Ads", "Google Maps", "Facebook", "Instagram", "YouTube"],
    deliverables: ["Local keyword strategy", "Content plan", "UX recommendations", "Paid media support", "Social engagement plan"],
    results: ["9 keywords reached top 3 by the end of 2023.", "18 keywords reached top 10.", "Organic traffic reached 5,000 visits per month, with a month above 7,000 in March 2023.", "Google review rating reached 4.6 stars.", "Website updates improved access to menu, event, service, and booking information."],
    metrics: [
      metric({ id: "bamboo-top3", label: "Top 3 keywords", value: "9", timeframe: "End of 2023", context: "Published source result for The Bamboo Bar and Bamboo Bar Bangkok search terms.", category: "Top 3 rankings" }),
      metric({ id: "bamboo-top10", label: "Top 10 keywords", value: "18", timeframe: "End of 2023", context: "Published source result for Google top 10 keyword visibility.", category: "Top 10 rankings" }),
      metric({ id: "bamboo-traffic", label: "Monthly organic traffic", value: "5,000", context: "Published source result for monthly organic traffic.", category: "Organic traffic" }),
      metric({ id: "bamboo-peak", label: "Peak month traffic", value: "7,000+", timeframe: "March 2023", context: "Published source result for a peak traffic month.", category: "Organic traffic" }),
    ],
    visualGallery: gallery("the-bamboo-bar", "The Bamboo Bar", [[1080, 600], [592, 637]]),
    keyLearning: "Luxury hospitality search needs practical booking clarity without flattening the premium experience that creates demand in the first place.",
    relatedServices: ["local-seo", "content-marketing", "ppc-management"],
    relatedIndustries: ["travel-seo"],
    relatedMarkets: ["australia-seo-agency"],
    relatedSampleAudits: ["local-seo-audit", "content-gap-map", "ppc-organic-intelligence"],
    finalCta: { title: "Make high-intent hospitality searches easier to capture.", description: "Taskcover can map local demand, content, reviews, and conversion paths for travel and hospitality brands.", label: "Explore travel SEO", href: "/industries/travel-seo" },
    featuredOnHomepage: false,
  }),
  "matthew-jeffery-law-firm": makeCase({
    slug: "matthew-jeffery-law-firm",
    title: "Matthew Jeffery Law Firm Search Recovery Case Study",
    clientName: "Matthew Jeffery Law Firm",
    shortName: "Matthew Jeffery",
    industry: "Legal and immigration",
    industrySlug: "legal-immigration-seo",
    industrySlugs: ["legal-immigration-seo"],
    market: "Canada",
    marketSlugs: ["canada-seo-agency"],
    serviceSlugs: ["technical-seo", "content-marketing", "local-seo"],
    eyebrow: "Legal search recovery",
    h1: "Recovering immigration-law visibility with technical remediation, content architecture, UX, and reporting alignment.",
    metaTitle: "Matthew Jeffery Law Firm SEO Case Study | Taskcover Agency",
    metaDescription: "Verified legal SEO case study for Matthew Jeffery Law Firm covering recovery from traffic decline, technical SEO, immigration content, CTR, onsite time, and bounce-rate outcomes.",
    summary: "Matthew Jeffery Law Firm recovered search visibility and engagement after authority, technical, content, and UX issues weakened organic performance.",
    heroSummary: "Taskcover Agency rebuilt legal search performance around immigration intent, technical quality, content clusters, authority links, UX diagnostics, and CRM/reporting alignment.",
    overview: "The firm needed to recover from visibility decline in a trust-sensitive Canadian immigration market where users research services through Google before contacting counsel.",
    clientBackground: "Matthew Jeffery Law Firm is a Toronto immigration and settlement law firm with more than 20 years of experience across family sponsorship, Express Entry, PR card renewal, and Canadian citizenship matters.",
    engagementPeriod: "Search recovery engagement following 2021 algorithm and visibility disruption",
    startingPoint: "Domain Authority reportedly fell from 37 to 20 in Q2 2021, disrupting 65% of target-keyword traffic and lowering lead conversion by 40%. Monthly organic traffic fell from 16,300 to 3,600.",
    challenge: "Legal and immigration search requires accuracy, trust, local relevance, and intent precision. Technical issues, weak internal links, and algorithm changes were reducing reach and lead quality.",
    objectives: ["Recover organic traffic and keyword visibility.", "Rebuild content around Canadian immigration search intent.", "Improve technical health, internal links, and authority signals.", "Improve UX, CTR, onsite engagement, and reporting clarity."],
    strategy: ["Research immigration-law keywords using SEMrush and Ahrefs context from the source narrative.", "Audit all existing articles for search intent and rebuild clusters around Canadian immigration.", "Strengthen internal links and authority links, including credible government-adjacent sources where available.", "Use GA4, Search Console, and UX diagnostics to improve engagement and reporting."],
    execution: steps(["Technical remediation::Fixed site structure, internal linking, and search-access issues.", "Content cluster rebuild::Organized informational, navigational, commercial, and transactional immigration intent.", "Authority improvement::Reinforced link quality and topical trust.", "UX and reporting::Used analytics, Search Console, and heatmap context to improve user paths."]),
    servicesDelivered: steps(["Technical SEO::Site architecture, internal linking, and remediation.", "Content Marketing::Immigration-law content clusters and landing pages.", "Local SEO::Toronto and Canada legal search relevance.", "Reporting alignment::CTR, onsite, bounce-rate, and social signals."]),
    channels: ["Google organic search", "Website", "Google Analytics 4", "Search Console", "Social media", "CRM/reporting"],
    deliverables: ["Technical audit", "Immigration keyword strategy", "Content cluster plan", "Internal link architecture", "UX reporting review"],
    results: ["Organic traffic increased 171% year over year.", "More than 80% of keywords entered top search results.", "45% of keywords reached Top 3.", "CTR increased 35%.", "Time onsite improved 133%.", "Bounce rate reduced from 72% to 38%.", "Followers increased 65% with 12% engagement."],
    metrics: [
      metric({ id: "mj-organic", label: "Organic traffic", value: "+171%", timeframe: "Year over year", context: "Published source result for organic traffic recovery.", category: "Organic traffic" }),
      metric({ id: "mj-top3", label: "Keywords in Top 3", value: "45%", context: "Published source result for keyword ranking distribution.", category: "Top 3 rankings" }),
      metric({ id: "mj-ctr", label: "CTR", value: "+35%", context: "Published source result for click-through rate improvement.", category: "CTR" }),
      metric({ id: "mj-onsite", label: "Time onsite", value: "+133%", context: "Published source result for onsite engagement improvement.", category: "UX improvement" }),
      metric({ id: "mj-bounce", label: "Bounce rate", value: "38%", baseline: "72%", endValue: "38%", context: "Published source result for bounce-rate reduction.", category: "Bounce rate" }),
    ],
    visualGallery: gallery("matthew-jeffery-law-firm", "Matthew Jeffery Law Firm", [[1400, 778], [883, 207]]),
    keyLearning: "Recovery work in legal SEO has to solve trust, technical access, intent accuracy, and conversion clarity together; isolated content production is not enough.",
    relatedServices: ["technical-seo", "content-marketing", "local-seo"],
    relatedIndustries: ["legal-immigration-seo"],
    relatedMarkets: ["canada-seo-agency"],
    relatedSampleAudits: ["technical-seo-audit", "content-gap-map", "local-seo-audit"],
    finalCta: { title: "Recover legal search visibility with context.", description: "Taskcover can diagnose technical, content, local, and conversion barriers in legal and immigration search.", label: "Explore legal SEO", href: "/industries/legal-immigration-seo" },
    featuredOnHomepage: false,
  }),
  "skatepro": makeCase({
    slug: "skatepro",
    title: "SkatePro eCommerce Search Architecture Case Study",
    clientName: "SkatePro",
    shortName: "SkatePro",
    industry: "eCommerce",
    industrySlug: "ecommerce-seo",
    industrySlugs: ["ecommerce-seo"],
    market: "Canada",
    marketSlugs: ["canada-seo-agency"],
    serviceSlugs: ["ecommerce-seo", "technical-seo", "content-marketing", "ppc-management"],
    eyebrow: "eCommerce search architecture",
    h1: "Strengthening product discovery, category visibility, UX, and conversion for an action-sports retailer.",
    metaTitle: "SkatePro eCommerce SEO Case Study | Taskcover Agency",
    metaDescription: "Verified SkatePro eCommerce SEO case study covering category/product discovery, technical SEO, UX, retargeting, traffic, rankings, and conversion outcomes.",
    summary: "SkatePro rebuilt search visibility from low traffic baselines toward stronger category/product discovery and social audience growth.",
    heroSummary: "Taskcover Agency aligned category SEO, product discoverability, content quality, UX, checkout friction, paid support, retargeting, and reputation signals.",
    overview: "SkatePro needed customers to find action-sports products across a broad catalog while turning search visits into orders.",
    clientBackground: "SkatePro is a global action-sports retailer serving more than 4 million customers per year with more than 20,000 items across skateboards, scooters, BMX, roller sports, and related gear.",
    engagementPeriod: "eCommerce search and conversion growth engagement",
    startingPoint: "In 2020, organic traffic averaged about 250 and paid traffic averaged about 3, sometimes reaching 0. Conversion was constrained by UX, checkout friction, and weak calls to action.",
    challenge: "A large action-sports catalog needs clear category architecture, product paths, technical controls, persuasive content, and a purchase experience that does not lose users after discovery.",
    objectives: ["Reach top 10 visibility for action-sports product searches.", "Improve website interface and content quality.", "Increase organic and paid traffic.", "Improve conversion from visitors to orders."],
    strategy: ["Map category and product intent around action sports and priority terms.", "Improve catalog architecture, internal links, and product discovery.", "Refresh content to help users choose equipment.", "Use paid media, retargeting, social activity, and reputation signals to support organic growth."],
    execution: steps(["Category SEO::Mapped action-sports category and product demand.", "Technical SEO::Reviewed catalog discoverability and search access.", "UX/CRO::Improved navigation, content clarity, checkout flow, and calls to action.", "Paid/social support::Used advertising and social media to reinforce demand and retarget buyers."]),
    servicesDelivered: steps(["eCommerce SEO::Category, product, and buying-intent architecture.", "Technical SEO::Catalog and crawl/discoverability controls.", "Content Marketing::Product education and category support.", "PPC Management::Paid support and retargeting."]),
    channels: ["Google organic search", "Paid search", "Website", "Checkout flow", "Facebook", "Instagram", "Google Maps/reviews"],
    deliverables: ["Category search map", "Product discovery recommendations", "UX and checkout review", "Content quality plan", "Retargeting and paid support plan"],
    results: ["SkatePro Canada reached top 10 results for important action-sports keywords.", "Organic traffic rose from about 250 to thousands of visits per month.", "Paid traffic stabilized and at times exceeded the campaign target.", "Conversion improved through UX and checkout optimization.", "Social audience reached 107,000 Facebook followers and 234,000 Instagram followers.", "Google Maps rating improved to 4.2 stars."],
    metrics: [
      metric({ id: "skatepro-organic", label: "Organic traffic", value: "Thousands/month", baseline: "About 250", context: "Published source result for traffic growth from a low 2020 baseline.", category: "Organic traffic" }),
      metric({ id: "skatepro-top10", label: "Top 10 visibility", value: "Reached", context: "Published source result for important action-sports keywords including examples in the source.", category: "Top 10 rankings" }),
      metric({ id: "skatepro-facebook", label: "Facebook audience", value: "107K", context: "Published source result for social audience size.", category: "Audience growth" }),
      metric({ id: "skatepro-instagram", label: "Instagram audience", value: "234K", context: "Published source result for social audience size.", category: "Audience growth" }),
    ],
    visualGallery: gallery("skatepro", "SkatePro", [[1080, 600], [1200, 630]]),
    keyLearning: "eCommerce SEO compounds when category architecture, product guidance, reputation, paid learning, and checkout usability are treated as one buying path.",
    relatedServices: ["ecommerce-seo", "technical-seo", "content-marketing", "ppc-management"],
    relatedIndustries: ["ecommerce-seo"],
    relatedMarkets: ["canada-seo-agency"],
    relatedSampleAudits: ["ecommerce-search-architecture", "technical-seo-audit", "ppc-organic-intelligence"],
    finalCta: { title: "Make your catalog easier to find and buy from.", description: "Taskcover can review category architecture, product discovery, technical controls, and conversion friction.", label: "Explore eCommerce SEO", href: "/industries/ecommerce-seo" },
    featuredOnHomepage: false,
  }),
  "agoda": makeCase({
    slug: "agoda",
    title: "Agoda Travel Search Growth Case Study",
    clientName: "Agoda",
    shortName: "Agoda",
    industry: "Travel",
    industrySlug: "travel-seo",
    industrySlugs: ["travel-seo"],
    market: "Southeast Asia",
    marketSlugs: ["australia-seo-agency"],
    serviceSlugs: ["international-seo", "technical-seo", "content-marketing", "ppc-management"],
    eyebrow: "Travel search and SEA growth",
    h1: "Aligning destination intent, mobile campaigns, and international SEO for Southeast Asia travel demand.",
    metaTitle: "Agoda Travel SEO Case Study | Taskcover Agency",
    metaDescription: "Verified Agoda case study covering Southeast Asia travel search, international SEO, destination content, keyword visibility, mobile campaigns, and organic traffic outcomes.",
    summary: "Agoda strengthened travel search visibility with verified top 5 keyword coverage, brand landing alignment, and organic traffic gains.",
    heroSummary: "Taskcover Agency supported Agoda's travel search growth through destination intent, international keyword strategy, EEAT content, mobile campaigns, and organic/paid coordination.",
    overview: "Agoda needed to compete across Southeast Asia travel search while demand, OTA competition, and post-pandemic travel behavior shifted quickly.",
    clientBackground: "Agoda is a Booking Holdings online travel platform focused strongly on Asia, with offices including Singapore, Bangkok, Hong Kong, Tokyo, Seoul, and Beijing.",
    engagementPeriod: "2021 travel search growth engagement",
    startingPoint: "From late 2020 to early Q1 2021, organic traffic declined by up to 50% while competition from OTAs including Traveloka, Kayak, Airbnb, Booking.com, and Expedia intensified.",
    challenge: "Agoda had to protect search visibility in a volatile travel market while competing for hotel, flight, destination, mobile, and deal-driven intent.",
    objectives: ["Grow Agoda awareness in Southeast Asia.", "Reach 80% top 10 and 75% top 5 coverage for priority travel keywords.", "Increase organic traffic by 40% as an objective.", "Use travel influencers and campaign hashtags to extend awareness.", "Reach high-intent booking and travel-search users."],
    strategy: ["Build comprehensive keyword research across hotels, travel booking, nearby hotels, flights, and destination intent.", "Use informational keywords first to build traffic and trust, then advance more competitive booking terms.", "Create SEO blog content to EEAT standards.", "Coordinate mobile-app promotions, Eco Deal, Gold Circle, local traveler targeting, and Day Use messaging with search demand."],
    execution: steps(["International SEO::Mapped Southeast Asia travel and destination demand.", "Content system::Built SEO blog and destination content around travel intent.", "Mobile campaign support::Aligned app, mobile deal, and local traveler demand.", "Reputation response::Used search to control negative visibility and reinforce positive brand context."]),
    servicesDelivered: steps(["International SEO::Regional travel demand and language-aware keyword strategy.", "Technical SEO::On-page and off-page optimization support.", "Content Marketing::Travel blog and destination content.", "PPC Management::Paid and campaign support for mobile and promotion demand."]),
    channels: ["Google organic search", "Mobile app campaigns", "SEO blog", "Influencers", "Hashtags", "Paid campaigns"],
    deliverables: ["Travel keyword map", "SEO content plan", "Landing-page alignment", "Mobile campaign search support", "Reputation search plan"],
    results: ["80% of important keywords reached Top 5.", "100% of brand keywords matched the intended landing pages.", "Organic traffic increased 13% in September 2021 versus the previous month after five months of SEO and blog work.", "Website traffic rate increased 0.4%.", "Bounce rate decreased 0.6%.", "Agoda's 2023 search data reported Vietnam travel searches up 298% year over year.", "App Store rating was 4.8 across 231.2K reviews, and Google Play rating was 4.7 across 2.71M reviews with 50M downloads."],
    metrics: [
      metric({ id: "agoda-top5", label: "Important keywords in Top 5", value: "80%", context: "Published source result for priority keyword visibility.", category: "Top 3 rankings" }),
      metric({ id: "agoda-brand", label: "Brand keywords to intended landing page", value: "100%", context: "Published source result for brand keyword page matching.", category: "Keyword visibility" }),
      metric({ id: "agoda-traffic", label: "Organic traffic", value: "+13%", timeframe: "September 2021 vs previous month", context: "Published source result after five months of SEO and blog work.", category: "Organic traffic" }),
      metric({ id: "agoda-vietnam-search", label: "Vietnam travel searches", value: "+298%", timeframe: "2023 year over year", context: "Published source reference from Agoda search data.", category: "Keyword visibility" }),
    ],
    visualGallery: gallery("agoda", "Agoda", [[1400, 788], [1121, 335]]),
    keyLearning: "Travel SEO has to flex with destination demand, mobile behavior, deals, and market-level competition; static landing pages are not enough.",
    relatedServices: ["international-seo", "technical-seo", "content-marketing", "ppc-management"],
    relatedIndustries: ["travel-seo"],
    relatedMarkets: ["australia-seo-agency"],
    relatedSampleAudits: ["international-seo-market-map", "content-gap-map", "ppc-organic-intelligence"],
    finalCta: { title: "Map travel demand across markets and moments.", description: "Taskcover can connect international SEO, destination content, mobile intent, and paid-organic intelligence.", label: "Explore travel SEO", href: "/industries/travel-seo" },
    featuredOnHomepage: false,
  }),
  "avis": makeCase({
    slug: "avis",
    title: "Avis Canada Multi-Location Search Case Study",
    clientName: "Avis",
    shortName: "Avis",
    industry: "Franchise and multi-location",
    industrySlug: "franchise-local-seo",
    industrySlugs: ["franchise-local-seo"],
    market: "Canada",
    marketSlugs: ["canada-seo-agency"],
    serviceSlugs: ["local-seo", "technical-seo", "content-marketing"],
    eyebrow: "Canada local search",
    h1: "Improving city-level rental car visibility, Google Maps presence, UX, and conversion for Avis Canada.",
    metaTitle: "Avis Canada Local SEO Case Study | Taskcover Agency",
    metaDescription: "Verified Avis Canada case study covering multi-location local SEO, Google Business Profile, city landing pages, organic traffic, UX, conversion, and Maps outcomes.",
    summary: "Avis Canada improved local visibility, organic traffic, UX, conversion, and Google Maps engagement across a multi-location rental car search journey.",
    heroSummary: "Taskcover Agency connected city landing pages, Google Business Profile improvements, technical performance, review signals, authority links, and conversion UX.",
    overview: "Avis needed high-intent car rental searches to reach the right city and branch pages while improving trust and booking confidence.",
    clientBackground: "Avis Car Rental is a global rental car brand owned by Avis Budget Group, known for its long history in car rental and service positioning around trying harder for customers.",
    engagementPeriod: "Canada multi-location growth campaign, 2023-2024 recognition context",
    startingPoint: "The source notes that pandemic demand pressure reduced Avis revenue by 39.94% year over year in 2020, making digital recovery and high-intent local visibility important.",
    challenge: "Car rental search is city-specific and map-driven. Avis had to win competitive terms, local branch visibility, technical speed, and booking conversion together.",
    objectives: ["Reach 100% top 10 keyword coverage in North America for core car rental terms as a campaign objective.", "Increase natural Google traffic by at least 30% within 12 months as an objective.", "Make traffic growth translate into bookings.", "Improve city-level Google Maps and Google Search visibility."],
    strategy: ["Create and optimize local landing pages and avis.ca paths for city and near-me intent.", "Update Google Business Profile content with real photos, reviews, and location keywords.", "Improve technical performance and authority links.", "Publish travel and car-rental content around trust and comparison intent."],
    execution: steps(["Local landing pages::Built city-level paths around car rental and near-me demand.", "Google Business Profile::Updated profiles with local information, images, reviews, and terms.", "Technical performance::Improved speed and user experience.", "Authority/content::Supported travel forum and comparison queries."]),
    servicesDelivered: steps(["Local SEO::City and branch-level rental visibility.", "Technical SEO::Speed and page experience improvements.", "Content Marketing::Travel and car-rental comparison content.", "Franchise SEO::Multi-location search architecture."]),
    channels: ["Google Search", "Google Maps", "Google Business Profile", "Website", "Travel content"],
    deliverables: ["City landing-page plan", "GBP optimization", "Technical performance recommendations", "Authority link support", "Conversion path review"],
    results: ["Avis appeared in top 3 Google Maps positions in major cities, with local searches up 30%.", "Organic traffic increased 40%.", "Page load time improved from 4.2s to 2.1s.", "Bounce rate fell from 65% to 45%.", "Conversion rose from 2.7% to 3.3%.", "Direction clicks and Avis searches on Google Maps increased 30%.", "Avis Canada was recognized as Canada's Leading Car Rental Company in 2023 and 2024 by World Travel Awards."],
    metrics: [
      metric({ id: "avis-local", label: "Local searches", value: "+30%", context: "Published source result connected to top 3 Google Maps visibility in major cities.", category: "Local search" }),
      metric({ id: "avis-organic", label: "Organic traffic", value: "+40%", context: "Published source result for natural search traffic growth.", category: "Organic traffic" }),
      metric({ id: "avis-speed", label: "Page load time", value: "2.1s", baseline: "4.2s", endValue: "2.1s", context: "Published source result for performance improvement.", category: "UX improvement" }),
      metric({ id: "avis-bounce", label: "Bounce rate", value: "45%", baseline: "65%", endValue: "45%", context: "Published source result for bounce-rate reduction.", category: "Bounce rate" }),
      metric({ id: "avis-conversion", label: "Conversion rate", value: "3.3%", baseline: "2.7%", endValue: "3.3%", context: "Published source result for conversion rate lift.", category: "Conversion" }),
    ],
    visualGallery: gallery("avis", "Avis", [[1400, 778], [491, 281]]),
    keyLearning: "Multi-location SEO succeeds when city landing pages, map trust, technical performance, and booking conversion all reinforce the same local intent.",
    relatedServices: ["local-seo", "technical-seo", "content-marketing"],
    relatedIndustries: ["franchise-local-seo", "travel-seo"],
    relatedMarkets: ["canada-seo-agency"],
    relatedSampleAudits: ["local-seo-audit", "technical-seo-audit", "content-gap-map"],
    finalCta: { title: "Build a local search system for every market you serve.", description: "Taskcover can map city pages, Google Business Profiles, local proof, and conversion flows for multi-location brands.", label: "Explore Canada SEO", href: "/markets/canada-seo-agency" },
    featuredOnHomepage: false,
  }),
  "novaworld": makeCase({
    slug: "novaworld",
    title: "NovaWorld Real Estate Digital Growth Case Study",
    clientName: "NovaWorld",
    shortName: "NovaWorld",
    industry: "Real estate",
    industrySlug: "travel-seo",
    industrySlugs: ["travel-seo"],
    market: "Vietnam",
    marketSlugs: ["australia-seo-agency"],
    serviceSlugs: ["technical-seo", "content-marketing", "ppc-management"],
    eyebrow: "Large-scale real estate growth",
    h1: "Building launch-stage visibility, content architecture, paid support, and buyer confidence for NovaWorld.",
    metaTitle: "NovaWorld Real Estate SEO Case Study | Taskcover Agency",
    metaDescription: "Verified NovaWorld case study covering large-scale real estate search, SEO foundation, content architecture, paid media, social coordination, traffic growth, and keyword expansion.",
    summary: "NovaWorld grew from limited digital visibility to large-scale search demand, keyword expansion, and stronger market trust.",
    heroSummary: "Taskcover Agency connected SEO foundations, content marketing, social media, performance ads, and buyer journey clarity for a major resort real estate brand.",
    overview: "NovaWorld needed to move from launch-stage visibility into sustained digital demand for high-value resort and tourism real estate.",
    clientBackground: "NovaWorld is Novaland's branded line of large tourism and resort urban areas, launched on March 7, 2019, with townhouses, shophouses, detached villas, and semi-detached villas.",
    engagementPeriod: "2020-2022 digital growth engagement",
    startingPoint: "In June 2019 the site had only 10 visits and 19 Google keywords, limiting digital reach for a major real estate launch.",
    challenge: "The brand needed to create awareness, confidence, and search demand in a competitive resort real estate market where buyers require both lifestyle aspiration and investment trust.",
    objectives: ["Increase website traffic at scale.", "Build SEO foundations and content architecture.", "Coordinate paid media and social content.", "Generate more qualified buyer attention and market conversation."],
    strategy: ["Audit and improve the website so Google could understand and rank project information.", "Build content around resort real estate, lifestyle, investment, and project discovery.", "Use paid media and social campaigns to accelerate awareness.", "Shape buyer journeys from awareness to consideration through content and trust signals."],
    execution: steps(["SEO foundation::Improved search access, structure, and project visibility.", "Content architecture::Built content around resort lifestyle and buyer decision points.", "Performance ads::Used paid media to accelerate qualified visibility.", "Social coordination::Created conversation and awareness around the project."]),
    servicesDelivered: steps(["Technical SEO::Foundation and site visibility improvements.", "Content Marketing::Project, lifestyle, and investment content architecture.", "PPC Management::Performance advertising for launch and demand.", "Social Media::Awareness and conversation support."]),
    channels: ["Google organic search", "Website", "Performance ads", "Social media", "Content marketing"],
    deliverables: ["SEO foundation plan", "Content architecture", "Paid media plan", "Social campaign coordination", "Buyer journey messaging"],
    results: ["Website traffic grew from 10 visits in June 2019 to nearly 100,000 visits per month by December 2022.", "Keyword footprint grew from 19 Google keywords in June 2019 to 2,513 by December 2022.", "NovaWorld became more familiar in the market and attracted tens of thousands of potential customers.", "The campaign strengthened trust and positioning in Vietnam's premium resort real estate segment."],
    metrics: [
      metric({ id: "novaworld-traffic", label: "Monthly website traffic", value: "~100,000", baseline: "10 visits", endValue: "Nearly 100,000/month", timeframe: "June 2019 to December 2022", context: "Published source result for traffic growth.", category: "Organic traffic" }),
      metric({ id: "novaworld-growth", label: "Traffic growth", value: "Nearly 1,000x", timeframe: "June 2019 to December 2022", context: "Published source result comparing initial visits with December 2022 traffic.", category: "Organic traffic" }),
      metric({ id: "novaworld-keywords", label: "Google keywords", value: "2,513", baseline: "19", endValue: "2,513", timeframe: "June 2019 to December 2022", context: "Published source result for keyword footprint expansion.", category: "Keyword visibility" }),
    ],
    visualGallery: gallery("novaworld", "NovaWorld", [[1400, 778], [1400, 788]]),
    keyLearning: "Large real estate launches need search architecture before demand peaks; paid media can accelerate awareness, but organic structure keeps interest discoverable.",
    relatedServices: ["technical-seo", "content-marketing", "ppc-management"],
    relatedIndustries: ["travel-seo"],
    relatedMarkets: ["australia-seo-agency"],
    relatedSampleAudits: ["technical-seo-audit", "content-gap-map", "90-day-search-growth-roadmap"],
    finalCta: { title: "Build search demand before the market fully knows the project.", description: "Taskcover can map launch visibility, content architecture, buyer intent, and paid-organic sequencing.", label: "Plan a growth roadmap", href: "/work/sample-audits/90-day-search-growth-roadmap" },
    featuredOnHomepage: false,
  }),
  "ccleaner": makeCase({
    slug: "ccleaner",
    title: "CCleaner Software Market Expansion Case Study",
    clientName: "CCleaner",
    shortName: "CCleaner",
    industry: "SaaS and software",
    industrySlug: "saas-seo",
    industrySlugs: ["saas-seo"],
    market: "Vietnam",
    marketSlugs: ["australia-seo-agency"],
    serviceSlugs: ["international-seo", "technical-seo", "content-marketing", "ppc-management"],
    eyebrow: "Software market expansion",
    h1: "Localizing software search demand, rankings, traffic, and conversion for CCleaner in Vietnam.",
    metaTitle: "CCleaner SaaS SEO Case Study | Taskcover Agency",
    metaDescription: "Verified CCleaner case study covering Vietnamese software localization, technical SEO, content, organic visibility, rankings, traffic, conversion, and social engagement.",
    summary: "CCleaner expanded Vietnamese software-market visibility with verified traffic, ranking, conversion, and social engagement outcomes.",
    heroSummary: "Taskcover Agency supported CCleaner's Vietnam expansion through localization, technical SEO, content, paid support, rankings, traffic, and conversion alignment.",
    overview: "CCleaner needed to enter and compete in Vietnam's software optimization and security market after company restructuring and international expansion.",
    clientBackground: "CCleaner is a system cleaning and optimization software platform backed by Avast after the 2017 acquisition, with expansion focus into Vietnam from 2021.",
    engagementPeriod: "Vietnam software-market expansion campaign",
    startingPoint: "Organic traffic was declining because of Google algorithm shifts and website structure issues. The source objective set traffic, top keyword, and organic conversion targets for Vietnam.",
    challenge: "CCleaner had to compete with established security and optimization brands including BKAV, McAfee, and Kaspersky while localizing value for Vietnamese software users.",
    objectives: ["Grow Vietnam website traffic.", "Place core keywords in top search results.", "Reach 100% top 10, 70% top 5, and 50% top 3 as initial ranking objectives.", "Reach 3% organic order conversion as an initial objective."],
    strategy: ["Localize content for young, professional, and older computer users with different needs.", "Improve technical SEO and site structure.", "Build content around PC, Windows, macOS, performance, and optimization intent.", "Use paid support and social engagement to reinforce organic visibility."],
    execution: steps(["Localization::Adapted messaging and content to Vietnamese user segments.", "Technical SEO::Addressed structure and optimization issues behind organic decline.", "Content marketing::Built software education around PC, Windows, macOS, and performance needs.", "Paid/social support::Used advertising and engagement to support visibility and conversion."]),
    servicesDelivered: steps(["International SEO::Vietnam localization and market intent.", "Technical SEO::Website structure and search performance.", "Content Marketing::Software education and product-intent content.", "PPC Management::Paid support for software-market demand."]),
    channels: ["Google organic search", "Website", "Paid campaigns", "Social media", "Software awards/authority"],
    deliverables: ["Vietnam keyword map", "Technical SEO review", "Localized content plan", "Paid support plan", "Conversion and social engagement review"],
    results: ["Traffic to the website reached 810,000.", "100% of core keywords reached top 10.", "80% of core keywords reached top 5.", "60% of core keywords reached top 3.", "Organic traffic order conversion reached 5%.", "Social engagement reached 3,000.", "CCleaner and Avast were connected with paid computer protection and antivirus software recognition in 2021 and 2023, and remained positioned among top security/software brands in 2024."],
    metrics: [
      metric({ id: "ccleaner-traffic", label: "Website traffic", value: "810,000", context: "Published source result for website traffic.", category: "Organic traffic" }),
      metric({ id: "ccleaner-top10", label: "Core keywords in top 10", value: "100%", context: "Published source result for keyword rankings.", category: "Top 10 rankings" }),
      metric({ id: "ccleaner-top5", label: "Core keywords in top 5", value: "80%", context: "Published source result for keyword rankings.", category: "Keyword visibility" }),
      metric({ id: "ccleaner-top3", label: "Core keywords in top 3", value: "60%", context: "Published source result for keyword rankings.", category: "Top 3 rankings" }),
      metric({ id: "ccleaner-conversion", label: "Organic order conversion", value: "5%", context: "Published source result for conversion from organic traffic.", category: "Conversion" }),
    ],
    visualGallery: gallery("ccleaner", "CCleaner", [[1080, 600], [1280, 720]]),
    keyLearning: "Software localization has to translate market trust, technical clarity, performance intent, and conversion confidence; rankings alone do not establish product adoption.",
    relatedServices: ["international-seo", "technical-seo", "content-marketing", "ppc-management"],
    relatedIndustries: ["saas-seo"],
    relatedMarkets: ["australia-seo-agency"],
    relatedSampleAudits: ["international-seo-market-map", "technical-seo-audit", "content-gap-map"],
    finalCta: { title: "Localize software demand without weakening technical credibility.", description: "Taskcover can map SaaS/software search intent, content localization, technical health, and conversion barriers.", label: "Explore SaaS SEO", href: "/industries/saas-seo" },
    featuredOnHomepage: false,
  }),
  "fwd-insurance": makeCase({
    slug: "fwd-insurance",
    title: "FWD Insurance Digital Growth Case Study",
    clientName: "FWD Insurance",
    shortName: "FWD",
    industry: "Insurance",
    industrySlug: "healthcare-seo",
    industrySlugs: ["healthcare-seo"],
    market: "Vietnam",
    marketSlugs: ["australia-seo-agency"],
    serviceSlugs: ["technical-seo", "content-marketing", "ppc-management"],
    eyebrow: "Insurance trust-sensitive search",
    h1: "Growing insurance visibility, trust, conversion, and social engagement around simpler customer messaging.",
    metaTitle: "FWD Insurance SEO Case Study | Taskcover Agency",
    metaDescription: "Verified FWD Insurance case study covering trust-sensitive insurance content, search visibility, UX, paid media, social campaigns, traffic, keywords, conversion, and engagement.",
    summary: "FWD Insurance strengthened digital growth with verified traffic, top 10 keyword visibility, conversion, and social engagement outcomes.",
    heroSummary: "Taskcover Agency aligned YMYL-sensitive insurance content, search visibility, UX, brand messaging, paid media, and social coordination.",
    overview: "FWD needed to improve online presence and brand recognition in Vietnam while changing how people think about insurance: less complex, more human, and easier to understand.",
    clientBackground: "FWD Insurance is an insurance group focused on simple, effective, accessible insurance. FWD entered Vietnam in 2016 and competed with longer-established brands including Bao Viet, Prudential, and Dai-ichi.",
    engagementPeriod: "12-month insurance digital growth engagement with campaign context from 2021-2023",
    startingPoint: "The source notes a young brand facing stronger legacy competitors and initial targets around website traffic, top 10 keyword share, conversion, and social engagement.",
    challenge: "Insurance content is trust-sensitive and often complex. FWD had to increase demand without creating confusion, fear, or overpromising around financial protection.",
    objectives: ["Increase website traffic.", "Grow top 10 keyword visibility.", "Improve order conversion.", "Increase social engagement.", "Support brand campaigns including Press Play and simpler insurance messaging."],
    strategy: ["Build clearer insurance content for life, health, accident, education, and retirement needs.", "Improve search visibility while keeping messaging understandable and trust-sensitive.", "Coordinate paid media and social activity around brand campaigns.", "Use UX and content clarity to reduce friction in insurance exploration."],
    execution: steps(["Search visibility::Improved organic access and keyword coverage.", "Content clarity::Translated insurance concepts into simpler decision support.", "Paid/social coordination::Supported brand campaigns and audience engagement.", "UX support::Improved digital paths from awareness to action."]),
    servicesDelivered: steps(["Technical SEO::Search access and site performance support.", "Content Marketing::Trust-sensitive insurance content and campaign support.", "PPC Management::Paid media coordination.", "Social Media::Campaign engagement and message distribution."]),
    channels: ["Google organic search", "Website", "Paid media", "Social media", "Brand campaigns"],
    deliverables: ["Insurance search map", "Trust-sensitive content plan", "Campaign message support", "Paid/social coordination", "Conversion path review"],
    results: ["After 12 months, website traffic reached 1,140,000.", "70% of keywords were in top 10 search results.", "Order conversion reached 0.8%.", "Social engagement reached 15,000 per post.", "Campaigns supported Press Play, Sống đầy cùng FWD Bảo hiểm dễ hiểu, and COVID-19 support communications."],
    metrics: [
      metric({ id: "fwd-traffic", label: "Website traffic", value: "1,140,000", timeframe: "After 12 months", context: "Published source result for website traffic.", category: "Organic traffic" }),
      metric({ id: "fwd-top10", label: "Keywords in top 10", value: "70%", timeframe: "After 12 months", context: "Published source result for top 10 keyword visibility.", category: "Top 10 rankings" }),
      metric({ id: "fwd-conversion", label: "Order conversion", value: "0.8%", timeframe: "After 12 months", context: "Published source result for order conversion.", category: "Conversion" }),
      metric({ id: "fwd-social", label: "Social engagement", value: "15,000/post", context: "Published source result for social engagement per post.", category: "Social engagement" }),
    ],
    visualGallery: gallery("fwd-insurance", "FWD Insurance", [[1080, 600], [803, 545]]),
    keyLearning: "Insurance search growth depends on clarity and trust: users need understandable language, proof, and low-friction paths before they will consider conversion.",
    relatedServices: ["technical-seo", "content-marketing", "ppc-management"],
    relatedIndustries: ["healthcare-seo"],
    relatedMarkets: ["australia-seo-agency"],
    relatedSampleAudits: ["content-gap-map", "technical-seo-audit", "ppc-organic-intelligence"],
    finalCta: { title: "Make trust-sensitive search easier to understand.", description: "Taskcover can review content clarity, search visibility, UX, and conversion paths for regulated or trust-heavy categories.", label: "Explore content strategy", href: "/services/content-marketing" },
    featuredOnHomepage: false,
  }),
} satisfies Record<CaseStudySlug, CaseStudy>;
