import type { LeadsContent } from "@/content/leads.types";

export const leads: LeadsContent = {
  locale: "en",
  recipientEmail: "business@taskcover.com",
  common: {
    back: "Back",
    continue: "Continue",
    submit: "Send request",
    submitting: "Sending...",
    retry: "Try again",
    directEmail: "Email business@taskcover.com",
    requiredNote: "Required fields are marked.",
    optional: "Optional",
    consentText:
      "I agree that Taskcover may use this information to review my request and contact me about relevant search-growth services.",
    honeypotLabel: "Leave this field empty",
    unavailableTitle: "Online submission is temporarily unavailable.",
    unavailableBody:
      "You can send your request directly to business@taskcover.com. Your entered details remain on this page so you can retry or email the team.",
    temporaryError:
      "The request could not be delivered right now. Please try again or email business@taskcover.com directly.",
    spamError:
      "The request could not be accepted. Please check the form and try again, or email business@taskcover.com directly.",
    validationSummary: "Please review the highlighted fields before continuing.",
    mailSubjects: {
      "seo-audit": "Free SEO audit request",
      "strategy-call": "Strategy call request",
      "general-contact": "Taskcover contact request",
      "media-inquiry": "Media inquiry for Taskcover",
      "private-reference": "Private reference request",
      partnership: "Partnership inquiry",
      "seo-mentor": "SEO Mentor inquiry",
      "ppc-inquiry": "PPC inquiry",
      other: "Taskcover inquiry",
    },
    turnstileLabel: "Security check",
  },
  fields: {
    name: { label: "Full name", placeholder: "Jane Nguyen" },
    workEmail: { label: "Work email", placeholder: "jane@company.com" },
    company: { label: "Company", placeholder: "Company or organization" },
    role: { label: "Role", placeholder: "Marketing lead, founder, operator" },
    websiteUrl: { label: "Website URL", placeholder: "https://example.com" },
    market: { label: "Primary market" },
    industry: { label: "Industry" },
    serviceInterests: { label: "Service interests" },
    currentTrafficRange: { label: "Current monthly organic traffic" },
    paidSearchActivity: { label: "Is paid search active?" },
    primaryChallenge: { label: "Primary search-growth challenge", placeholder: "What is blocking visibility, leads, or execution?" },
    goals: { label: "Main business goal", placeholder: "What should search growth help the business do?" },
    timeline: { label: "Desired timeline" },
    investmentRange: { label: "Estimated monthly search-growth investment" },
    preferredTimeZone: { label: "Preferred time zone" },
    preferredCallWindows: { label: "Preferred call windows" },
    message: { label: "Message", placeholder: "Share useful context, links, constraints, or questions." },
    engagementType: { label: "Engagement type" },
    publication: { label: "Publication or platform", placeholder: "Publication, podcast, newsletter, or show" },
    topic: { label: "Topic", placeholder: "Search, AI visibility, technical SEO, local SEO..." },
    deadline: { label: "Deadline", placeholder: "Date or timing if relevant" },
    requestedFormat: { label: "Requested format" },
  },
  validation: {
    required: "This field is required.",
    email: "Enter a valid work email.",
    url: "Enter a valid website URL.",
    consent: "Consent is required before sending.",
    selectRequired: "Choose at least one option.",
    length: "This field is too long.",
    malformed: "This value is not supported.",
    callWindows: "Choose two or three preferred call windows.",
  },
  options: {
    markets: [
      { value: "usa", label: "USA" },
      { value: "canada", label: "Canada" },
      { value: "australia", label: "Australia" },
      { value: "multiple", label: "Multiple markets" },
      { value: "other", label: "Other" },
    ],
    industries: [
      { value: "travel-hospitality", label: "Travel & Hospitality" },
      { value: "education", label: "Education" },
      { value: "healthcare-wellness", label: "Healthcare & Wellness" },
      { value: "legal-immigration", label: "Legal & Immigration" },
      { value: "saas-technology", label: "SaaS & Technology" },
      { value: "ecommerce", label: "eCommerce" },
      { value: "franchise-multilocation", label: "Franchise & Multi-location" },
      { value: "other", label: "Other" },
    ],
    services: [
      { value: "seo-agency", label: "SEO strategy" },
      { value: "technical-seo", label: "Technical SEO" },
      { value: "ai-search-optimization", label: "AI search optimization" },
      { value: "content-marketing", label: "Content marketing" },
      { value: "digital-pr-link-building", label: "Digital PR & authority" },
      { value: "local-seo", label: "Local SEO" },
      { value: "ecommerce-seo", label: "eCommerce SEO" },
      { value: "international-seo", label: "International SEO" },
      { value: "seo-audit", label: "SEO audit" },
      { value: "ppc-management", label: "PPC management" },
      { value: "seo-mentor-service", label: "SEO Mentor Service" },
    ],
    traffic: [
      { value: "unknown", label: "Not sure yet" },
      { value: "under-1000", label: "Under 1,000 visits/month" },
      { value: "1000-10000", label: "1,000-10,000 visits/month" },
      { value: "10000-50000", label: "10,000-50,000 visits/month" },
      { value: "50000-plus", label: "50,000+ visits/month" },
    ],
    paidSearch: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "planned", label: "Planned" },
      { value: "not-sure", label: "Not sure" },
    ],
    timelines: [
      { value: "urgent", label: "Needs attention now" },
      { value: "30-60-days", label: "30-60 days" },
      { value: "quarter", label: "This quarter" },
      { value: "6-months", label: "Next 6 months" },
      { value: "exploring", label: "Exploring options" },
    ],
    investments: [
      { value: "not-sure", label: "Not sure yet" },
      { value: "under-2500", label: "Under USD 2,500/month" },
      { value: "2500-5000", label: "USD 2,500-5,000/month" },
      { value: "5000-10000", label: "USD 5,000-10,000/month" },
      { value: "10000-plus", label: "USD 10,000+/month" },
      { value: "project-based", label: "Project-based engagement" },
    ],
    timeZones: [
      { value: "america-eastern", label: "Eastern time" },
      { value: "america-central", label: "Central time" },
      { value: "america-mountain", label: "Mountain time" },
      { value: "america-pacific", label: "Pacific time" },
      { value: "canada-eastern", label: "Canada Eastern time" },
      { value: "australia-eastern", label: "Australia Eastern time" },
      { value: "europe", label: "Europe" },
      { value: "asia", label: "Asia" },
      { value: "other", label: "Other" },
    ],
    callWindows: [
      { value: "weekday-morning", label: "Weekday morning" },
      { value: "weekday-midday", label: "Weekday midday" },
      { value: "weekday-afternoon", label: "Weekday afternoon" },
      { value: "weekday-evening", label: "Weekday evening" },
      { value: "flexible", label: "Flexible" },
    ],
    contactIntents: [
      { value: "seo-services", label: "SEO services" },
      { value: "ppc", label: "PPC management" },
      { value: "seo-mentor", label: "SEO Mentor Service" },
      { value: "media", label: "Media inquiry" },
      { value: "private-reference", label: "Private reference request" },
      { value: "partnership", label: "Partnership" },
      { value: "general", label: "General question" },
      { value: "other", label: "Other" },
    ],
    engagementTypes: [
      { value: "audit", label: "Audit or assessment" },
      { value: "ongoing", label: "Ongoing growth program" },
      { value: "consulting", label: "Consulting or mentorship" },
    ],
    requestedFormats: [
      { value: "quote", label: "Written quote" },
      { value: "interview", label: "Interview" },
      { value: "briefing", label: "Technical briefing" },
    ],
  },
  freeAudit: {
    meta: {
      title: "Free SEO Audit Request | Taskcover Agency",
      description:
        "Request a Taskcover SEO audit covering technical health, search demand, content authority, AI search readiness, and 90-day priorities.",
    },
    eyebrow: "Diagnostic assessment",
    h1: "Request a Free SEO Audit",
    intro:
      "Share the context needed to diagnose the search system behind your site, market, content, and growth priorities.",
    proof:
      "The audit request does not promise rankings or response time. It helps Taskcover evaluate fit and the right diagnostic lens.",
    steps: [
      { title: "Contact and website", description: "Who you are and what site should be reviewed." },
      { title: "Business and search context", description: "Market, industry, service interests, and current search activity." },
      { title: "Priorities and timing", description: "What matters most, when action is needed, and optional investment context." },
    ],
    previewTitle: "Potential audit areas",
    previewIntro: "The right review depends on your market and site, but the diagnostic can cover:",
    previewItems: [
      "Technical health",
      "Search demand",
      "Content authority",
      "AI search readiness",
      "Local or international opportunity",
      "Paid and organic overlap",
      "90-day priorities",
    ],
    privacyTitle: "How your information is used",
    privacyBody:
      "Form data is used only to evaluate and respond to your request. No sensitive personal, financial, health, or account data is requested.",
  },
  bookCall: {
    meta: {
      title: "Request a Strategy Call | Taskcover Agency",
      description:
        "Request a Taskcover strategy call for SEO, AI search, PPC, content, local, eCommerce, international, or search-growth planning.",
    },
    eyebrow: "Strategy-session planner",
    h1: "Request a Strategy Call",
    intro:
      "Use this planner to share your growth context and preferred windows. Taskcover will confirm availability after a configured delivery adapter accepts the request.",
    agendaTitle: "What the session can cover",
    agenda: ["Business context", "Search constraints", "Priority opportunities", "Fit for audit, advisory, or execution support"],
    prepareTitle: "Useful context to prepare",
    prepare: ["Website and market", "Current SEO or PPC activity", "Internal constraints", "Important deadlines or decision dates"],
    boundary:
      "This route collects a strategy-call request. It does not confirm a calendar appointment until a future calendar adapter is configured.",
  },
  contact: {
    meta: {
      title: "Contact Taskcover Agency | Search Growth Requests",
      description:
        "Contact Taskcover for SEO services, PPC management, SEO Mentor Service, media inquiries, private references, partnerships, or general questions.",
    },
    eyebrow: "Inquiry routing desk",
    h1: "Send the right request to Taskcover",
    intro:
      "Choose the intent that best matches your request so the message can be evaluated with the right context.",
    deskTitle: "Routing map",
    deskItems: ["SEO and PPC fit", "Mentorship questions", "Media and commentary", "Private-reference qualification", "Partnership and general requests"],
    intentHelp: "Your selected intent changes the context fields below.",
  },
  thankYou: {
    meta: { title: "Request received | Taskcover Agency", description: "Taskcover request confirmation." },
    fallbackTitle: "Request received",
    fallbackMessage: "The request type was recorded safely.",
    nextLabel: "What happens next",
    studiesLabel: "Relevant case studies",
    samplesLabel: "Relevant sample audits",
    viewStudies: "View case studies",
    viewSamples: "View sample audits",
    analyticsHook: "Analytics hook ready: thank_you_view",
    states: {
      "seo-audit": {
        title: "SEO audit request received",
        message: "Your diagnostic request has been accepted by the configured delivery path.",
        next: ["Taskcover reviews the website and context provided.", "The team evaluates fit, likely audit areas, and useful next steps.", "No response time is guaranteed on this page."],
        studies: ["British University Vietnam", "Matthew Jeffery Law Firm", "SkatePro"],
        samples: ["Technical SEO Audit", "AI Search Visibility Review", "90-Day Search Growth Roadmap"],
        primaryCta: "Request a Strategy Call",
        secondaryCta: "Explore Sample Audits",
      },
      "strategy-call": {
        title: "Strategy-call request received",
        message: "Your call request has been delivered. This is not a confirmed calendar appointment.",
        next: ["Taskcover reviews fit and availability.", "The team uses your preferred windows to evaluate scheduling options.", "A future calendar adapter may automate this later."],
        studies: ["Agoda", "FWD Insurance", "Casa Madera"],
        samples: ["Content Gap Map", "PPC + Organic Search Intelligence Review"],
        primaryCta: "View Case Studies",
        secondaryCta: "Explore Services",
      },
      "media-inquiry": {
        title: "Media inquiry received",
        message: "Your media request has been delivered for editorial-fit review.",
        next: ["Topic, format, and deadline are reviewed.", "Taskcover evaluates whether an approved representative is appropriate.", "Spokesperson availability is not promised."],
        studies: ["Agoda", "British University Vietnam"],
        samples: ["AI Search Visibility Review", "Search Growth Framework"],
        primaryCta: "Explore Proof",
        secondaryCta: "Return to Contact",
      },
      "private-reference": {
        title: "Private-reference request received",
        message: "Your private-reference request has been delivered for qualification review.",
        next: ["Taskcover checks engagement fit and confidentiality boundaries.", "No private names, details, or introductions are exposed automatically.", "Availability is evaluated case by case."],
        studies: ["Verified Case Study Library", "Client Results Standard"],
        samples: ["Technical SEO Audit", "90-Day Search Growth Roadmap"],
        primaryCta: "Review Proof Standard",
        secondaryCta: "View Work",
      },
      "general-contact": {
        title: "Contact request received",
        message: "Your request has been accepted by the configured delivery path.",
        next: ["Taskcover reviews the message and routes it by topic.", "If relevant, the team may connect your request to a service, sample audit, or case study.", "No response time is guaranteed."],
        studies: ["Verified Case Study Library", "Sample Audit Library"],
        samples: ["Content Gap Map", "Local SEO Audit"],
        primaryCta: "Book a Strategy Call",
        secondaryCta: "Explore Services",
      },
      partnership: {
        title: "Partnership inquiry received",
        message: "Your partnership request has been delivered for fit review.",
        next: ["Taskcover reviews alignment, audience, and operating boundaries.", "No partnership availability is implied.", "Relevant context may be requested later."],
        studies: ["Proof and Authority System"],
        samples: ["Search Growth Framework"],
        primaryCta: "Explore Proof",
        secondaryCta: "Return to Contact",
      },
      "seo-mentor": {
        title: "SEO Mentor inquiry received",
        message: "Your mentorship request has been delivered.",
        next: ["Taskcover reviews the team context and skill gaps.", "Mentorship scope is evaluated before any engagement is confirmed.", "No response time is guaranteed."],
        studies: ["SEO Mentor Service"],
        samples: ["90-Day Search Growth Roadmap"],
        primaryCta: "Explore SEO Mentor Service",
        secondaryCta: "View Sample Audits",
      },
      "ppc-inquiry": {
        title: "PPC inquiry received",
        message: "Your PPC request has been delivered.",
        next: ["Taskcover reviews paid-search context and organic overlap.", "The team evaluates whether PPC management or search intelligence is the right fit.", "No response time is guaranteed."],
        studies: ["Casa Madera", "FWD Insurance"],
        samples: ["PPC + Organic Search Intelligence Review"],
        primaryCta: "Explore PPC Management",
        secondaryCta: "View Work",
      },
      other: {
        title: "Request received",
        message: "Your request has been accepted by the configured delivery path.",
        next: ["Taskcover reviews the message and routes it by topic.", "Additional context may be requested if needed.", "No response time is guaranteed."],
        studies: ["Work Library"],
        samples: ["Sample Audit Library"],
        primaryCta: "Explore Work",
        secondaryCta: "Return Home",
      },
      contact: {
        title: "Contact request received",
        message: "Your request has been accepted by the configured delivery path.",
        next: ["Taskcover reviews the request type and message.", "The team evaluates the most relevant next path.", "No response time is guaranteed."],
        studies: ["Verified Case Study Library"],
        samples: ["Sample Audit Library"],
        primaryCta: "Book a Strategy Call",
        secondaryCta: "Explore Work",
      },
    },
  },
};
