import type { SampleAudit, SampleAuditSlug, WorkContent } from "../work.types";

const disclosure =
  "Illustrative sample deliverable. It demonstrates Taskcover's methodology and does not represent a specific client engagement or result.";

const sampleOrder: SampleAuditSlug[] = [
  "technical-seo-audit",
  "ai-search-visibility-review",
  "content-gap-map",
  "local-seo-audit",
  "ecommerce-search-architecture",
  "international-seo-market-map",
  "ppc-organic-intelligence",
  "90-day-search-growth-roadmap",
];

function sample(input: {
  slug: SampleAuditSlug;
  title: string;
  shortLabel: string;
  focus: string;
  question: string;
  visual: string;
  inputs: string[];
  answers: string[];
  method: string[];
  findings: string[];
  priority: string[];
  output: string[];
  roadmap: string[];
  services: string[];
  industries: string[];
}): SampleAudit {
  return {
    id: `sample-${input.slug}`,
    type: "sample-audit",
    slug: input.slug,
    title: input.title,
    shortLabel: input.shortLabel,
    summary: input.focus,
    focus: input.focus,
    buyerQuestion: input.question,
    visualStyle: input.visual,
    eyebrow: "Sample deliverable",
    permissionStatus: "internal-only",
    verificationStatus: "not-applicable",
    publicDisclosure: true,
    requiredContextComplete: false,
    illustrative: true,
    disclosureText: disclosure,
    inputs: input.inputs.map((label) => ({ label, detail: "Reviewed as a methodology input, not as client evidence." })),
    answers: input.answers,
    method: input.method.map((label, index) => ({
      label,
      detail: ["Collect", "Diagnose", "Prioritize", "Translate"][index] ?? "Refine",
      status: ["Mapped", "Assessed", "Prioritized", "Ready for execution"][index] ?? "Validated",
    })),
    findings: input.findings.map((label, index) => ({
      label,
      detail: ["Critical", "High priority", "Needs review", "Monitor"][index % 4],
      status: ["Critical", "High priority", "Needs review", "Monitor"][index % 4],
    })),
    priority: input.priority.map((label) => ({
      label,
      detail: "Judged by impact, dependency, confidence, and implementation effort.",
      status: "Prioritized",
    })),
    outputPreview: input.output.map((label) => ({
      label,
      detail: "Shown as a sample output structure with qualitative labels.",
      status: "Illustrative",
    })),
    roadmap: input.roadmap.map((label) => ({
      label,
      detail: "Converted into owner-ready tasks and decision gates.",
      status: "Ready",
    })),
    relatedServices: input.services,
    relatedIndustries: input.industries,
    deliverables: input.output,
    methodology: input.method,
    faq: [
      {
        q: "Is this a real client audit?",
        a: "No. It is an illustrative sample that shows how Taskcover structures analysis and recommendations.",
      },
      {
        q: "Can the same structure be used for a live engagement?",
        a: "Yes. Live work uses verified inputs, client context, permission rules, and measurement sources before public outcomes are discussed.",
      },
      {
        q: "Does this sample promise a result?",
        a: "No. It explains decision logic and deliverable format without claiming rankings, traffic, leads, revenue, or platform visibility.",
      },
    ],
    metaTitle: `${input.title} Sample | Taskcover Agency`,
    metaDescription: `${input.title} sample deliverable showing Taskcover's methodology without client names, fake metrics, or invented results.`,
  };
}

const samples = {
  "technical-seo-audit": sample({
    slug: "technical-seo-audit",
    title: "Technical SEO Audit",
    shortLabel: "Technical SEO",
    focus: "Crawl architecture, indexation, rendering risk, schema readiness, and release risk translated into priority actions.",
    question: "What technical constraints are limiting search performance or creating future risk?",
    visual: "Crawl architecture and issue-priority ledger",
    inputs: ["Crawl paths", "Indexation states", "Rendering behavior", "Schema coverage", "Release history"],
    answers: ["Which systems need immediate attention", "Which issues can be monitored", "Which fixes unlock later work"],
    method: ["Architecture scan", "Indexation review", "Rendering and performance assessment", "Release-risk translation"],
    findings: ["Blocked indexation pattern", "Template-level rendering risk", "Schema needs review", "Migration dependency"],
    priority: ["Critical search access", "High-priority template fixes", "Validated technical controls", "Monitoring queue"],
    output: ["Issue ledger", "Crawl-state map", "Schema review table", "Release-risk checklist"],
    roadmap: ["Fix search access first", "Batch template changes", "Validate deployment", "Monitor index response"],
    services: ["technical-seo", "seo-audit", "seo-agency"],
    industries: ["saas-seo", "ecommerce-seo", "travel-seo"],
  }),
  "ai-search-visibility-review": sample({
    slug: "ai-search-visibility-review",
    title: "AI Search Visibility Review",
    shortLabel: "AI visibility",
    focus: "Entity clarity, answer-surface readiness, citation sources, structured content, and authority signals.",
    question: "Is the brand understandable and citeable across AI answer environments?",
    visual: "Entity graph and answer-surface map",
    inputs: ["Entity statements", "Source coverage", "Structured content", "Third-party authority", "Answer-ready pages"],
    answers: ["Where entity clarity is weak", "Which sources support citations", "Which content needs structured answers"],
    method: ["Entity extraction", "Citation-source review", "Answer format assessment", "Authority signal mapping"],
    findings: ["Entity relationship gap", "Citation source needs review", "Structured content opportunity", "Third-party proof dependency"],
    priority: ["Entity definition", "Source reinforcement", "Answer block production", "Authority validation"],
    output: ["Entity graph", "Answer-surface matrix", "Citation source ledger", "AI readiness roadmap"],
    roadmap: ["Clarify entity pages", "Strengthen source pages", "Add answer formats", "Review third-party proof"],
    services: ["ai-search-optimization", "content-marketing", "digital-pr-link-building"],
    industries: ["education-seo", "healthcare-seo", "legal-immigration-seo"],
  }),
  "content-gap-map": sample({
    slug: "content-gap-map",
    title: "Content Gap Map",
    shortLabel: "Content gaps",
    focus: "Topic clusters, intent coverage, authority gaps, refresh needs, conversion content, and internal links.",
    question: "Where is content missing, under-supported, or disconnected from buyer intent?",
    visual: "Topic cluster and intent coverage map",
    inputs: ["Topic universe", "Intent groups", "Existing content", "Authority signals", "Conversion paths"],
    answers: ["Which topics deserve new pages", "Which assets need refresh", "Where internal links should change"],
    method: ["Topic clustering", "Intent mapping", "Coverage review", "Conversion-content alignment"],
    findings: ["Decision-stage gap", "Authority topic underbuilt", "Refresh opportunity", "Internal-link path needs review"],
    priority: ["Revenue-relevant topics", "Authority-building clusters", "Refresh queue", "Conversion support pages"],
    output: ["Cluster map", "Intent matrix", "Content coverage ledger", "Internal-link opportunity list"],
    roadmap: ["Build priority gaps", "Refresh decaying assets", "Connect supporting pages", "Measure coverage quality"],
    services: ["content-marketing", "seo-agency", "seo-audit"],
    industries: ["education-seo", "travel-seo", "saas-seo"],
  }),
  "local-seo-audit": sample({
    slug: "local-seo-audit",
    title: "Local SEO Audit",
    shortLabel: "Local SEO",
    focus: "Local presence, Google Business Profile readiness, landing pages, review signals, citations, and conversion paths.",
    question: "Can local buyers find, trust, and act on the business in each service area?",
    visual: "Local presence map and conversion path",
    inputs: ["Local landing pages", "Business profile fields", "Review themes", "Citation consistency", "Service-area pages"],
    answers: ["Which local signals need work", "Where landing-page coverage is thin", "How conversion paths should improve"],
    method: ["Presence review", "Profile readiness check", "Review-signal classification", "Local page architecture"],
    findings: ["Service-area content gap", "Profile completeness needs review", "Citation consistency issue", "Conversion path friction"],
    priority: ["Core location signals", "Service landing pages", "Review response system", "Conversion route cleanup"],
    output: ["Local presence map", "GBP review framework", "Citation consistency table", "Local conversion path"],
    roadmap: ["Normalize local data", "Improve local pages", "Strengthen review signals", "Validate lead paths"],
    services: ["local-seo", "seo-audit", "content-marketing"],
    industries: ["franchise-local-seo", "healthcare-seo", "legal-immigration-seo"],
  }),
  "ecommerce-search-architecture": sample({
    slug: "ecommerce-search-architecture",
    title: "eCommerce Search Architecture Review",
    shortLabel: "eCommerce architecture",
    focus: "Category hierarchy, product discoverability, faceted-navigation risk, buying intent, and internal links.",
    question: "Can search engines and shoppers move through the catalog without waste or confusion?",
    visual: "Category tree and faceted-navigation risk map",
    inputs: ["Category tree", "Product hierarchy", "Facet rules", "Buying intent", "Merchandising paths"],
    answers: ["Which categories need consolidation", "Which facets create risk", "How buying intent maps to architecture"],
    method: ["Catalog architecture review", "Facet-risk classification", "Intent-to-category mapping", "Internal-link review"],
    findings: ["Facet control needs review", "Category depth imbalance", "Product path dependency", "Buying-intent mismatch"],
    priority: ["Indexable category control", "Priority category pages", "Product-link architecture", "Merchandising search path"],
    output: ["Category tree", "Facet risk ledger", "Buying-intent map", "Internal-link architecture"],
    roadmap: ["Control indexation", "Reshape key categories", "Connect products and guides", "Measure crawl quality"],
    services: ["ecommerce-seo", "technical-seo", "content-marketing"],
    industries: ["ecommerce-seo", "travel-seo", "saas-seo"],
  }),
  "international-seo-market-map": sample({
    slug: "international-seo-market-map",
    title: "International SEO Market Map",
    shortLabel: "International map",
    focus: "Country and language priorities, localization depth, hreflang architecture, regional intent, and rollout sequence.",
    question: "Which markets should be served first, and what localization depth is required?",
    visual: "Country-language matrix and rollout board",
    inputs: ["Country targets", "Language coverage", "Regional intent", "Hreflang structure", "Localization resources"],
    answers: ["Which markets are ready", "Where localization needs depth", "Which technical signals must be corrected"],
    method: ["Market context review", "Language-depth mapping", "Hreflang architecture", "Rollout sequencing"],
    findings: ["Localization depth gap", "Hreflang needs review", "Regional intent mismatch", "Rollout dependency"],
    priority: ["Market readiness", "Language architecture", "Regional content depth", "Technical validation"],
    output: ["Country-language matrix", "Localization depth board", "Hreflang architecture", "Rollout sequence"],
    roadmap: ["Select priority markets", "Fix language architecture", "Build regional content", "Validate international signals"],
    services: ["international-seo", "technical-seo", "content-marketing"],
    industries: ["travel-seo", "education-seo", "saas-seo"],
  }),
  "ppc-organic-intelligence": sample({
    slug: "ppc-organic-intelligence",
    title: "PPC + Organic Search Intelligence Review",
    shortLabel: "PPC + organic",
    focus: "Shared intent, paid and organic overlap, landing-page alignment, conversion tracking readiness, and budget logic.",
    question: "Where should paid and organic search share intelligence instead of competing blindly?",
    visual: "Shared intent map and overlap ledger",
    inputs: ["Search terms", "Organic targets", "Landing pages", "Conversion tracking", "Message alignment"],
    answers: ["Where paid informs SEO", "Where organic can reduce waste", "Which pages need alignment before scaling"],
    method: ["Intent classification", "Overlap review", "Landing-page alignment", "Tracking readiness check"],
    findings: ["Shared intent opportunity", "Landing-page mismatch", "Tracking readiness needs review", "Organic coverage gap"],
    priority: ["High-intent shared terms", "Landing-page fixes", "Tracking validation", "Organic content support"],
    output: ["Intent map", "Paid-organic overlap table", "Landing-page alignment board", "Budget-priority logic"],
    roadmap: ["Classify shared terms", "Align landing pages", "Validate tracking", "Use PPC learning for SEO"],
    services: ["ppc-management", "seo-agency", "content-marketing"],
    industries: ["saas-seo", "ecommerce-seo", "education-seo"],
  }),
  "90-day-search-growth-roadmap": sample({
    slug: "90-day-search-growth-roadmap",
    title: "90-Day Search Growth Roadmap",
    shortLabel: "90-day roadmap",
    focus: "Execution sequencing, ownership lanes, dependencies, measurement plans, and decision gates for the next 30/60/90 days.",
    question: "What should the team do first, next, and later without promising rankings on a fixed timeline?",
    visual: "30/60/90 execution board and dependency map",
    inputs: ["Audit findings", "Business priorities", "Team capacity", "Dependencies", "Measurement readiness"],
    answers: ["Which actions lead the sequence", "Who owns each lane", "Which decisions must be made before execution"],
    method: ["Findings synthesis", "Dependency mapping", "Owner-lane planning", "Measurement design"],
    findings: ["Critical first dependency", "Owner lane needs confirmation", "Measurement confidence gap", "Decision gate required"],
    priority: ["First 30 days", "Days 31-60", "Days 61-90", "Next decision gate"],
    output: ["Execution board", "Owner lanes", "Dependency map", "Measurement plan"],
    roadmap: ["Stabilize foundations", "Build priority assets", "Validate implementation", "Review and adjust"],
    services: ["seo-agency", "seo-audit", "seo-mentor-service"],
    industries: ["saas-seo", "travel-seo", "franchise-local-seo"],
  }),
} satisfies Record<SampleAuditSlug, SampleAudit>;

export const work: WorkContent = {
  ui: {
    home: "Home",
    work: "Work",
    breadcrumb: "Breadcrumb",
    disclosureLabel: "Disclosure",
    illustrativeSample: "Illustrative sample",
    verifiedCaseStudy: "Verified case study",
    verifiedClientResult: "Verified client result",
    confidentialEngagement: "Confidential engagement",
    privateReference: "Private reference",
    noPublicCaseStudiesTitle: "No public named case studies are displayed without verified evidence.",
    noPublicResultsTitle: "No public client results are displayed without verified measurement context.",
    noPublicRegistryBody:
      "Taskcover publishes only records with verified public permission, verified evidence, complete context, public disclosure, and approved wording.",
    publicRegistry: "Public registry",
    evidenceRequired: "Evidence required",
    measurementContext: "Measurement context",
    explore: "Explore",
    viewSample: "View sample",
    getAudit: "Get a Free SEO Audit",
    bookCall: "Book a Strategy Call",
    relatedSamples: "Related sample deliverables",
    relatedServices: "Related services",
    relatedIndustries: "Related industries",
    priority: "Priority",
    status: "Status",
    input: "Input",
    method: "Method",
    output: "Output",
  },
  channelLinks: [
    { label: "Case Studies", href: "/work/case-studies", description: "A future-safe registry for named client stories once evidence is approved." },
    { label: "Sample Audits", href: "/work/sample-audits", description: "Illustrative deliverables that show how Taskcover thinks and packages work." },
    { label: "Search Growth Frameworks", href: "/work/search-growth-frameworks", description: "The operating model that turns research into execution." },
    { label: "Client Results", href: "/work/client-results", description: "The measurement standard for publishing verified outcomes." },
  ],
  sampleAuditLinks: sampleOrder.map((slug) => ({
    label: samples[slug].title,
    href: `/work/sample-audits/${slug}`,
    description: samples[slug].focus,
  })),
  hub: {
    metaTitle: "Work, Sample Audits, and Search Growth Systems | Taskcover Agency",
    metaDescription:
      "Explore Taskcover's sample deliverables, search growth framework, case-study standards, and verified client-result publication rules.",
    eyebrow: "Work system",
    h1: "From search intelligence to execution",
    intro:
      "Taskcover's work is structured around evidence, diagnosis, prioritization, implementation support, measurement, and learning. Public proof is separated from illustrative methodology.",
    command: [
      { label: "Research", detail: "Market, search, content, technical, and buyer context.", status: "Assessed" },
      { label: "Diagnostics", detail: "Constraints, opportunities, and confidence are separated.", status: "Validated" },
      { label: "Strategy", detail: "Recommendations are tied to business relevance and search demand.", status: "Prioritized" },
      { label: "Execution roadmap", detail: "Actions are sequenced by dependency and owner readiness.", status: "Mapped" },
      { label: "Measurement", detail: "Outcomes require source, baseline, timeframe, and context.", status: "Ready for execution" },
      { label: "Iteration", detail: "Learning loops reshape the next cycle of work.", status: "Validated" },
    ],
    systemMap: [
      { label: "Sample audits", detail: "Show deliverable structure without client claims.", connectsTo: "Strategy roadmaps" },
      { label: "Search-growth frameworks", detail: "Explain the operating logic behind the work.", connectsTo: "Execution lanes" },
      { label: "Case studies", detail: "Render only when permission and evidence are verified.", connectsTo: "Public proof" },
      { label: "Client results", detail: "Require measurement sources, baseline, timeframe, and context.", connectsTo: "Reporting systems" },
      { label: "Strategy roadmaps", detail: "Convert findings into sequenced work.", connectsTo: "Implementation support" },
      { label: "Reporting systems", detail: "Keep learning tied to confidence and attribution limits.", connectsTo: "Iteration" },
    ],
    actionFlow: [
      { label: "Research", detail: "Collect context and search demand.", status: "Assessed" },
      { label: "Diagnosis", detail: "Find blockers, gaps, and leverage points.", status: "Validated" },
      { label: "Priority model", detail: "Judge impact, effort, dependency, and confidence.", status: "Prioritized" },
      { label: "Roadmap", detail: "Translate work into owner-ready actions.", status: "Mapped" },
      { label: "Implementation support", detail: "Guide changes through real constraints.", status: "Ready" },
      { label: "Measurement", detail: "Read outcomes with context and limitations.", status: "Reviewed" },
    ],
    evidenceMatrix: [
      { label: "Illustrative sample", detail: "Public methodology only; no client identity or result claim.", status: "Allowed with disclosure" },
      { label: "Verified case study", detail: "Requires permission, context, evidence, approved wording, and assets.", status: "Evidence-gated" },
      { label: "Verified client result", detail: "Requires source, baseline, timeframe, methodology, and attribution context.", status: "Evidence-gated" },
      { label: "Confidential engagement", detail: "No identity, metric, quote, screenshot, source URL, or engagement detail is exposed.", status: "Protected" },
      { label: "Private reference", detail: "Shared only through approved qualification and permission paths.", status: "Controlled" },
    ],
    cta: {
      title: "Start with a search audit that can become an execution roadmap.",
      description: "The initial audit can review technical health, search demand, content authority, AI search readiness, market opportunity, and 90-day priorities.",
      preview: ["Technical health", "Search demand", "Content authority", "AI search readiness", "Market opportunity", "90-day priorities"],
    },
  },
  pages: {
    "case-studies": {
      metaTitle: "Evidence-Based Case Study Standards | Taskcover Agency",
      metaDescription: "How Taskcover publishes case studies only when public permission, evidence, context, wording, and assets are verified.",
      eyebrow: "Case-study standard",
      h1: "Case studies with evidence and context",
      intro: "Taskcover does not publish invented success stories. This page explains how future public case studies must be verified before they appear.",
    },
    "sample-audits": {
      metaTitle: "Sample SEO Audits and Deliverables | Taskcover Agency",
      metaDescription: "Explore eight illustrative Taskcover sample deliverables covering technical SEO, AI search, content, local, eCommerce, international, PPC, and roadmaps.",
      eyebrow: "Sample deliverables",
      h1: "See how Taskcover thinks",
      intro: "These sample audits demonstrate methodology, analysis structure, and execution translation without representing real client engagements or results.",
    },
    "search-growth-frameworks": {
      metaTitle: "Search Growth Operating Framework | Taskcover Agency",
      metaDescription: "Taskcover's Discover, Diagnose, Prioritize, Build, Measure, and Learn framework for turning search intelligence into execution.",
      eyebrow: "Operating framework",
      h1: "The search growth operating framework",
      intro: "Search growth works best as an operating system: context, intelligence, priority logic, execution architecture, measurement, and governance.",
    },
    "client-results": {
      metaTitle: "Verified Client Results Publication Standard | Taskcover Agency",
      metaDescription: "Taskcover's framework for publishing client results only with verified evidence, public permission, baseline, timeframe, source, and context.",
      eyebrow: "Results standard",
      h1: "Results with measurement context",
      intro: "Client outcomes are published only when the evidence is verified, public permission is clear, and the measurement context is complete.",
    },
  },
  caseStudies: {
    registryIntro: "Named case studies can be useful only when buyers can understand the work, context, evidence, and limits behind the result.",
    verification: [
      { label: "Identity permission", detail: "The client or organization has approved public naming.", status: "Required" },
      { label: "Engagement context", detail: "Scope, market, services, and constraints are documented.", status: "Required" },
      { label: "Measurement source", detail: "Outcome sources are verified and approved for public use.", status: "Required" },
      { label: "Approved wording and assets", detail: "Claims, quotes, screenshots, and visuals are reviewed before publishing.", status: "Required" },
    ],
    requiredEvidence: [
      "Client identity permission",
      "Engagement context",
      "Baseline context",
      "Methodology",
      "Timeframe",
      "Measurement source",
      "Outcome context",
      "Approved wording",
      "Approved assets",
    ],
    structure: [
      { label: "Context", detail: "What problem the engagement was allowed to solve.", status: "Documented" },
      { label: "Method", detail: "What Taskcover changed or advised.", status: "Explained" },
      { label: "Evidence", detail: "What source supports the claim.", status: "Verified" },
      { label: "Limits", detail: "What cannot be attributed or disclosed.", status: "Stated" },
    ],
    confidential: [
      { label: "No private identifiers", detail: "Names, domains, screenshots, quotes, and source URLs stay hidden.", status: "Protected" },
      { label: "Private reference path", detail: "References require qualification and permission.", status: "Controlled" },
      { label: "Evidence is not exposed", detail: "Internal documents never become public proof by default.", status: "Private" },
    ],
    cta: {
      title: "Need to evaluate how Taskcover would approach your market?",
      description: "Use the sample deliverables to review methodology, then request an audit for your own search context.",
    },
  },
  sampleAudits: {
    selectorIntro: "Use the library to compare the kind of questions each deliverable answers and how findings become priorities.",
    comparison: [
      { label: "Technical risk", detail: "Architecture, indexation, rendering, schema, and release dependencies.", status: "Diagnostic" },
      { label: "Demand and content", detail: "Topic coverage, intent, authority, conversion support, and refresh needs.", status: "Strategic" },
      { label: "Market systems", detail: "Local, eCommerce, international, and paid-organic search structure.", status: "Operational" },
      { label: "Execution planning", detail: "Roadmaps, ownership lanes, decision gates, and measurement plans.", status: "Actionable" },
    ],
    everyAudit: ["Clear buyer question", "Data inputs", "Analysis method", "Findings structure", "Priority logic", "Roadmap translation", "Visible disclosure"],
    priorityFlow: [
      { label: "Severity", detail: "What blocks access, trust, or conversion.", status: "Assessed" },
      { label: "Business relevance", detail: "How closely the issue connects to buyer demand.", status: "Mapped" },
      { label: "Implementation effort", detail: "What resources or dependencies are required.", status: "Estimated" },
      { label: "Measurement confidence", detail: "How clearly future change can be read.", status: "Qualified" },
    ],
    disclosureTitle: "Illustrative data is not client evidence.",
    disclosureBody: disclosure,
    cta: {
      title: "Turn a sample structure into a real audit.",
      description: "Taskcover can apply the relevant framework to your site, market, content system, or search-growth plan.",
    },
  },
  frameworks: {
    stages: [
      { label: "Discover", detail: "Business model, buyers, market, and search surfaces.", status: "Context" },
      { label: "Diagnose", detail: "Technical constraints, demand gaps, authority needs, and conversion friction.", status: "Intelligence" },
      { label: "Prioritize", detail: "Business relevance, search demand, dependency, effort, and confidence.", status: "Decision" },
      { label: "Build", detail: "Pages, technical fixes, authority assets, local systems, and measurement setup.", status: "Execution" },
      { label: "Measure", detail: "Visibility, coverage, health, readiness, lead quality, and reporting confidence.", status: "Learning" },
      { label: "Learn", detail: "Adjust the next cycle based on evidence and attribution limits.", status: "Iteration" },
    ],
    prioritization: [
      { label: "Business relevance", detail: "Does the action support a meaningful buyer or market?", status: "Required" },
      { label: "Search demand", detail: "Is there a qualified demand signal?", status: "Required" },
      { label: "Technical dependency", detail: "Does another fix need to happen first?", status: "Sequenced" },
      { label: "Authority requirement", detail: "Does the topic need proof, links, expertise, or third-party validation?", status: "Assessed" },
      { label: "Conversion impact", detail: "Can the action improve decision paths without inventing impact claims?", status: "Qualified" },
      { label: "Measurement confidence", detail: "Can future performance be read with enough context?", status: "Qualified" },
    ],
    execution: [
      { label: "Technical lane", detail: "Crawl, indexation, performance, schema, templates, and migrations.", status: "Owner-ready" },
      { label: "Content lane", detail: "Briefs, pages, refreshes, internal links, and answer-ready assets.", status: "Owner-ready" },
      { label: "Authority lane", detail: "Proof, digital PR, citations, expertise signals, and source reinforcement.", status: "Owner-ready" },
      { label: "Measurement lane", detail: "Dashboards, source checks, baselines, and decision reviews.", status: "Owner-ready" },
    ],
    measurement: [
      { label: "Non-brand visibility", detail: "Read with query intent and market context.", status: "Contextual" },
      { label: "Technical health", detail: "Track fixes that improve crawl and rendering reliability.", status: "Operational" },
      { label: "Content coverage", detail: "Review topic completeness and buyer-path support.", status: "Strategic" },
      { label: "AI answer readiness", detail: "Assess entity clarity and citation-source strength.", status: "Qualified" },
    ],
    governance: [
      { label: "Decision record", detail: "Why priorities were selected.", status: "Documented" },
      { label: "Owner lanes", detail: "Who needs to act and what they need.", status: "Assigned" },
      { label: "Review cadence", detail: "When evidence is reviewed and priorities change.", status: "Scheduled" },
      { label: "Disclosure rules", detail: "What may be public, private, or withheld.", status: "Controlled" },
    ],
    serviceMapping: [
      { label: "SEO Strategy", detail: "Owns the operating model and priority decisions.", status: "Core" },
      { label: "Technical SEO", detail: "Resolves search-access and platform constraints.", status: "Foundation" },
      { label: "Content Marketing", detail: "Builds the content system around demand and authority.", status: "Growth" },
      { label: "PPC Management", detail: "Feeds paid-search intelligence into organic decisions.", status: "Connected" },
    ],
    industryMapping: [
      { label: "Travel", detail: "Market, destination, and seasonal demand architecture.", status: "Adapted" },
      { label: "Education", detail: "Program intent, trust, and admissions decision paths.", status: "Adapted" },
      { label: "Healthcare", detail: "Service-area trust, local pathways, and compliance-aware content.", status: "Adapted" },
      { label: "SaaS and eCommerce", detail: "Product, category, and buying-journey architecture.", status: "Adapted" },
    ],
    cta: {
      title: "Use the framework to choose the right next move.",
      description: "A Taskcover audit turns the operating model into priorities for your specific market, site, and team constraints.",
    },
  },
  clientResults: {
    registryIntro: "Public results require measurement context. A metric without baseline, source, timeframe, and methodology can mislead buyers.",
    requirements: [
      { label: "Verified evidence", detail: "The source can be checked and is approved for use.", status: "Required" },
      { label: "Public permission", detail: "The client has approved public disclosure.", status: "Required" },
      { label: "Baseline and timeframe", detail: "The starting context and time window are clear.", status: "Required" },
      { label: "Relevant methodology", detail: "The work behind the outcome is documented.", status: "Required" },
      { label: "Approved wording", detail: "The claim is reviewed and not overstated.", status: "Required" },
    ],
    metricContext: [
      { label: "Qualified organic demand", detail: "Demand quality matters more than raw visibility.", status: "Context" },
      { label: "Non-brand visibility", detail: "Separated from brand demand where possible.", status: "Context" },
      { label: "Technical health", detail: "Interpreted as an operational signal.", status: "Context" },
      { label: "Content coverage", detail: "Read against topic and buyer-path completeness.", status: "Context" },
      { label: "AI answer readiness", detail: "Assessed as readiness, not a fake platform claim.", status: "Context" },
      { label: "Lead quality", detail: "Evaluated only with approved sources and limitations.", status: "Context" },
    ],
    attribution: [
      "Search performance can be affected by market demand, seasonality, brand activity, platform changes, paid media, product changes, and site releases.",
      "Taskcover does not publish isolated metrics as proof without explaining source, baseline, timeframe, methodology, and limitations.",
      "Confidential evidence remains private even when it supports internal decision-making.",
    ],
    confidential: [
      { label: "No exposed identity", detail: "Client names, domains, screenshots, and source URLs are withheld.", status: "Protected" },
      { label: "No exposed metrics", detail: "Private metrics are not transformed into anonymous public claims.", status: "Protected" },
      { label: "No implied endorsement", detail: "Private work is not used as public proof.", status: "Protected" },
    ],
    methodology: [
      { label: "Audit", detail: "Evidence informs what should be changed.", status: "Input" },
      { label: "Roadmap", detail: "Priorities sequence the work.", status: "Plan" },
      { label: "Implementation", detail: "Changes move through team and platform constraints.", status: "Action" },
      { label: "Measurement review", detail: "Results are read with context and limitations.", status: "Learning" },
    ],
    cta: {
      title: "Measure the work before publishing the result.",
      description: "Taskcover can help define a clean search-growth measurement framework for future client reporting.",
    },
  },
  samples,
};
